### ISSUE TITLE
notifyDataSetChanged() 报错

### ISSUE THREAD

**Issue by hetianpeng** [alibaba/vlayout#10]
我有 7 个卡片。
第 7 个卡片一开始有 10 条数据，点击 button 添加 10 条数据并 notifyDataSetChanged()。
第一次点击 button 由 10条数据变成 20 条，成功。
第二次点击 button 由 20条数据变成 30 条，失败。
![image](https://cloud.githubusercontent.com/assets/5644311/23651795/9f594dbc-0361-11e7-8476-7fea2f3b4530.png)

下面是我 debug 的过程截图。
第一次点击 button：
![image](https://cloud.githubusercontent.com/assets/5644311/23651955/252b08d6-0362-11e7-9135-ee1b0b59aa9e.png)

第二次点击 button：
![image](https://cloud.githubusercontent.com/assets/5644311/23652020/54142f1a-0362-11e7-80d7-6934d5d26273.png)

可以看到 helpers 的 size == 0，不知道为什么。

下面是我刷新的代码，不知道是不是我刷新的方式错了，希望能解答下，谢谢！
![image](https://cloud.githubusercontent.com/assets/5644311/23652205/f4f63d38-0362-11e7-8205-27af0db98194.png)

**Comment by longerian** [comment]
将 demo 代码传递 github 上，我调一下看看

**Comment by hetianpeng** [comment]
[demo地址](https://github.com/hetianpeng/VlayoutDemo)

又发现一个问题：
GridLayoutHelper 一行 4 列等分屏幕宽
![image](https://cloud.githubusercontent.com/assets/5644311/23659850/7ff717b2-0382-11e7-9be7-4e184cf34b28.png)
第一次添加数据后，notifyDataSetChanged() 后变了样子。
![image](https://cloud.githubusercontent.com/assets/5644311/23659904/ad428c06-0382-11e7-8664-08432dc00be7.png)

**Comment by longerian** [comment]
第一个问题参考 bugfix/1.0.2 的修复。

第二个问题GridLayoutHelper 一行 4 列等分屏幕宽 这个问题没有复现过。

**Comment by hetianpeng** [comment]
第一个问题修复后，第二个问题就没复现，刚试了下。
