### ISSUE TITLE
StickyLayoutHelper的setBgColor()无效

### ISSUE THREAD

**Issue by zhufengi** [alibaba/vlayout#100]
设置之后没有反应，同样的颜色在其他helper设置是有效的，还有一个就是可以自己自定义布局吗，在StickyLayoutHelper中

**Comment by longerian** [comment]
这种悬浮类型的布局，背景色是不支持的。
自定义布局也可以，需要你单独写layoutHelper注册进来。

**Comment by zhufengi** [comment]
LayoutHelper可以加载layout有例子吗，VLayout有群吗

**Comment by yongchao1210** [comment]
VLayout有QQ群吗？有的话加一个方便交流！！！

**Comment by longerian** [comment]
目前还没有人力维护QQ群来答疑，请谅解。

**Comment by longerian** [comment]
@yongchao1210  新建了qq群可以交流
