### ISSUE TITLE
vlayout使用起来非常卡

### ISSUE THREAD

**Issue by object1984** [alibaba/vlayout#101]
new DelegateAdapter(mVirtualLayoutManager, false);

这个参数是true 还是 false 都非常卡。。。请问可能是什么地方出现了问题呢

**Comment by longerian** [comment]
看一下日志，有没有内部跑异常
检查复用的问题，有没有滑动过程中反复创建view

**Comment by zhangkuo0216** [comment]
的确有内部bug  复用的时候 viewHoder转换错误。请问怎么解决呢？

**Comment by omyrobin** [comment]
尝试设置RecyclerView.RecycledViewPool(); 
viewPool.setMaxRecycledViews(X, Y); 有几种类型的ItemType就设置几个
X从0开始加，Y根据自己的需求加；

**Comment by Smilefanlei** [comment]
请问，这个viewPool.setMaxRecycledViews(X, Y);   这个X对应的是什么？是几种adapter？

**Comment by longerian** [comment]
@omyrobin 对回收复用池的理解是正确的。
@zhangkuo0216 @object1984 类型转换错误，需要正确地设置 viewType，参考 FAQ：https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md
