### ISSUE TITLE
GridLayoutHelper在setAutoExpand(true)的时候，如果数据不足，首次显示正常

### ISSUE THREAD

**Issue by blesslp** [alibaba/vlayout#107]
GridLayoutHelper在setAutoExpand(true)的时候，
如果数据不足，首次显示正常，可以自适应的拉伸铺满空间
************
|        |       |
************

但是一滑动下去，再拉回来的时候，就变成autoExpand=false的效果了，
************
|    |    |    
************

**Comment by longerian** [comment]
已知问题

**Comment by longerian** [comment]
等 1.0.9
