### ISSUE TITLE
做monkey的时候出现了classcastexception

### ISSUE THREAD

**Issue by chen28683** [alibaba/vlayout#116]
有好几种type，对应不同的viewholder。发现把index为0的viewholder传给了index为2的viewholder，导致了classcast异常。大家见过这种情况么

java.lang.ClassCastException: HomePageHeadAdapter$HeadViewHolder cannot be cast to .HomePageBannerAdapter$MainViewHolder
===Crash num 3 Message===06-26 09:02:28.441  1616  1616 E AndroidRuntime: 	at HomePageBannerAdapter$PagerAdapter.onBindViewHolder(HomePageBannerAdapter.java:121)

**Comment by longerian** [comment]
参考这个问题 #72

**Comment by chen28683** [comment]
我们的itemviewtype是没问题的，每个子adapter的viewtype都不一样，按道理不会有这个问题吧？还是我理解错了。问题是偶现的，很难复现。

**Comment by longerian** [comment]
子adapter的viewtype是否要一样，是你可以控制的，通过`public DelegateAdapter(VirtualLayoutManager layoutManager, boolean hasConsistItemType)`的第二个参数。
所以要看你传递的是true还是false，出现类型转换的错误一定是不同类型的viewtype之间复用导致的。

**Comment by longerian** [comment]
没有异议就关闭啦
