### ISSUE TITLE
多Adapter崩溃

### ISSUE THREAD

**Issue by qq8803128** [alibaba/vlayout#117]
错误代码
`W/System.err: java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.second' on a null object reference
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at com.alibaba.android.vlayout.DelegateAdapter.findAdapterByIndex(DelegateAdapter.java:456)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at com.alibaba.android.vlayout.DelegateAdapter.onCreateViewHolder(DelegateAdapter.java:122)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1607)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:978)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at com.alibaba.android.vlayout.layout.StickyLayoutHelper.layoutViews(StickyLayoutHelper.java:102)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:280)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:574)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1140)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:358)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:398)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
06-29 10:32:14.515 4375-4375/com.xinkuai.mobile W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.View.layout(View.java:17647)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.View.layout(View.java:17647)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1217)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.View.layout(View.java:17647)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.View.layout(View.java:17647)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.View.layout(View.java:17647)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.View.layout(View.java:17647)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.View.layout(View.java:17647)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.View.layout(View.java:17647)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.View.layout(View.java:17647)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2407)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2129)
06-29 10:32:14.516 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1315)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6420)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:688)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:623)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at android.os.Looper.loop(Looper.java:154)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6165)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
06-29 10:32:14.517 4375-4375/com.xinkuai.mobile W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)`

代码设置
`
       val layoutManager = VirtualLayoutManager(this)

        binding.recyclerView.setLayoutManager(layoutManager)

        val viewPool = RecyclerView.RecycledViewPool()
        viewPool.setMaxRecycledViews(0, 20)
        binding.recyclerView.setRecycledViewPool(viewPool)

        mAdapter = DelegateAdapter(layoutManager, false)
        binding.recyclerView.setAdapter(mAdapter)

        val adapters = LinkedList<DelegateAdapter.Adapter<*>>()

        for (i in mBeanHelper!!.adapterLists(bean.data, true, true)) {
            val helper = mBeanHelper!!.createLayoutHelper(i[0].layoutHelper)
            if (i[0].aspectRatio > 0.0f) {
                helper.aspectRatio = i[0].aspectRatio
            }
            val adapter = BaseAdapter(binding.recyclerView, helper, mAdapterHelper)
            adapter.set(i)
            adapters.add(adapter)
        }
        mAdapter?.setAdapters(adapters)
`

BaseAdapter
`
public class BaseAdapter extends DelegateAdapter.Adapter {
    private LayoutHelper mLayoutHelper;
    private RecyclerView mRecyclerView;
    private AdapterHelper mAdapterHelper;
    private List<ItemBean.DataBean> items = new ArrayList<>();

    public BaseAdapter(RecyclerView recyclerView, LayoutHelper helper, AdapterHelper adapterHelper) {
        super();
        mLayoutHelper = helper;
        mRecyclerView = recyclerView;
        mAdapterHelper = adapterHelper;
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return mAdapterHelper.create(viewType, mRecyclerView);
    }

    @Override
    public void onViewDetachedFromWindow(RecyclerView.ViewHolder holder) {
        super.onViewDetachedFromWindow(holder);
        if (holder instanceof BaseHolder) {
            ((BaseHolder) holder).unbind();
        }
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        if (holder instanceof BaseHolder) {
            if (mLayoutHelper instanceof GridLayoutHelper) {
                ((BaseHolder) holder).bind(position, items.get(0));
            }else {
                ((BaseHolder) holder).bind(position, items.get(position));
            }
        }
    }

    @Override
    public int getItemViewType(int position) {
        if (mLayoutHelper instanceof GridLayoutHelper) {
            return items.get(0).type;
        }
        return items.get(position).type;
    }

    @Override
    public int getItemCount() {
        if (mLayoutHelper instanceof GridLayoutHelper) {
            return items.get(0).list.size();
        }
        return items.size();
    }

    @Override
    public LayoutHelper onCreateLayoutHelper() {
        return mLayoutHelper;
    }

    public void set(List<ItemBean.DataBean> items) {
        if (this.items == items) {
            return;
        }
        List<ItemBean.DataBean> removes = new ArrayList<>();
        for (ItemBean.DataBean item : items) {
            if (!mAdapterHelper.isRegist(item.type)) {
                removes.add(item);
            }
        }

        for (ItemBean.DataBean item : removes) {
            items.remove(item);
        }
        this.items = items;
    }

}

`

如果不重写BaseAdapter.getItemViewType方法就没事

**Comment by longerian** [comment]
参考 http://pingguohe.net/2017/05/03/the-beauty-of-math-in-vlayout.html  理解一下DelegateAdapter(layoutManager, false) 第二个参数的含义，你可能需要传递一个true。看你的需求。

**Comment by longerian** [comment]
还有 #126 ，也可以参考一下。
