### ISSUE TITLE
动态的更换adpter，无法显示更换后的adpter

### ISSUE THREAD

**Issue by yihuajia** [alibaba/vlayout#121]
A、B、C、D四个adpter，C是需要根据状态来替换的，换成E。通过日志查看，在delegateAdapter确实是把C替换成E了，但是界面上显示的却还是C。有调用delegateAdapter.notifyDataSetChanged();

**Comment by longerian** [comment]
如果只是把`List<Adapter> adapters`里的C换成E，再调用`delegateAdapter.notifyDataSetChanged();`是不行的，因为内部的layoutHelper映射关系没有变更，需要重新调用`setAdapters`替换更新。

**Comment by yihuajia** [comment]
恩，没去了解原理。如果delegateAdapter单个的add，先remove再add也还是，也有调用delegateAdapter.notifyDataSetChanged();也还是无法显示替换后的。甚至是粗暴点在add之前delegateAdapter.clear了，还是无法把C换成E。。

**Comment by yihuajia** [comment]
那按照您的意思就是如果要动态更换的话就直接对List<Adapter> adapters这个进行操作，然后再去setAdapters?

**Comment by longerian** [comment]
是的

**Comment by yihuajia** [comment]
刚刚试了还是无法完成更新，我是在完成替换之后再去setAdapters。
代码简化如下：
       adapterList.add(new A(data));
        adapterList.add(new B(data));
        adapterList.add(new C(data));
        adapterList.add(new D(data));

        if (条件1成立) {
            adapterList.add(2, new E(data));        
        } else if (条件2成立)) {
            adapterList.add(2, new F(data));
        } else if (条件3成立) {
            adapterList.add(2, new G(data));
        }
        for (DelegateAdapter.Adapter adapter : adapterList) {
            Timber.d("adapter ---- " + adapter.toString());
        }
        delegateAdapter.setAdapters(adapterList);
打印出来的日志是插入在C的前面了。。。

**Comment by longerian** [comment]
adapter应该已经换了 ，确认一下是不是view的显示有问题

**Comment by yihuajia** [comment]
view的显示是没有问题的，这块已经确认过了，也不知道是什么情况。已经放弃用这种动态更换adapter的方式去实现了

**Comment by ruodezizaiyi** [comment]
@longerian 我也试了多次使用setAdapters(),界面明显出现错误情况,特别的使用了delegateAdatper.clear(),发现还是没用....

**Comment by longerian** [comment]
我试试看

**Comment by longerian** [comment]
@yihuajia @ruodezizaiyi 
我在Demo里测试了一下，是可以替换的，当然你们的业务逻辑可能更多一些，但基本的功能应该是可以的。
```
findViewById(R.id.jump).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //EditText position = (EditText) findViewById(R.id.position);
                //if (!TextUtils.isEmpty(position.getText())) {
                //    try {
                //        int pos = Integer.parseInt(position.getText().toString());
                //        recyclerView.scrollToPosition(pos);
                //    } catch (Exception e) {
                //        Log.e("VlayoutActivity", e.getMessage(), e);
                //    }
                //} else {
                //    recyclerView.requestLayout();
                //}
                adapters.remove(3);
                GridLayoutHelper layoutHelper1 = new GridLayoutHelper(2);
                adapters.add(3, new SubAdapter(VLayoutActivity.this, layoutHelper1, 4));
                delegateAdapter.setAdapters(adapters);
                delegateAdapter.notifyDataSetChanged();
            }
        });
```

linear区替换成了grid
<img width="280" alt="2017-07-03 10 10 08" src="https://user-images.githubusercontent.com/1511489/27796446-93964b46-603c-11e7-8087-151660ebeb8d.png">


<img width="285" alt="2017-07-03 10 10 21" src="https://user-images.githubusercontent.com/1511489/27796445-9368f98e-603c-11e7-8597-a7e7450a6c4e.png">

**Comment by yihuajia** [comment]
有空我再去试试吧。。

**Comment by longerian** [comment]
检查一下是不是复用导致的view显示的错误

**Comment by softrice** [comment]
我看delegateAdapter.setAdapters(adapters);
后跟着
delegateAdapter.notifyDataSetChanged();
这是强制要求的么
