### ISSUE TITLE
DelegateAdapter 中的一个Adapter刷新，其他Adapter也刷新了

### ISSUE THREAD

**Issue by jobzwm** [alibaba/vlayout#125]
用 addAdapter 方法添加了 A、B、C、D 这4个adapter，然后调用 B.notifyDataSetChanged()，其他3个adapter也刷新了。

**Comment by longerian** [comment]
是的，如果只要更新局部，那就调用`public final void notifyItemChanged(int position)`这样的方法

**Comment by zhujian1989** [comment]
请问public final void notifyItemChanged(int position)方法对应的是哪一个类？delegateAdapter么？

**Comment by longerian** [comment]
是的

**Comment by ania93** [comment]
delegateAdapter.notifyItemChanged中position这个参数是adapter的位置索引么？还是view的绝对位置索引？

**Comment by longerian** [comment]
大的 DelegateADapter的 adapter 的位置的索引 @ania93
