### ISSUE TITLE
关于Example中的OnePlusLayoutActivity中的二个问题

### ISSUE THREAD

**Issue by qaz349293703** [alibaba/vlayout#126]
希望能帮忙看下我的疑问。可能说的比较烦。希望能耐心看完。谢谢了。。。

你好，我有二个疑问：

1：一个是这个Activity里面的布局的第一个是一个Banner，刚开始显示Banner0,我比如往左边滑动到了Banner3,我只要将Banner移出到屏幕外面。这个Banner貌似就被摧毁并又变成了Banner0，但是onViewRecycled方法并没有被调用，说明没有被移除。

2：第二个问题可能说起来比较烦。我尽可能说仔细点，就是代码里面这个Banner是用了new SubAdapter，然后如果我把
```
@Override
public int getItemViewType(int position) {
        return 1;
}
```
这段去除掉，那OK，接下去的里面覆写的方法也就都无效了。比如：``onCreateViewHolder``方法等，这样不管是设置Banner高度，还是内容，都没有了。因为这些覆写的方法开头都加了判断，判断是不是ViewPager。
```
@Override
public MainViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
      if (viewType == 1)
              return new MainViewHolder(
                   LayoutInflater.from(OnePlusNLayoutActivity.this).inflate(R.layout.view_pager, parent, false));

      return super.onCreateViewHolder(parent, viewType);
}
```
因为这时候viewType 默认就为0了。所以就调用了``return super.onCreateViewHolder(parent, viewType);``,这时候SubAdapter 的布局默认是一个包含了TextView 的FrametLayout。

所以这时候打开的时候你会发现，这个Banner变成了一个没有内容的，而且高度很小的一个方块。但是你把这个Banner滑出到屏幕外面，再回来，你会发现这个Banner里面的TextView被赋值为23，有时候赋值为24.而且高度又重新被赋值为300。但是并没有地方去设置高度和内容。因为我们覆写了设置高度的``onBindViewHolder``方法，和设置内容的``onBindViewHolderWithOffset``方法，但是里面也没有调用``super.onBindViewHolder``和``super.onBindViewHolderWithOffset``,感觉是和其他地方混乱冲突导致。不知道是为什么。。。

希望能帮忙看下原因。可能说的比较烦。谢谢了。。。

**Comment by longerian** [comment]
第一个问题：
因为是demo，写的比较简单
```
@Override
                public void onBindViewHolder(MainViewHolder holder, int position) {
                    if (holder.itemView instanceof ViewPager) {
                        ViewPager viewPager = (ViewPager) holder.itemView;

                        viewPager.setLayoutParams(new LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, 200));

                        // from position to get adapter
                        viewPager.setAdapter(new PagerAdapter(this, viewPool));
                    }
                }
```

这里每次复用的时候重置viewPager的adapter，所以都是从0开始。

**Comment by longerian** [comment]
第二个问题：
demo里的DelegateAdater设置了所有SubAdapter之间的类型是可以复用的（`new DelegateAdapter(layoutManager, true)`），默认的type=0。
当banner的那个SubAdapter覆盖了这个方法，它旗下的整个组件就是type=1。不会与其他区块复用。
```
@Override
public int getItemViewType(int position) {
        return 1;
}
```

但是你删除这个方法之后，启动第一次打开就显示默认的view那个view。当滑出去再滑回来的时候，复用了会复用另一个subAdapter示例显示view。

因为相同itemType之间是复用的，不光view复用，连adapter都复用。

具体的复用逻辑你可以看一下DelegateAdapter的源码，通过`mHasConsistItemType`来控制复用逻辑。

这一块还有一个文章可以参考：http://pingguohe.net/2017/05/03/the-beauty-of-math-in-vlayout.html

**Comment by qaz349293703** [comment]
感谢解疑。。。
