### ISSUE TITLE
如何添加一个横向滚动的adapter呢

### ISSUE THREAD

**Issue by diorslau** [alibaba/vlayout#127]
如题  我想在rv中加一个横向滚动的,但是看了LinearLayoutHelp  没看到有设置横向的方法,请假下如何做呢

**Comment by longerian** [comment]
可以参考demo里第一个banner，layoutHelper没有横向滚动的。

**Comment by jinxiyang** [comment]
同问，能提供一个实现横向滚动布局的思路吗？是要再嵌套一个recyclerview吗

**Comment by jamie1052741705** [comment]
使用RecyclerView嵌套使用，一直报错

 java.lang.ClassCastException: 
com.example.ui.main.home.BannerAdapter$BannerViewHolder cannot be cast to com.example..ui.main.home.HorizontalAdapter$HorizontalViewHolder
                                                                                 at com.example.ui.main.home.HorizontalAdapter.onBindViewHolder(HorizontalAdapter.java:21)

**Comment by svenjung** [comment]
横向布局整体当RecyclerView的一个item处理，跟例子里面的Banner实现差不多

**Comment by longerian** [comment]
@jinxiyang 是的
@jamie1052741705  检查一下类型，是不是返回错了。整理了一个FAQ：https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md
