### ISSUE TITLE
如何异步调用接口拿到数据之后动态设置 GridLayoutHelper 设置显示的列数呢？

### ISSUE THREAD

**Issue by xxst** [alibaba/vlayout#129]
初始化设置布局 GridLayoutHelper 的时候就让设置了 spanCount 属性。当我调用接口拿到数据之后 还能再次设置 GridLayoutHelper 的 setSpanCount 来改变布局显示吗？

我的目的是：想实现一行可以滑动的多张图片.

**Comment by longerian** [comment]
一行滑动需要做一个viewpager或者横向recyclerview包进去，gridlayouthelper本身不能横向滑。

**Comment by Zhaoyy** [comment]
@xxst 你可以根据拿到的数据重新整理你的``List<LayoutHelper>``，然后在设置到你的``VirtualLayoutAdapter.setLayoutHelpers()``中。
example:
```java
List<LayoutHelper> helpers = yourVirtualLayoutAdapter.getLayoutHelpers();
// 重新整理你的 LayoutHelpers
youtrVirtualLayoutAdapter.setLayoutHelpers(helpers);
youtrVirtualLayoutAdapter.notifyDataSetChanged();
```
