### ISSUE TITLE
如何刷新数据

### ISSUE THREAD

**Issue by qinguyi** [alibaba/vlayout#13]
可以提供个刷新数据的示例吗？数据改变需要重新delegateAdapter.setAdapters(adapters)吗

**Comment by longerian** [comment]
调用对应数据有变更的 ```DelegateAdapter.Adapter```  的 ```notifyDataSetChanged()``` 方法即可，目前 master 分支上存在 bug，用 bugfix/1.0.2 分支代码。
周末发布一个小版本，再更新一下 readme。
