### ISSUE TITLE
关于itemcount和range的问题请教

### ISSUE THREAD

**Issue by lauhwong** [alibaba/vlayout#132]
//init
 final VirtualLayoutManager layoutManager = new VirtualLayoutManager(this);
recyclerView.setLayoutManager(layoutManager);
 final List<LayoutHelper> helpers = new LinkedList<>();
final GridLayoutHelper gridLayoutHelper = new GridLayoutHelper(4);
//gridLayoutHelper.setItemCount(25);
 helpers.add(gridLayoutHelper);
 layoutManager.setLayoutHelpers(helpers);
recyclerView.setAdapter(...）
//update
gridLayoutHelper.setItemCount(25);
gridLayoutHelper.setRange(0, 25- 1);
recyclerView.getAdapter().notifyDataSetChanged();
为什么setItemcount的时候不直接更新range呢。

**Comment by Zhaoyy** [comment]
``BaseLayoutHelper.java``
```java

    @Override
    public void setItemCount(int itemCount) {
        this.mItemCount = itemCount;
    }
```
看代码可以发现，这个方法只是改变了值。而``LayoutHelper.setRange()``是在``VirtualLayoutManager.setLayoutHelpers()``的时候调用的。

**Comment by longerian** [comment]
subAdapter和layoutHelper的itemCount需要一一对应，layoutHelper的itemCount和range都是内部计算出来的，用户只要关系subAdapter的信息即可，不能直接修改layoutHelper的数据信息，否则导致内部索引不一致，会出错。用户只要去修改layoutHelper的ui属性，比如margin、padding等。

**Comment by lauhwong** [comment]
recyclerView.setAdapter(new VirtualLayoutAdapter(layoutManager) {...})我用的virtualAdapter,同时也更新了count。

**Comment by lauhwong** [comment]
@longerian 完整代码如下，最后显示 的方式为VirtualLayoutManager.mDefaultLayoutHelper,而不是gridLayoutHelper 
 //init
    final RecyclerView recyclerView = (RecyclerView)findViewById(R.id.rv);
    final VirtualLayoutManager layoutManager = new VirtualLayoutManager(this);
    recyclerView.setLayoutManager(layoutManager);
    final List<LayoutHelper> helpers = new LinkedList<>();
    final GridLayoutHelper gridLayoutHelper = new GridLayoutHelper(4);
    helpers.add(gridLayoutHelper);
    layoutManager.setLayoutHelpers(helpers);
    //setAdapter
    final SubAdapter adapter = new SubAdapter(this, new GridLayoutHelper(4));
    recyclerView.setAdapter(adapter);
    //update data
    new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
        @Override
        public void run() {
            List<String> list = new ArrayList<>();
            for (int i = 0; i < 100; i++) {
                list.add("" + i * 100);
            }
            adapter.setData(list);
            adapter.notifyDataSetChanged();

        }
    }, 2000);

//adapter clz
static class SubAdapter extends DelegateAdapter.Adapter<MainViewHolder> {
    private Context mContext;
    private LayoutHelper mLayoutHelper;
    private List<String> mList = new ArrayList<>();

    public SubAdapter(Context context, LayoutHelper layoutHelper) {
        this.mContext = context;
        this.mLayoutHelper = layoutHelper;
    }

    public void setData(List<String> mList) {
        this.mList = mList;
    }

    @Override
    public LayoutHelper onCreateLayoutHelper() {
        return mLayoutHelper;
    }

    @Override
    public MainViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return new MainViewHolder(new TextView(mContext));
    }

    @Override
    public void onBindViewHolder(MainViewHolder holder, int position) {
        VirtualLayoutManager.LayoutParams layoutParams = new VirtualLayoutManager.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, 100);
        holder.itemView.setLayoutParams(layoutParams);
        ((TextView) holder.itemView).setText(mList.get(position));
    }


    @Override
    protected void onBindViewHolderWithOffset(MainViewHolder holder, int position, int offsetTotal) {
    }

    @Override
    public int getItemCount() {
        return mList.size();
    }
}

static class MainViewHolder extends RecyclerView.ViewHolder {

    public MainViewHolder(View itemView) {
        super(itemView);
    }
}

**Comment by longerian** [comment]
不知道你的defaultLayoutHelper是哪里来的，你不需要直接调用 layoutManager.setLayoutHelpers(helpers); 这个方法，你只需要给adapter加layoutHelper，adapter内部会协调layoutManager的信息，参考demo和文档https://github.com/alibaba/vlayout/blob/master/README-ch.md 来重写一下。

**Comment by lauhwong** [comment]
@longerian 去掉
```java
    final List<LayoutHelper> helpers = new LinkedList<>();
    final GridLayoutHelper gridLayoutHelper = new GridLayoutHelper(4);
    helpers.add(gridLayoutHelper);
    layoutManager.setLayoutHelpers(helpers);
```
显示效果一样,我是grid还是显示linear，defaultLayoutHelper是virtualLayoutManager的默认的linearLayout.

**Comment by longerian** [comment]
你的adapter用错了吧，参考文档和demo，简单情况下 先用DelegaterAdapter。 DelegateAdapter里包含SubAdapter
