### ISSUE TITLE
整个GridLayoutHelper布局的View怎么获取？不是Adapter里面的Item View。谢谢您的回复！

### ISSUE THREAD

**Issue by treasure-lau** [alibaba/vlayout#133]
如题！

**Comment by treasure-lau** [comment]
比如：RecyclerView里面有LinearLayoutHelper、GridLayoutHelper、ColumnLayoutHelper等布局，我想在里面的GridLayoutHelper布局上添加一层View。想知道如果获取整个View？谢谢！

**Comment by longerian** [comment]
LayoutHelper负责ItemView的布局，它自身没有一层View，所以你想要怎么在布局上添加一层View？

**Comment by treasure-lau** [comment]
谢谢
