### ISSUE TITLE
关于滚动加载更多的一些疑惑.

### ISSUE THREAD

**Issue by pinkApple** [alibaba/vlayout#134]
如题, 我注意到 vlayout 可以使用一个recyclerview完成本来需要多个recyclerview来完成的事情,只需要添加多个helper和一系列adapter,  
以前我们项目使用是
recyclerview.addOnScrollListener(){
     if(canLoadMore && lastItem == itemCount - 1)  loadMore()  来加载下一页数据
}
如果使用vlayout的话, 只有一个recylerview的情况下, 可不可以给每一个adapter添加他们自己的scroll listener?  当这个adapter的最后一个元素显示时, 并且业务需求这个adapter是分页模式,来手动配置这个adapter专属的加载更多的操作,避免其他adapter的item个数造成的position计算,从而避免这种全局的干扰.?

或者说vlayout有提供这种解决方案,只是我还没发觉正确的操作方式? 囧

**Comment by longerian** [comment]
仍然可以使用recyclerView的scrollListener来监听是否滚动到最后。参考 #110
