### ISSUE TITLE
LinearLayoutHelper 的 setPaddingBottom 有Bug

### ISSUE THREAD

**Issue by xxst** [alibaba/vlayout#135]
现在 LinearLayoutHelper 的 setPaddingBottom 和 setMarginBottom 效果是一样的，应该不一样，请检查～

vlayout 的版本：1.0.9

**Comment by longerian** [comment]
```
            LinearLayoutHelper layoutHelper1 = new LinearLayoutHelper();
            layoutHelper1.setBgColor(Color.YELLOW);
            layoutHelper1.setAspectRatio(2.0f);
            layoutHelper1.setMargin(10, 10, 10, 10);
            layoutHelper1.setPadding(10, 10, 10, 10);
```

通过如上设置，并没有出现你说的情况，需要你提供一下复现的路径

**Comment by xxst** [comment]
setPadding 和 setMargin 的方式确实没有问题。但是 单独设置 setPaddingBottom 应该是那边距，设置完之后却是外边距，同设置 setMarginBottom 没有分别了！

**Comment by longerian** [comment]
padding里概念和你理解的可能不一样，layoutHelper的padding是模拟出来的，参考https://github.com/alibaba/vlayout/blob/master/docs/ATTRIBUTES-ch.md
