### ISSUE TITLE
OnePlusNLayoutHelper新增几种布局可否提交pr

### ISSUE THREAD

**Issue by 5peak2me** [alibaba/vlayout#14]
![qq 20170308204014](https://cloud.githubusercontent.com/assets/6847158/23704360/755710c4-043f-11e7-8124-7b13f10f0007.png)
另外StickyLayoutHelper的抖动修改思路指点一下

**Comment by longerian** [comment]
可以，我拉一个 feature 分支，先往 feature 上合并。

不过值得注意的是这个 helper 本身也不是特别通用，很多时候是基于业务场景开发，所以也不用扩展太多，或者单独起一个 helper 注册进来。像1 + 5这种布局模式，第一印象其实是可以拆分成一个1+2的OnePlusNLayoutHelper 和 一个 GridLayoutHelper。

**Comment by longerian** [comment]
```StickeyLayoutHelper```抖动是因为在```afterLayout()```方法的```if (!mDoNormalHandle && mPos >= startPosition && mPos <= endPosition)```流程里，没有处理上下相邻区域的边距，我已经在 bugfix/1.0.2的分支里修复。

**Comment by 5peak2me** [comment]
@longerian 赞同。1+5拆分或者合并相对来说取决于业务逻辑本身。具体业务具体实现。

**Comment by CloudedDragon** [comment]
@longerian   請問有辦法支援 2+1 的排版嗎？
就是  1+2左右鏡射的排版

**Comment by 5peak2me** [comment]
@CloudedDragon 两个在左边，改变mesure和layout的逻辑就可以了

**Comment by longerian** [comment]
@CloudedDragon 如5peak2me 所说，可以参照着写个自定义的。

**Comment by CloudedDragon** [comment]
@5peak2me  @longerian  好喔 我再試試看 因為案子有點趕～

**Comment by 5peak2me** [comment]
核心逻辑在OnePlusNLayoutHelper里面可以找到，1+2的情况。交换一下
