### ISSUE TITLE
Vlayout 嵌套横向的RecyclerView, Item使用Glide图片加载框架就不显示图片........

### ISSUE THREAD

**Issue by omyrobin** [alibaba/vlayout#151]
使用Vlayout 其中一个Item是一个可以横向滑动的列表，所以采用了一个RecyclerView 变量名horzontalView,
horzontalView加载数据的时候发现如果使用Glide加载图片就不显示，注释掉加载图片的代码，就能正确显示Item。

但是用Glide直接使用在Vlayout对应的RecyclerView上可以正常显示图片

**Comment by omyrobin** [comment]
额 找到原因了 是数据的原因......

**Comment by longerian** [comment]
你使用vlayout的上线产品吗，能不能到 #255 里登记一下
