### ISSUE TITLE
使用ScrollView嵌套Recyclerview+v-layout是否会导致复用失效？

### ISSUE THREAD

**Issue by Smilefanlei** [alibaba/vlayout#152]
如果我再scrollview里面嵌套了ViewPager，Viewpager里面嵌套了recyclerview+v-layout是否会出现显示不全的情况？

**Comment by longerian** [comment]
是的，内部嵌套滑动暂时没有细调过

**Comment by longerian** [comment]
不是特别建议在scrollview里嵌套这么多层次，滑动手势很容易冲突。
如果一定要嵌套，先用普通的linearLayoutManager配合`recyclerView. setNestedScrollingEnabled(true)`测试一下嵌套滚动是否正常，然后切换到vlayout测试。如果滚动正常，复用就好了，如果全部展开不滚动，那就没有复用逻辑了。
