### ISSUE TITLE
adapter调用notify后会触发onBindViewHolder调用2次，但该adpter itemCount为1

### ISSUE THREAD

**Issue by nuoxiang** [alibaba/vlayout#157]
请问下是正常现象吗，是否有优化的地方

**Comment by longerian** [comment]
我需要确认一下，之前没有发现2次调用

**Comment by nuoxiang** [comment]
调用的是delegateAdapter的notify方法

**Comment by longerian** [comment]
我测了一下没有出现你说的情况，如果你实现了onBindViewHolder和onBindViewHolderWithOffset，这两个方法都是会调用一次的。

**Comment by nuoxiang** [comment]
假如有 adapter1 和 adapter2 , 调用 adaper1.notifyDataSetChanged 会触发 adaper2 onBindViewHolder 再次调用.因为 adaper1 和 adaper2 都调用了 notifyDataSetChanged ,所以每个 adapter onBindViewHolder 调用了 2 次

**Comment by longerian** [comment]
那你调用的是DelegateAdapter.Adapter 的notify方法，这样其实也会触发全部刷新，所以只要调用一次就够了，等数据变化完毕一次性刷新。

**Comment by nuoxiang** [comment]
那像 notifyItemRangeChanged 这样更新的方式有没有

**Comment by longerian** [comment]
等数据变更完毕，用DelegateAdapter的接口刷新， 都有的

**Comment by nuoxiang** [comment]
感谢解答，问题关闭了
