### ISSUE TITLE
vlayout中 无论使用哪种helper  结合调用 Glide.with(context).pauseRequests();  和Glide.with(context).resumeRequests();  加载过的图片被回收了

### ISSUE THREAD

**Issue by yzjjdcf** [alibaba/vlayout#158]
例如   前十项加载了图片  下拉到前10项不可见的时候 返回再看 图片又重新加载了

**Comment by yzjjdcf** [comment]
滑动到不可见  再滑动回来   加载过的图片应该绑定在item上啊   不用这个vlayout. glide在正常recyclerview上调用pauseRequest和resumeRequest方法即使item复用也是不重新加载？  难不成我使用方式不对？

**Comment by MoLiao2046** [comment]
控件复用和渲染效果复用，你是这个意思吗？

**Comment by longerian** [comment]
@yzjjdcf 滑动到不可见的时候，这个滑出去的item可能被复用，用来显示新滑进来的item位置。所以每次滑到屏幕内的item就是要重新绑定一下数据，否则显示就错乱了。

**Comment by longerian** [comment]
也会复用，但你要重新绑定下数据啊。

**Comment by yzjjdcf** [comment]
对呀  是复用  但是我没加Glide.with(context).pauseRequests(); 和Glide.with(context).resumeRequests();  这两句话的时候  并没有重新加载图片的现象啊 ，

**Comment by longerian** [comment]
那总得有其他代码去触发重新加载图片，不然哪里来的自动加载图片。
