### ISSUE TITLE
滑动到底部时，若底部卡片设置了底部margin，偶尔会显示不出margin

### ISSUE THREAD

**Issue by blackbluezx** [alibaba/vlayout#160]
若页面底部配置了带底部margin的卡片，手指往上滑动时，滑动速度快时，底部卡片的底部margin可显示，滑动速度较慢时，底部卡片的底部margin只会显示部分，甚至不显示，请问这个问题是什么原因呢？该怎么解决？急，麻烦了

**Comment by longerian** [comment]
底部带margin的是哪个layoutHelper，可能高度计算有问题

**Comment by blackbluezx** [comment]
仔细查了下 不是layoutHelper计算高度的问题 是引入的开源下拉刷新库 导致的 谢谢大神！
