### ISSUE TITLE
外层加一个最近git上很火的SmartRefreshLayout 上拉的时候StickyLayoutHelper的view会先上去再下来

### ISSUE THREAD

**Issue by zy4569575** [alibaba/vlayout#161]
外层加一个最近git上很火的SmartRefreshLayout 上拉的时候StickyLayoutHelper的view会先上去再下来请问是什么原因？

**Comment by zy4569575** [comment]
这块应该是跟这刷新控件走了上拉加载更多的时候

**Comment by longerian** [comment]
stickylayout 是悬浮在recyclerview的正常布局流上面，你上拉的时候整个recyclerview被拉上去，当然会跟着位移，释放之后如果recyclerview快速复位，没有触发stickylayout重新布局，那么会出现你说的情况。

**Comment by zy4569575** [comment]
您好，我大概明白了，那么如何触发stickylayout重新布局？

**Comment by longerian** [comment]
调用requestLayout方法就可以，但是如果复位过程中有动画，可能需要配合动画实时调整位置细调一下。

**Comment by zy4569575** [comment]
好的，明白了，多谢！

**Comment by mdalvik** [comment]
您好,最后的解决方案是啥呢,我这边尝试调用 requestLayout 结果没反应
