### ISSUE TITLE
混淆后setBgColor无效

### ISSUE THREAD

**Issue by wengqizun** [alibaba/vlayout#162]
添加了
-keepattributes InnerClasses
-keep class com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx { *; }
-keep class android.support.v7.widget.RecyclerView$LayoutParams { *; }
-keep class android.support.v7.widget.RecyclerView$ViewHolder { *; }
-keep class android.support.v7.widget.ChildHelper { *; }
-keep class android.support.v7.widget.ChildHelper$Bucket { *; }
-keep class android.support.v7.widget.RecyclerView$LayoutManager { *; }
然后混淆，setBgColor无效，现在我的解决方案是，额外加了一个混淆配置
-keep class com.alibaba.android.vlayout.**{*;}
然后就好了

**Comment by longerian** [comment]
方便的话看看具体哪里有问题
