### ISSUE TITLE
demo中的vlayoutActivity滑到瀑布流然后跳转再滑到瀑布流头部,第一个item上面会空出一块部分

### ISSUE THREAD

**Issue by fpl1104** [alibaba/vlayout#164]
每jump一次头部就会空出来多一点
例如:
155  156
157  158
159  160
当我jump到177的时候再返回去看就变成
       155
157  156
158  159
我在使用vlayoutActivity过程中也遇到这个问题了,特意看了下你们的demo也有这个问题

**Comment by longerian** [comment]
已知 ，还未修复

**Comment by fpl1104** [comment]
有什么中间方案绕过这个问题吗？

**Comment by fpl1104** [comment]
@longerian

**Comment by longerian** [comment]
临时方案：
跳到顶部的时候，触发一次StaggeredGridLayoutHelper的checkForGaps()方法，会重新计算布局，可能会有一次小的动画，checkForGaps()是private的，你可以反射调用一下或者改源码
我尽快系统性的解决一下这个问题

**Comment by longerian** [comment]
1.0.10解决
