### ISSUE TITLE
自定义Adapter中调用notifyItemRemove等方法列表不刷新

### ISSUE THREAD

**Issue by lazy-ape** [alibaba/vlayout#166]
继承DelegateAdapter.Adapter自定义adapter中，调用adapter的notifyitem方法时列表不刷新，必须调用notifyDataSetChanged才能刷新

**Comment by longerian** [comment]
自定义adapter的notifyItem方法，参数里的position需要是item在整个列表里的position，而不是自定义adapter里的相对位置。
