### ISSUE TITLE
当item复用时滑动事件会突然失效

### ISSUE THREAD

**Issue by eioz95** [alibaba/vlayout#170]
使用 DelegateAdapter.setAdapter(List<> adapter)添加不同的subAdapter 其中有几个的item是一致的
向上滑是正常的,但是向下拉时,如果item一致,拉动时滑动事件会突然失效,手指没有离开屏幕但是已经滑动的距离会回弹一小段,看了下log 执行onBindViewHolder方法后 滑动事件就失效了.请问这是什么情况?

**Comment by eioz95** [comment]
没有报错,oncreate也没有执行,只执行了onbind

**Comment by longerian** [comment]
vlayout对touch事件是没有拦截处理的，所以要看看日志，代码排查一下

**Comment by eioz95** [comment]
好的,我找一找.
