### ISSUE TITLE
加载刷新可以使用这个

### ISSUE THREAD

**Issue by gaoxuge521** [alibaba/vlayout#171]
https://github.com/anzaizai/EasyRefreshLayout

这个是我学习vlayout的demo

https://github.com/gaoxuge521/myDemo7

**Comment by gaoxuge521** [comment]
有#39提的数据错乱的问题，不知道怎么解决，坐等大神

**Comment by yanzhenjie** [comment]
下拉刷新任何框架都可以的，个人比较喜欢`SwipeRefreshLayout`，理想中的加载更多，加载更多应该交给conent来做，我是使用[SwipeRecyclerView](https://github.com/yanzhenjie/SwipeRecyclerView)来替代默认的`RecyclerView的`，基本功能也比较齐全。

**Comment by longerian** [comment]
数据的错乱问题在demo中是解决了，不知道其他场景是怎么复现的，还没细看
