### ISSUE TITLE
gridlayouthelper 设置spansize问题

### ISSUE THREAD

**Issue by diorslau** [alibaba/vlayout#176]
在使用gridlayout的时候 我设置了spansize,   首次进入后往下滑动的后 我的gridlayout是错乱的,并没有达到我想要的跨列效果,  但是网上滑动后又继续下滑的话 布局又是正确的. 

正确的布局应该是 :        

      1              
2    3   4      

其中1是占3列  , 下面 234各占1列

错乱的布局 :                    
     1                                   
2    这里是空白
3    4

**Comment by longerian** [comment]
那就得看你的spansize是怎么写的。getSize回调的position是整个页面的position，而不是layoutHelper内部的position

**Comment by xiaotian1** [comment]
为什么返回的时整个页面的position呢？
有可能gridlayouthelper 上面的内容数量不固定我该怎么办。

**Comment by longerian** [comment]
在一次操作里应该是固定的，不可能来回滑动还不确定。获取相对位置，只要position - layoutHelper.getRange().getLower() 就拿到了。
