### ISSUE TITLE
当Adapter内存在某个定时器类的控件时，刷新或者滑动过程中，总是会跳

### ISSUE THREAD

**Issue by VaneSue** [alibaba/vlayout#178]
如题

**Comment by lixi0912** [comment]
duplicate of #46

**Comment by VaneSue** [comment]
问题基本自行解决，不是vlayout的问题
如果你也遇到这样的问题，可能是
第一，检查一下你的动画，View的visibility 属性等
第二，焦点问题，将焦点放在RecyclerView 的父布局上

**Comment by lixi0912** [comment]
你这边会跳是指高度会抖动？

**Comment by VaneSue** [comment]
尝试一下不要将焦点放在RecyclerView 上？  
在 RecyclerView 的父控件上添加：android:descendantFocusability="blocksDescendants"

**Comment by lixi0912** [comment]
@VaneSue  刚试了下，并没有效果
