### ISSUE TITLE
应该如何结合其他Adapter使用

### ISSUE THREAD

**Issue by a512509050** [alibaba/vlayout#179]
例如BaseRecyclerViewAdapterHelper

**Comment by lixi0912** [comment]
你是说不继承于 DelegateAdapter.Adapter ?

如果是的话，可以参考下
[WrapperAdapter.java](https://github.com/lixi0912/vlayout/blob/master/vlayout/src/main/java/com/alibaba/android/vlayout/WrapperAdapter.java)

**Comment by a512509050** [comment]
@lixi0912 好的，我来试一下

**Comment by a512509050** [comment]
@lixi0912 您好，我测试了一下WrapperAdapter，布局显示正常，但是刷新数据不知道该调用什么方法

**Comment by lixi0912** [comment]
@a512509050  调用实际的 Adapter 的
```java
    @see #notifyItemChanged(int)
    @see #notifyItemInserted(int)
    @see #notifyItemRemoved(int)
    @see #notifyItemRangeChanged(int, int)
    @see #notifyItemRangeInserted(int, int)
    @see #notifyItemRangeRemoved(int, int)
```
比如 

```java
    DelegateAdapter delegateAdapter = new DelegateAdapter(layoutManager);
    List<DelegateAdapter.Adapter> adapters = new ArrayList<>();
    IngredientsAdapter ingredientAdapter = new IngredientsAdapter(data.getIngredients());
    adapters.add(new WrapperAdapter<>(ingredientAdapter, ingredientsHelper));
    delegateAdapter.addAdapters(adapters);
    // some code 
    ingredientAdapter.notifyItemRangeInsert(insertIndex, insertCount);
```

**Comment by longerian** [comment]
@a512509050 @lixi0912 我们在Tangram里使用的Adapter就是自定义的，没有使用DelegateAdapter，可以参考借鉴：

https://github.com/alibaba/Tangram-Android/blob/master/tangram/src/main/java/com/tmall/wireless/tangram/dataparser/concrete/PojoGroupBasicAdapter.java
