### ISSUE TITLE
嵌套webview的问题

### ISSUE THREAD

**Issue by DanielYP** [alibaba/vlayout#180]
我用vlayout做了一个比较复杂长的列表，其中有一个delegateAdapter.Adapter的布局是一个webview，webview的高度设置为match_parent。原因是，如果设置为wrap_content。列表由下往上滑动的时候，滑动到WebView，就会出现一个bug，比如一滑动到webview，就回到了底部(webview加载的是长文），设置为match_parent就没有问题。

但文章过段时，设置mathc_parent就有空白，如果解决空白呢

**Comment by longerian** [comment]
最好是根据内容高度来设置精确的值，如果是wrapcontent，按你说的bug，可能需要每次onBind的时候让webview滚动到顶部。
