### ISSUE TITLE
使用vlayout来回切换二个tab,发生位移问题

### ISSUE THREAD

**Issue by douya40** [alibaba/vlayout#183]
使用vlayout来回切换二个tab,发生位移问题

**Comment by douya40** [comment]
为什么会发生位移问题呢

**Comment by shijia109** [comment]
焦点抢占吧，比如有viewpager之类的

**Comment by douya40** [comment]
我是分三块第一块是viewpager的滑动图片，第二块是九宫格，第三块是列表。这样来回切换二个tab,发生位移问题

**Comment by longerian** [comment]
不是特别能想象，做个gif说明一下。

**Comment by blesslp** [comment]
recyclerview切换显示的时候,如果有item抢了焦点,确实会位移,这个不是recyclerView的原因吧

**Comment by jhy1990** [comment]
recyclerView 加个android:overScrollMode="never"，父控件加个android:descendantFocusability="blocksDescendants"，我的就是这么解决的

**Comment by longerian** [comment]
抖动一般是padding 、margin计算不对引起的，我修复了一个这样的问题，1.2.7。保持关注吧。
