### ISSUE TITLE
自定义轮播组件问题

### ISSUE THREAD

**Issue by shijia109** [alibaba/vlayout#185]
第一个item为开源框架AndroidImageSlider用来轮播，我自定义一个adapter继承自DelegateAdapter，在onCreateViewHolder里初始化了组件和数据（不知道有没有不妥，但是在onBindViewHolder里初始化会在每次滑动到它位置时都初始化一次），但是即使这么做有时滑动到列表底部再滑动到顶部时，轮播会变成空白，轮播滚动后又正常显示内容，不知道是什么原因是被回收了吗还是别的原因，大神能不能解答下？

**Comment by shijia109** [comment]
解决了，我把每个adapter的类型都设置了独立的viewtype，确保这个值不重样，然后每个viewtype都在viewpool设置了setMaxRecycledViews，就没问题了，原来有一个adapter没设置viewtype，加上一个不同的viewtype值就好了

**Comment by shijia109** [comment]
白高兴一场，没有彻底解决，只不过是白城空白概率变小了，偶尔还是会出现

**Comment by longerian** [comment]
滑出屏幕外是会回收的，当重新滑动到屏幕内，需要在onBindViewHolder里重新绑定下数据。

**Comment by shijia109** [comment]
可是理论来讲轮播图不可以被回收，可以重新绑定数据，但是这样每次再滑动到顶部轮播就复位了，而且还会有点卡顿，有没有什么好办法处理呢？另外一个页面里有一个其中一个item有一个定时器做的倒计时效果，也是onCreateViewHolder里初始化的定时器和数据，貌似没有问题，好像没有被回收重建的迹象，不知道是不是跟引用有关。而轮播已经换了一个了，第一个是自定义的viewpager，也是滑上去有时候就变成空白，不知道有没有办法解决这个问题，让某个item不被回收

**Comment by longerian** [comment]
滑出屏幕回收后，重新滑入屏幕会被复用，这个时候绑定是原始的数据，如果你只有一个这样类型的组件，应该是不需要重新创建的。
如果重新绑定了数据，那就会丢失状态，需要自己维护状态了。

**Comment by Ung8023** [comment]
遇到了同样的问题，第一项为轮播图，当滑动到下面，再滑动回去时，会显示为轮播的第一个页面

**Comment by longerian** [comment]
@Ung8023 这个状态要自行维护，vlayout感知不到。

**Comment by douya40** [comment]
vlayout考虑要全面呀
