### ISSUE TITLE
加载更多Item只能使用addAdapter吗？

### ISSUE THREAD

**Issue by huclengyue** [alibaba/vlayout#189]
在一个RecyclerView中 有多个不同的adapter A B C D，它们使用同一个LinearLayoutHelper 只是UI不同，

在调用加载更多后，我通过修改的D的数据 在调用D 的 notifyDataSetChanged  修改数据 这时候就会报错。
```
ClassCastException。
CardDetailsReplyAdapter$ReplyHolder cannot be cast to CardDetailsAuthorAdapter$AuthorHolder
```
D的ViewHolder 不能转为 C 的ViewHolder 。

如果删除C 这个类型 就提示不能转为 B 的ViewHolder

**Comment by longerian** [comment]
那是复用的问题，看看FAQ里说明能不能解决：https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md

**Comment by huclengyue** [comment]
非常感谢，确实是复用导师的问题。
