### ISSUE TITLE
StickyLayoutHelper 设置以后没有效果

### ISSUE THREAD

**Issue by 18311023368** [alibaba/vlayout#190]
我的adapter是这样的，3个SingleLayoutHelper  1个StickyLayoutHelper  最后一个是LinearLayoutHelper，但是现在设置了StickyLayoutHelper没有效果

**Comment by 18311023368** [comment]
什么情况下回出现没有吸顶的效果呢

**Comment by longerian** [comment]
sticky 是它负责的组件滑出屏幕范围的时候才有吸顶效果。如果默认就要吸顶，用fixLayoutHelper

**Comment by 18311023368** [comment]
我现在也是啊  ，按照demo写的啊  也是费解了

**Comment by longerian** [comment]
这不应该，你对着demo检查检查

**Comment by 18311023368** [comment]
解决了 多谢

**Comment by longerian** [comment]
有看出什么原因吗
