### ISSUE TITLE
DelegateAdapter初次加载第一个adapter正常，第二个不正常

### ISSUE THREAD

**Issue by SSSSunrise** [alibaba/vlayout#194]
![qhox6bgbbm yejnk449e m](https://user-images.githubusercontent.com/31717774/30144293-e05bcfd8-93bc-11e7-9326-858da7039e2c.png)

`layoutManager = new VirtualLayoutManager(getActivity());
        final RecyclerView.RecycledViewPool viewPool = new RecyclerView.RecycledViewPool();
        layoutManager.setRecycleOffset(300);
        fragment_home_recyclerView.setLayoutManager(layoutManager);
        fragment_home_recyclerView.setRecycledViewPool(viewPool);
        viewPool.setMaxRecycledViews(0, 20);//设置回收复用池大小
        viewPool.setMaxRecycledViews(1, 20);//设置回收复用池大小
        fragment_home_recyclerView.addItemDecoration(new RecyclerView.ItemDecoration() {
            public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
                outRect.set(10, 10, 10, 10);
            }
        });
        delegateAdapter = new DelegateAdapter(layoutManager);
        adapters = new LinkedList<>();

        LinearLayoutHelper layoutHelper = new LinearLayoutHelper();
        layoutHelper.setBgColor(getResources().getColor(R.color.FFFFFF));

        GridLayoutHelper gridLayoutHelper = new GridLayoutHelper(2);
        gridLayoutHelper.setWeights(new float[]{50, 50});
        gridLayoutHelper.setHGap(10);

        homeDataEntity = new HomeDataEntity();
        mAdapter = new CommunityAdapter(getActivity(), layoutHelper);
        mNewCommunityAdapter = new NewCommunityAdapter(getActivity(), gridLayoutHelper);
        adapters.add(mAdapter);
        adapters.add(mNewCommunityAdapter);

        delegateAdapter.addAdapters(adapters);
        fragment_home_recyclerView.setAdapter(delegateAdapter);`
我的第一个LinearLayoutHelper在进行了下拉刷新后变成了第二个 GridLayoutHelper的属性，第二个GridLayoutHelper依然是一行只有一个
![dme435t3s 1elx8t5 q8 y6](https://user-images.githubusercontent.com/31717774/30144255-a9e60112-93bc-11e7-80b9-9682c014f808.png)

**Comment by SSSSunrise** [comment]
![gif](https://user-images.githubusercontent.com/31717774/30145091-a1e4e96a-93c1-11e7-98e0-df160ec259aa.gif)
我给你传个gif，我想让下面的几个字符串像Gridview一样，分两列排列，但是始终达不到要求，下拉刷新了一次数据，第一个adapter的布局变成了两列。

**Comment by lixi0912** [comment]
https://github.com/alibaba/vlayout/issues/191

可能是同一个问题~ 你可以试一下

**Comment by longerian** [comment]
用 1.2.1
