### ISSUE TITLE
很多个适配器出现问题

### ISSUE THREAD

**Issue by ConanHolmes** [alibaba/vlayout#197]
当我循环加了很多个（十多个吧）适配器再setAdapters,在我滑动过程中会自动回到顶部好几次什么原因？

**Comment by ConanHolmes** [comment]
`SingleLayoutHelper singleLayoutHelper1 = new SingleLayoutHelper();
        VirtualLayoutManager.LayoutParams layoutParams = new VirtualLayoutManager.LayoutParams(VirtualLayoutManager.LayoutParams.MATCH_PARENT, ScreenUtil.dip2px(72));
        singleLayoutHelper1.setMarginTop(ScreenUtil.dip2px(8));
        singleLayoutHelper1.setMarginLeft(ScreenUtil.dip2px(16));
        singleLayoutHelper1.setMarginRight(ScreenUtil.dip2px(16));
        CategoryBannerAdapter bannerAdapter=new CategoryBannerAdapter(getContext(), R.mipmap.ic_logo_empty5, bannerItems,layoutParams,singleLayoutHelper1);
        adapters.add(bannerAdapter);

        for (int i = 0; i < navigations.size(); i++) {
            final KindBean.DataEntity.NavigationsEntity kn = navigations.get(i);
            SingleLayoutHelper singleLayoutHelper = new SingleLayoutHelper();
            singleLayoutHelper.setMargin(0,ScreenUtil.dip2px(10),0,ScreenUtil.dip2px(10));
            CatagoryNameAdapter catagoryNameAdapter=new CatagoryNameAdapter(getActivity(),kn.getName(),singleLayoutHelper);
            adapters.add(catagoryNameAdapter);

            grid = new GridLayoutHelper(3);
            grid.setGap(ScreenUtil.dip2px(16));
            grid.setAutoExpand(false);
            CategoryGridAdapter categoryGridAdapter=new CategoryGridAdapter(getContext(),kn.getItems(),grid);
            adapters.add(categoryGridAdapter);
        }
        delegateAdapter.setAdapters(adapters);
        delegateAdapter.notifyDataSetChanged();`

**Comment by longerian** [comment]
😂😂😂

**Comment by inshun** [comment]
你应该是在 adapter 中又用了 recycler view 了吧?

**Comment by ConanHolmes** [comment]
没有用recyclerview 啊...就用了两个adapter，一个是singleLayoutHelper是一个banner，一个就是gridLayouthelper，但是在滑动过程中还是会返回顶部....不知道怎么回事诶..
