### ISSUE TITLE
PullToRefreshRecyclerView + VLayout 无法上拉加载更多

### ISSUE THREAD

**Issue by 18826243441m** [alibaba/vlayout#198]
求大神解答
本人项目中使用PullToRefreshRecyclerView来实现上拉加载更多和下拉刷新,可是下拉刷新可以,上拉加载更多却不行.

**Comment by longerian** [comment]
你要先定位一下，为什么不行。比如PullToRefreshRecyclerView上拉刷新的原理是什么，和vlayout结合导致哪里有冲突，然后该怎么解决。

**Comment by 295522894** [comment]
解决了吗

**Comment by 18826243441m** [comment]
解决了,重写了上拉和下拉的判断标准

**Comment by 295522894** [comment]
方便把解决后的代码贴出来借鉴下吗   我也遇到了同样的问题

**Comment by 18826243441m** [comment]
/**
     * @return boolean:
     * @Description: 判断第一个条目是否完全可见
     * @version 1.0
     * @date 2015-9-23
     * @Author zhou.wenkai
     */
    private boolean isFirstItemVisible() {
        final RecyclerView.Adapter<?> adapter = getRefreshableView().getAdapter();

        // 如果未设置Adapter或者Adapter没有数据可以下拉刷新
        if (null == adapter || adapter.getItemCount() == 0) {
            LogUtil.d(LOG_TAG, "isFirstItemVisible. Empty View.");
            return true;
        } else {
            //如果是Valyout的框架,判断标准如下
            if (getRefreshableView().getLayoutManager() instanceof VirtualLayoutManager) {
                VirtualLayoutManager layoutManager = (VirtualLayoutManager) getRefreshableView().getLayoutManager();
                //获取第一个可见view的位置
                if (layoutManager.findFirstCompletelyVisibleItemPosition() == 0) {
                    return true;
                }
            } else {//如果是普通的,则判断标准如下
                // 第一个条目完全展示,可以刷新
                if (getFirstVisiblePosition() == 0) {
                    return getRefreshableView().getChildAt(0).getTop() >= getRefreshableView()
                            .getTop();
                }
            }
        }

        return false;
    }

**Comment by 18826243441m** [comment]
/**
     * @return boolean:
     * @Description: 判断最后一个条目是否完全可见
     * @version 1.0
     * @date 2015-9-23
     * @Author zhou.wenkai
     */
    private boolean isLastItemVisible() {
        final RecyclerView.Adapter<?> adapter = getRefreshableView().getAdapter();

        // 如果未设置Adapter或者Adapter没有数据可以上拉刷新
        if (null == adapter || adapter.getItemCount() == 0) {
            LogUtil.d(LOG_TAG, "isLastItemVisible. Empty View.");
            return true;

        } else {
            //如果是Valyout的框架,判断标准如下
            if (getRefreshableView().getLayoutManager() instanceof VirtualLayoutManager) {
                VirtualLayoutManager layoutManager = (VirtualLayoutManager) getRefreshableView().getLayoutManager();
                //获取第最后一个可见view的位置
                if (layoutManager.findLastCompletelyVisibleItemPosition() + 1 == adapter.getItemCount()) {
                    return true;
                }
            } else {
                //如果是普通的,判断标准如下
                // 最后一个条目View完全展示,可以刷新
                int lastVisiblePosition = getLastVisiblePosition();
                if (lastVisiblePosition >= getRefreshableView().getAdapter().getItemCount() - 1) {
                    return getRefreshableView().getChildAt(
                            getRefreshableView().getChildCount() - 1).getBottom() <= getRefreshableView()
                            .getBottom();
                }
            }
        }

        return false;
    }

**Comment by 18826243441m** [comment]
其实就是因为vlayout的adapter比平时的recycleview的adapter多包裹了一层,所以平时的判断标准不准确

**Comment by 295522894** [comment]
老哥 稳
