### ISSUE TITLE
demo滑动bug

### ISSUE THREAD

**Issue by yaozs** [alibaba/vlayout#20]
当界面在10,11,12,13位置时，手指按下来回反复上下滑动界面，会出现11,12,13,14,15消失，和颜色移位

**Comment by Basakerone** [comment]
是的，我也测试了一下，在30的位置反复上下滑动会造成30这个条目颜色改变。。第一个条目viewpager用StickyLayoutHelper去固定左右滑动会造成条目消失。。。

**Comment by longerian** [comment]
ok 研究一下

**Comment by longerian** [comment]
```StickyLayoutHelper ```里只支持一个元素，demo 里使用有点问题，代码已经推到 bugfix 分支去了，再试试。
