### ISSUE TITLE
菜鸟求解

### ISSUE THREAD

**Issue by CoKoOne** [alibaba/vlayout#200]
我的APP首页类似淘宝一样很复杂，有很多的功能模块，对应的就有很多接口；我使用Okhttputils框架发起请求，Okhttputils框架，每发起一个请求就开启一个子线程；由于接口众多我就发了很多的请求，但是由于在不同的子线程中请求的接口，所以每个接口数据回来的速度都不一样，当数据回来时，主线程已经执行完：DelegateAdapter delegateAdapter = new DelegateAdapter(layoutManager, false);
recycler.setAdapter(delegateAdapter);导致没有数据；我当前的解决方案是每个接口回来数据我就调用对应的Adapter刷新，是这样解决吗？感觉好像这种做法很low! 

复用池问题：如果布局有很多的不同item，是不是要在每个不同Item对应的Adapter里重写getItemViewType，然后每个不同Item都：

RecyclerView.RecycledViewPool viewPool = new RecyclerView.RecycledViewPool();
recyclerView.setRecycledViewPool(viewPool);
viewPool.setMaxRecycledViews(ItemViewType, 复用池大小);

求高人解惑———————初学菜鸟。

**Comment by longerian** [comment]
问题1：将接口合并成一个，一次性返回。有需要的话分页处理，第一页返回首屏的数据，后面再一页一页地返回。
问题2：参考 #196 的说明。

**Comment by CoKoOne** [comment]
一次性返回数据量是否太大？淘宝首页的数据也是一个接口，一次性返回吗？期待大神下一次更新时，在Demo中加入复用池多类型，结合BaseRecyclerViewAdapterHelper使用、removeAdapter()示例！我都是一个Adapter对应一个Viewholder的， delegateAdapter.removeAdapter(0);  就崩溃了：ClassCastException：ViewHolder cannot be cast to.......... ？

**Comment by longerian** [comment]
数据量大也比你发多个请求的开销来的小。过于庞大就分页处理。
