### ISSUE TITLE
滑动后展开的ExpandTextView又合起来了

### ISSUE THREAD

**Issue by gdmec07120731** [alibaba/vlayout#201]
请问，比如我布局里面有一个ExpandTextView，点击展开，滑动直到它消失在屏幕，又滑动回来，ExpandTextView就合上了。

**Comment by DanielYP** [comment]
这个需要你自己保存合起或展开状态。不是vlayout的bug。记住每一个item的状态，滑动回来的时候恢复该状态

**Comment by longerian** [comment]
正如 @DanielYP 所解释的那样
