### ISSUE TITLE
关于StaggeredGridLayoutHelper,当数据源数量为1时的问题。

### ISSUE THREAD

**Issue by DanielYP** [alibaba/vlayout#202]
在我使用瀑布流的时候，当数量为1，在下拉刷新时，会发生该唯一view一会在瀑布流左边，一会在瀑布流右面，规律性强。左右左右左右。
我的写法是。
1. layouthelper
        StaggeredGridLayoutHelper layoutHelper = new StaggeredGridLayoutHelper();
        layoutHelper.setLane(2);
        layoutHelper.setHGap(40);
        layoutHelper.setVGap(40);
        layoutHelper.setPaddingTop(40);
2. init
        mVLayoutManager = new VirtualLayoutManager(getActivity());
        mRvList.setLayoutManager(mVLayoutManager);

        RecyclerView.RecycledViewPool viewPool = new RecyclerView.RecycledViewPool();
        mRvList.setRecycledViewPool(viewPool);
        viewPool.setMaxRecycledViews(0, 10);

        mDelegateAdapter = new DelegateAdapter(mVLayoutManager);
        mDelegateAdapter.addAdapter((DelegateAdapter.Adapter) presenter.getAdapter());
        mRvList.setAdapter(mDelegateAdapter);
3. 获取瀑布流的adapter
    @Override
    public RecyclerView.Adapter getAdapter() {
        if (mAdapter == null) {
            mAdapter = new CommonStaggeredAdapter(mView.getViewContext(), this, mView.getStaggeredLayoutHelper());
        }
        return mAdapter;
    }
4. 我瀑布流的adapter里面为
    @Override
    public int getItemCount() {
        return CollectionUtils.size(articleData);
    }
5. 当数据加载完毕，我是这么更新adapter的
        mModel.setArticleData(data);
        mAdapter.setArticleData(mModel.getArticleData()); （传递给瀑布流的数据源，mAdapter就算是瀑布流的adapter)
        mAdapter.notifyDataSetChanged();
6. 具体效果可以查看线上app。如果需要私信给你

**Comment by longerian** [comment]
大概原因是这样子的，有两个泳道，第一次刷新占用第一道，

刷新后layoutHelper以为第一道被占据了，排布到第二道，回收了第一道。

再次刷新，情况刚好相反。

如果是全量替换，重新给一个adapter，会重新生成layoutHelper，否则的话，将老的layoutHelper的调用一下onClear方法试试。

**Comment by DanielYP** [comment]
恩，我现在用了替代方案，只要大于1就没有问题，我默认都加了1，并在bind中隐藏掉。你这么解释我大概可以理解了。
