### ISSUE TITLE
滑动卡顿问题

### ISSUE THREAD

**Issue by xinxin1314** [alibaba/vlayout#205]
这个多个布局的时候, 第一次滑动的时候卡顿, 就第一次滑动的时候卡顿, 第二次以上就不会卡顿

**Comment by longerian** [comment]
检查一下有没有错误日志，是不是组件性能本身差，先自己排查一下。

**Comment by yxlku** [comment]
滑动一直卡顿，如果不使用vlayout，在recycleview中直接显示的话不会卡顿呢，是按照demo来写的呀

**Comment by longerian** [comment]
各位检查下日志，看看复用是不是有问题。

**Comment by yangitlife** [comment]
如果添加了多个adapter的话  尝试每个adapter的 getItemViewType 返回不同的值;
