### ISSUE TITLE
数据动态加载顺序会导致数据显示在屏幕之外~

### ISSUE THREAD

**Issue by lixi0912** [alibaba/vlayout#206]
伪代码如下

```java

DelegateAdapter adapter  = new DelegateAdapter();
List<DelegateAdapter.Adapter> adapters = new ArrayList<>();
adapters.add(firstAdapter);
adapters.add(secAdapter);
adapter.setAdapter(adapters);
recyclerView.setAdapter(adapter);

handler.postDelay(new Runnable(){
    public void run(){
        firstAdapter.add(firstList);
        firstAdapter.notifyItemRangeInsert(0, firstList.size());
    }
}, TimeUnit.SECONDS.toMillis(3));


handler.postDelay(new Runnable(){
    public void run(){
        secAdapter.add(secList);
        secAdapter.notifyItemRangeInsert(0, secList.size());
    }
}, TimeUnit.SECONDS.toMillis(1));

```

上述初始的 Adapter 默认的 ItemCount 都是 0，此时当 SecAdapter 加载完并刷新界面，然后 FirstAdapter 也加载完并调用刷新界面，预期效果应是，界面首项为 FirstAdapter 的第一项内容，但是实际上是 SecAdapter 的首项，界面中并没有含有抢焦点的控件~ 图片加载的高度也是写死的，加载完
 item 高度不会发生改变~

**Comment by longerian** [comment]
1. vlayout 用的是哪个版本
2. layoutHelper怎么写的

**Comment by lixi0912** [comment]
1. vlayout 版本为 1.2.2
2. layoutHelper 为 LinearLayoutHelper ，FirstAdapter 对应的 LayoutHelper 设置了一个 MarginBottom ，两个 LayoutHelper  都设置了 BgColor~

**Comment by longerian** [comment]
了解了，它没有自动滚动下去。

**Comment by longerian** [comment]
@lixi0912   这个问题还存在吗

**Comment by lixi0912** [comment]
@longerian  刚整理了下代码，提交了一个分支，你可以检出看看  -> [地址](https://github.com/lixi0912/vlayout/tree/bugfix/reported_issue_206)

**Comment by longerian** [comment]
好，我尽快研究下

**Comment by longerian** [comment]
我测试了下，对于recyclerView来说，就是这么设计的，需要我们自行滚动，你换成linearlayoutmanager也是一样的效果。
