### ISSUE TITLE
请问如何通过 vlayout　来实现横向滚动呢？？

### ISSUE THREAD

**Issue by HaiChecker** [alibaba/vlayout#212]

**Comment by HaiChecker** [comment]
已经找到实现方式了，代码如下：
LinearLayoutHelper g = new LinearLayoutHelper(20);   //20代表Ｈ的间隔
VirtualLayoutManager.setOrientation(VirtualLayoutManager.HORIZONTAL);

**Comment by longerian** [comment]
横向滚动是可以的，不过有些布局可能还没处理好横向的逻辑，需要参考数值方向的布局逻辑移植处理一下。
