### ISSUE TITLE
怎么remove掉某一个adapter？

### ISSUE THREAD

**Issue by ania93** [alibaba/vlayout#217]
想remove掉某一个adapter的时候有默认的动画，用delegateAdapter的notifyItemRemoved方法，发现remove掉的是recyclerview中所有的view中索引的那个view，而并不是移除某一整块view？

**Comment by longerian** [comment]
恩   传入正确的position就可以了。  需要获取到view在整体页面中的position，参考 https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md#获取-delegateadapter-里数据的相对位置
