### ISSUE TITLE
关于网络请求后加载模块界面的问题

### ISSUE THREAD

**Issue by NeVaDaAAA** [alibaba/vlayout#218]
您好 目前我有个问题想请教
我的一个模块是要走网络请求，获取list.size,来放在Adapter中，当我把创建模块Adapter的工作放在网络请求成功的时候，该模块不显示，请问怎么解决呢？

 BaseDelegateAdapter recommendAdapter = new BaseDelegateAdapter(getActivity(), new LinearLayoutHelper(),
                    R.layout.vlayout_recommend, list.size, RECOMMEND_VIEW_TYPE) {
                @Override
                public void onBindViewHolder(BaseViewHolder helper, int position) {
                    super.onBindViewHolder(helper, position);
                    if (position != recommend_list.size() - 1) {
            line.setVisibility(View.VISIBLE);
        } else {
            line.setVisibility(View.GONE);
        }

        ImageView imageView = helper.getView(R.id.tb_recommend_iv);
        .......
                }
            };
            mAdapters.add(recommendAdapter);

**Comment by longerian** [comment]
debug一下 mAdapters.add(recommendAdapter); 之后的逻辑，比如recommendAdapter 有没有添加到列表里，对应的layoutHelper有没有生成，有没有传递到VirtualLayoutManager里。

**Comment by NeVaDaAAA** [comment]
已解决 谢谢

**Comment by longerian** [comment]
你使用vlayout的上线产品吗，能不能到 #255 里登记一下
