### ISSUE TITLE
 关于viewtype

### ISSUE THREAD

**Issue by chshp1234** [alibaba/vlayout#221]
情况是这样的，也是一个商城首页页面，共9个adapter，且我都写成了不同的，其中有几个用的是同一个itemview，然后这些全都用同一个viewholder（里面只有个getView（rid）方法），现在我打log出来9个adapter返回的viewtype是这样的9，0，2，5，5，5，5，9，9，14，所以这个tpye是怎么给定的，如果我hasConsistItemType 设为true会出现问题吗

**Comment by lixi0912** [comment]
你可以看下这个
https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md
http://pingguohe.net/2017/05/03/the-beauty-of-math-in-vlayout.html
