### ISSUE TITLE
LinearLayoutHelper.dividerHeight 导致界面滑动

### ISSUE THREAD

**Issue by lixi0912** [alibaba/vlayout#223]
v-layout: 1.2.2
phone: 红米 note 3
android: 6.0

layout 大致如下

```xml
<LoadMoreFrame>
    <RecyclerView/>
    <LoadView/>
</LoadMoreFrame>
```
LoadMoreFrame 的大致原理通过，改变 layout 的 top 和 bottom 的值，来使 RecyclerView 上移和移动还原。

而当有 dividerHeight 的时候，则会出现 item 滑动

![2017-10-19 16_50_43](https://user-images.githubusercontent.com/7205121/31762437-cf9914b4-b480-11e7-9a4a-5b8636444707.gif)

清晰地址-> https://pan.baidu.com/s/1jInCMto

**Comment by longerian** [comment]
@lixi0912  1.2.8 你试一下，  还有问题再给我反馈

**Comment by lixi0912** [comment]
@longerian  使用项目测试问题依旧

LoadMoreFrame 是通过调用 RecyclerView.layout( top 值由 0 到 -FooterView.height ) 使整个 RecyclerView 上移，显示出 FooterView

**Comment by longerian** [comment]
ok，针对linearLayoutHelper可能还有其他问题没修复到。方便的话测试项目贴个代码或github地址给我，我再调一调，本周应该可以修复这个。

**Comment by lixi0912** [comment]
@longerian  刚整理了下代码，提交了一个分支，你可以检出看看~  -> -> [地址](https://github.com/lixi0912/vlayout/tree/bugfix/reported_issue_223)

**Comment by longerian** [comment]
修复了 下周发布下

**Comment by sacowiw** [comment]
@longerian 这个问题依然存在。
LinearLayoutHelper设置dividerHeight后，执行notifyDataSetChanged()时，整个列表还是有轻微的位移

**Comment by longerian** [comment]
@sacowiw 你可以拉个分支  复现一下场景 我拉下来看看
