### ISSUE TITLE
加载 RecyclerView 莫名自动滚动，注册监听发现 newState == 2，不是手动滑动

### ISSUE THREAD

**Issue by yuri8080** [alibaba/vlayout#225]
我加载一个页面（acticity）的时候，整体都用  RecyclerView 来实现， 然后进入这个acticity 的时候，会自动发生 滚动事件 ！！

我绝对没有 进行任何滚动操作 （诸如，smoothScrollToPosition，scrollToPosition，scrollTo 都没有，甚至连  scroll 关键字都没有） ，但是 RecyclerView  ，依然会发生自动滚动 ！！ 请大神  看看，是不是 bug ，如果，不是 希望给予指导  ！！！ 拜谢 拜谢！！

**Comment by yuri8080** [comment]
补充一下， 我用的是 VirtualLayoutManager layoutManager = new 
                                                                               VirtualLayoutManager(getApplication());

 final List<DelegateAdapter.Adapter> listItems = new LinkedList<>();
        listItems.add.......

**Comment by yuri8080** [comment]
继续 自己补充 ！  解决方法

android:descendantFocusability="blocksDescendants"   父布局里，加这句



android:overScrollMode="never"   recycleView里加这局


PS  这是我往后面翻问题，看的的一个大神的回答 ！ 多谢那位，大神

**Comment by longerian** [comment]
ok 这个应该是某个view获取焦点，触发重新布局引起的偏移。

**Comment by iielse** [comment]
可以，我倒是遇到了 recyclerView嵌套 recyclerView导致的自动滑动

**Comment by SubinVane** [comment]
http://www.jianshu.com/p/cb4fc4f01cf9  使用VLayout，你可能遇到的问题

**Comment by longerian** [comment]
@yuri8080 我最近修复了一个 bug，重新进入页面，如果触发重布局（如果有padding margin之类的设置）会引起滚动、偏移。 你可以试试新版本。

**Comment by yuri8080** [comment]
好的，多谢大神通知 @longerian

**Comment by MagicKim** [comment]
> @ yuri8080我最近修复了一个bug，重新进入页面，如果触发重布局（如果有padding margin之类的设置）会引起滚动，替换。你可以试试新版本。

大佬可否告知,recyclerView如果触发重布局（如果有padding margin之类的设置）会引起滚动.这个源码在layoutmanager里面还是recyclerView里面?我想分析一下,目前我也遇到了这个问题.看到您说的才解决了.
