### ISSUE TITLE
addAdapter(int position,  Adapter adapter) 无效

### ISSUE THREAD

**Issue by xinxin1314** [alibaba/vlayout#231]
调用方法 addAdapter(int position,  Adapter adapter) 并不会添加到指定的位置, 而是添加在最后面, 调用了notifyDataSetChanged()方法也不起作用, 应该是一个 bug

**Comment by longerian** [comment]
需要确认下你用的是哪个版本，我这边review代码加实际测试，是可以的，除非你的position > 当前sub adapter的个数，
