### ISSUE TITLE
征集vlayout工作小组

### ISSUE THREAD

**Issue by longerian** [alibaba/vlayout#234]
### 工作小组招募
vlayout 开源半年以来，受到了大家的广泛关注。通过Issue了解到，在Android应用开发中，大家普遍需要一种扁平化的、可回收复用的页面异构布局的技术方案，也有不少产品开始尝试使用这个框架解决业务问题。感谢各位的支持和认可，正是大家的期热情与期待，让我们有更强的动力把它做得更好。同时，我们也要看到了不足之处。比如：API 不是很完善，大家在使用的时候碰到了一些问题；RecyclerView 框架体系本身也比较复杂，很多同学遇到的问题不知道如何定位，排查也需要花费大量时间；缺乏对横滑的支持等。

开源项目是为了能把已有的成果贡献给社区，同时我们也认为自己的力量是有限的，期望能够通过大家的力量一起来完善和发展。为了更好的吸收优秀的方案，加速优化推进，我们希望招募一些技术经验丰富且有志于贡献力量的同学组成工作小组，一起推动 vlayout 的发展。

#### 招募数量
3-5人；

#### 小组职责
- 设计更加好用的 API；
- 开发丰富的 DEMO 供社区学习和指导使用；
- 增加更多有价值的新特性；
- 及时跟进和解决Issue，并搭建一个小的讨论组或社区提供更加方便的答疑服务

#### 招募对象
- 对开源与技术有热情，愿意为开源做贡献；
- 有UI框架设计经验者优先；
- 最好对 RecyclerView 体系 或 vlayout 的整体设计思路与代码结构有一定掌握；

#### 免费福利
- 阿里巴巴纪念礼品
- 有机会免费获取国内技术大会门票
- 不定期在阿里巴巴园区组织技术交流，相互学习

#### 联系方式
发送个人简介与意向：xlhongultimate@gmail.com

**Comment by PantomZ** [comment]
如果demo中，能加一些，比如：网络请求加载数据，刷新数据，内存优化的一些例子，是极好的
