### ISSUE TITLE
关于使用LinearLayoutHelper加载更多数据时出现的bug

### ISSUE THREAD

**Issue by sudeqiangxx** [alibaba/vlayout#238]
使用LinearLayoutHelper做类似recyceView功能时，当有更多的item时，数据回收问题，出现item复用出现数据更新很多次，相当于一个textview上的数据变动很多次，出现抖动问题。估计是复用上出了问题。

**Comment by longerian** [comment]
是在同一个item上多次绑定数据吗

**Comment by longerian** [comment]
1.2.9 , linearLayoutHelper 的问题解决过。
