### ISSUE TITLE
position 问题

### ISSUE THREAD

**Issue by lvtanxi** [alibaba/vlayout#240]
DelegateAdapter 添加了多个adapter之后，onBindViewHolder中的position还是从0开始的，这个我能理解。但是一个问题就是，在添加多个adapter之后GridLayoutHelper会出现问题，如下：
`
 //设置Grid布局
        GridLayoutHelper gridLayoutHelper = new GridLayoutHelper(2);
        //是否自动扩展
        gridLayoutHelper.setAutoExpand(false);
        //自定义设置某些位置的Item的占格数
        gridLayoutHelper.setSpanSizeLookup(new GridLayoutHelper.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                Log.e("position", position + "");
                if (position == 13) {
                    return 2;
                } else {
                    return 1;
                }
            }
        });
`
GridLayoutHelper 中的position不是对应当前adapter的了。position在adapter的起始位置变成了这个adapter前面所有的itemCount的个数了。我如何使position从0开始呢？

**Comment by longerian** [comment]
是的 ，参考这里：https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md

『在 SpanSizeLookup 中，public int getSpanSize(int position) 方法参数的 position 是整个页面的 position 信息，需要获取当前 layoutHelper 内的相对位置，需要减去一个偏移量，即 position - getStartPosition()。』

**Comment by lvtanxi** [comment]
刚刚处理好，说来关闭问题。不过谢谢解答
