### ISSUE TITLE
我在v-layout中有一个布局，布局中有viewflipper的广告文字轮播出现问题

### ISSUE THREAD

**Issue by PantomZ** [alibaba/vlayout#241]
viewflipper有两个动画，上下滚动用的。然后显示的时候，整个v-layout会向下移动；
在recyclerview上的itemview中加入viewflipper没有这个向下平移的问题

**Comment by longerian** [comment]
画面抖动 平移的问题，基本上是由于某个padding 或者margin重复计算或者遗漏计算导致，需要看一下你的页面结构来。或者你先看看把相关参数屏蔽掉，先看看是那个边距引起的。

**Comment by PantomZ** [comment]
![screenshot_1511365996](https://user-images.githubusercontent.com/19757494/33136479-43801998-cfe0-11e7-9e3d-af7835dc505a.png)

**Comment by PantomZ** [comment]
行业资讯，就是一个轮播的广告文字栏

**Comment by PantomZ** [comment]
多谢，已经解决，是某个LinearLayoutHelper加了dividerHeight,导致的。
