### ISSUE TITLE
FloatLayoutHelper 滑动onTouch 与 onClick 冲突了。

### ISSUE THREAD

**Issue by Justin777s** [alibaba/vlayout#246]
点击 FloatView FloatLayoutHelper.java line 422-427
'''
 case MotionEvent.ACTION_UP:
                case MotionEvent.ACTION_CANCEL:
                    doPullOverAnimation(v);
                    (v.getParent()).requestDisallowInterceptTouchEvent(false);
                    v.setPressed(false);
                    break;
'''
事件无法到onClick

修改了一下 
'''
  case MotionEvent.ACTION_UP:
                    //如果上一个滑动事件是move，则取消不执行onClick
                    if (Math.abs(event.getX() - lastPosX) > mTouchSlop
                            || Math.abs(event.getY() - lastPosY) > mTouchSlop
                            || lastMotionAction == MotionEvent.ACTION_MOVE) {
                        isDrag = true;
                        (v.getParent()).requestDisallowInterceptTouchEvent(false);
                        v.setPressed(false);
                    }else{
                        isDrag = false;
                    }
                    doPullOverAnimation(v);
                    break;
'''

**Comment by longerian** [comment]
@Justin777s 建议以pr的形式提过来，并说明下上下文，解决的场景，我整体看一下。
