### ISSUE TITLE
关于addAdapter(position,adapter)的问题

### ISSUE THREAD

**Issue by NeVaDaAAA** [alibaba/vlayout#247]
大神您好 
我现在有个问题想请教

我现在在用Vlayout写首页布局，但是我们首页的布局接口比较多，所以我使用了下面的方法
public void addAdapter(int position, @Nullable Adapter adapter) {
        addAdapters(position, Collections.singletonList(adapter));
    }
在网络请求成功获得数据后  delegateAdapter.addAdapter(0,bannerAdapter);
                                            delegateAdapter.addAdapter(1,menuRvAdapter);
                                            delegateAdapter.addAdapter(2,marqueeAdapter);
                                            delegateAdapter.addAdapter(3,logisticAdapter);
                                            delegateAdapter.notifyDataSetChanged();
然后出现了界面错乱的情况 ，Banner下面不是Menu而是Marquee，Marquee下面是Menu 。请问该如何解决这个问题呢？
提前感谢！！！！！！！

**Comment by lixi0912** [comment]
我这边的做法是，将需要的类型固定添加到 delegateAdapter， 数据加载成功后对 notify 实际的 adapter。

比如
```java
List<DelegateAdapter.Adpater> adapters = new ArrayList<>();

adapters.add(bannerAdapter);
adapters.add(menuRvAdapter);
adapters.add(marqueeAdapter);
adapters.add(logisticAdapter);

delegateAdapter.setAdapters(adapters);
// ....
// ...

bannerAdapter.notifyItemRangeInsert(insertIndex,insertSize);

```

**Comment by longerian** [comment]
可以参考楼上的做法，最好构造好一个list之后，一次性调用addAdapter方法。如果你的list顺序是对的，而显示错了，很可能是复用出错了。
https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md
