### ISSUE TITLE
请问如何使用delegateAdapter.addAdapter(position，adapter)？

### ISSUE THREAD

**Issue by yanyiqun001** [alibaba/vlayout#248]
delegateAdapter.addAdapter（adapter）可以正常添加布局在最后面，但使用delegateAdapter.addAdapter(position，adapter)
adapter的onBindViewHolder方法就获取不到布局文件资源

**Comment by longerian** [comment]
是什么错误

**Comment by yanyiqun001** [comment]
添加的adapter的onBindViewHolder中 通过holder.itemview.findviewbyid 获取不到控件

**Comment by longerian** [comment]
@yanyiqun001  应该是你的复用有问题，拿到了错误的view，检查一下类型，看一下  FAQ 里的说明：https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md
