### ISSUE TITLE
GridLayoutHelper 设置的是横向显示个数问题

### ISSUE THREAD

**Issue by renbin1990** [alibaba/vlayout#249]
您好,我设置的是 横向显示4个显示两排    但是实际显示的是横向显示两个,显示4排   
下面是代码,您看下
//2 功能列表
        GridLayoutHelper personGridHelper = new GridLayoutHelper(4);
        personGridHelper.setItemCount(8);
        personGridHelper.setVGap(3);
        personGridHelper.setHGap(3);
        GNAdapter gnAdapter = new GNAdapter(this, personGridHelper, 8, listItem);

这是适配
public class GNAdapter extends DelegateAdapter.Adapter<GNAdapter.MainViewHolder> {

    private Context mContext;
    private LayoutHelper mPersonGridHelper;
    private int mCount;
    private RecyclerView.LayoutParams mLayoutParams;
    private ArrayList<HashMap<String, Object>> mListItem;
    private MyItemClickListener myItemClickListener;

    public GNAdapter(Context context, LayoutHelper personGridHelper, int count, ArrayList<HashMap<String, Object>> listItem) {
        this(context, personGridHelper, count, new RecyclerView.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, 300), listItem);

    }
    public GNAdapter(Context context, LayoutHelper personGridHelper, int count, @NonNull RecyclerView.LayoutParams layoutParams, ArrayList<HashMap<String, Object>> listItem){
        this.mContext = context;
        this.mPersonGridHelper = personGridHelper;
        this.mCount = count;
        this.mLayoutParams = layoutParams;
        this.mListItem = listItem;
    }

    @Override
    public LayoutHelper onCreateLayoutHelper() {
        return mPersonGridHelper;
    }

    @Override
    public MainViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return new GNAdapter.MainViewHolder(LayoutInflater.from(mContext).inflate(R.layout.item_gn, parent, false));
    }

    @Override
    public void onBindViewHolder(GNAdapter.MainViewHolder holder, int position) {
        // 绑定视图
        holder.Text.setText((String) mListItem.get(position).get("ItemTitle"));
        holder.image.setImageResource((Integer) mListItem.get(position).get("ItemImage"));
    }

    @Override
    public int getItemCount() {
        return mCount;
    }
    public class MainViewHolder extends RecyclerView.ViewHolder {

        public TextView Text;
        public ImageView image;

        public MainViewHolder(View root) {
            super(root);
            // 绑定视图
            Text = (TextView) root.findViewById(R.id.Item);
            image = (ImageView) root.findViewById(R.id.Image);
        }

        public TextView getText() {
            return Text;
        }
    }

**Comment by longerian** [comment]
没有问题，用你的代码也跑了一下，没有你说的问题。
