### ISSUE TITLE
显示错乱

### ISSUE THREAD

**Issue by tu-jiong** [alibaba/vlayout#251]
同时添加 LinearLayoutHelper GridLayoutHelper 后，调用RecyclerView的scrollToPosition()方法 
会出现显示错乱的情况

**Comment by longerian** [comment]
这是由于滚动后没有触发重新布局引起的，试试滚动结束调用一次requestLayout

**Comment by tu-jiong** [comment]
调用smoothScrollToPosition() 就没有问题了
