### ISSUE TITLE
appcompat-v7版本报错

### ISSUE THREAD

**Issue by 37Jayden** [alibaba/vlayout#253]
<img width="1053" alt="wx20171130-152249 2x" src="https://user-images.githubusercontent.com/10772918/33418750-5e12f016-d5e2-11e7-8e5d-2e9f41496b17.png">

导入com.alibaba.android:vlayout:1.2.2@aar，appcompat-v7报错

**Comment by longerian** [comment]
因为内部用的是23.1.1的support依赖，这是一个警告，
