### ISSUE TITLE
item高度问题

### ISSUE THREAD

**Issue by AIlll** [alibaba/vlayout#254]
item布局文件宽高都设置为match_parent，但是只有宽有效果，高度就是只能自适应，match_parent没有任何效果，加载布局也是LayoutInflater.from(mContext).inflate(R.layout.view, parent, false)，适配器也没有对布局的宽高做修改，求解

**Comment by longerian** [comment]
item宽度是根据布局类型、样式和屏幕宽度来确定的，所以宽match_parent是可以的，但高度就不行，默认是以wrap_content，需要item自己确定高度值

**Comment by AIlll** [comment]
![image](https://user-images.githubusercontent.com/23742136/33470449-4d60ec3e-d6a3-11e7-9a84-205fd44e427a.png)
![image](https://user-images.githubusercontent.com/23742136/33470482-6ab7334c-d6a3-11e7-88b6-ee7ee4b46a12.png)
@longerian 再请教一下StickyLayoutHelper，吸顶是能吸顶，但是被后面的item给覆盖了，这是什么原因

**Comment by longerian** [comment]
StickyLayoutHelper里的item在sticky状态的时候，是会添加到最顶层的，你先看看view的层级，是不是后面的item写了什么z轴参数绘制到顶层了。

**Comment by AIlll** [comment]
貌似是cardView的原因？

**Comment by AIlll** [comment]
@longerian 那就是cardView的原因了

**Comment by longerian** [comment]
是支持的，但是默认都是0，你可以给sticky里的值加一个z更大的值，让它能绘制到更高的层级。
