### ISSUE TITLE
vlayout嵌套ViewPager高度不自适应

### ISSUE THREAD

**Issue by chenzhiwei-github** [alibaba/vlayout#259]

**Comment by longerian** [comment]
ViewPager 本身的实现原理导致它不能支持高度 wrap_content，需要写死或者按比例人为设置一个固定高度，如果你想要wrap_content，需要定制一下源码，如果你在Google上搜索过的话，应该可以找到我早年写的一篇文章：http://pingguohe.net/2016/01/21/how-to-make-viewpages-height-attr-support-wrap-content-efficiently.html
