### ISSUE TITLE
How to set the LayoutHelper divider view?

### ISSUE THREAD

**Issue by siyehua** [alibaba/vlayout#26]
怎么设置LayoutHelper 的divider,像ListView那样.

找到了setDividerHeight方法,但是没有找到setDivide,只能通过item来实现吗?

**Comment by longerian** [comment]
RecyclerView的框架里设计的机制是使用```ItemDecoration ```，所以尝试使用这个。
用 item 来实现的话也是可行的，效率会低一些。
如果是纯色的，用背景来实现也可以。

**Comment by siyehua** [comment]
感谢回答.
因为这个项目主要是为了多种item设计的,所以可能会有多种不同的分割线.
所以更希望能通过LayoutHelper来设置不同的分割线
感觉这样更加符合设计一点

**Comment by longerian** [comment]
是的，```ItemDecoration```支持区分不同的 item 的，但要自定义实现，可以参考[问答](http://stackoverflow.com/questions/35013383/itemdecoration-based-on-viewtype-in-recyclerview)

如果使用了```ItemDecoration```出现了 bug，我可以解一下。但是这个功能本身确实不适合 layoutHelper 做。
