### ISSUE TITLE
called detach on an already detached child ViewHolder{8ce4457 position=2 id=-1, oldPos=-1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent

### ISSUE THREAD

**Issue by HeYongRui** [alibaba/vlayout#262]
,添加多个adapter，有一个adapter的item有多个，滑动的时候就出现called detach on an already detached child ViewHolder{8ce4457 position=2 id=-1, oldPos=-1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent，试了好多方法都不行，不知道怎么回事，求解！！！！（*参考望山试过更改LayoutInflater的inflate的参数无效）

**Comment by longerian** [comment]
大概是索引位置错了 demo跑过了吗

**Comment by HeYongRui** [comment]
跑过了，我添加的子adapter如下
` class VFeatureAdapter extends BaseDelegateAdapter<VFeatureAdapter.VFeatureViewHolder> {

    private List<AdvertDto> advertDtoList;
    private Context mContext;

    public VFeatureAdapter(List<AdvertDto> advertDtoList) {
        this.advertDtoList = advertDtoList;
    }

    public VFeatureAdapter(Context mContext, LayoutHelper mLayoutHelper, List<AdvertDto> advertDtoList) {
        super(mContext, mLayoutHelper);
        this.advertDtoList = advertDtoList;
    }

    public VFeatureAdapter(Context mContext, LayoutHelper mLayoutHelper, VirtualLayoutManager.LayoutParams mLayoutParams, List<AdvertDto> advertDtoList) {
        super(mContext, mLayoutHelper, mLayoutParams);
        this.advertDtoList = advertDtoList;
        this.mContext = mContext;
    }

    @Override
    public VFeatureViewHolder doOnCreateViewHolder(ViewGroup parent, int viewType) {
        VFeatureViewHolder vFeatureViewHolder = null;
//        switch (viewType) {
//            case 1:
//                vFeatureViewHolder = new VFeatureViewHolder(LayoutInflater.from(this.getContext()).inflate(R.layout.fragement_main_feature_item_one, parent,
//                        false));
//                break;
//            case 2:
//                vFeatureViewHolder = new VFeatureViewHolder(LayoutInflater.from(this.getContext()).inflate(R.layout.fragement_main_feature_item_two, parent,
//                        false));
//                break;
//            case 3:
//                vFeatureViewHolder = new VFeatureViewHolder(LayoutInflater.from(this.getContext()).inflate(R.layout.fragement_main_feature_item_three, parent,
//                        false));
//                break;
//        }
        vFeatureViewHolder = new VFeatureViewHolder(LayoutInflater.from(mContext).inflate(R.layout.fragement_main_feature_item_one, null));
        return vFeatureViewHolder;
    }

    @Override
    public void doOnBindViewHolder(VFeatureViewHolder holder, int position) {
        AdvertDto advertDto = advertDtoList.get(position);
        if (advertDto == null) return;
        List<AdvertPhotoDto> advertPhotoDtoList = advertDto.getAdvertPhotoDtoList();
        if (advertPhotoDtoList == null || advertPhotoDtoList.size() < 0) return;
        int itemViewType = holder.getItemViewType();
        AdvertPhotoDto advertPhotoDto = advertPhotoDtoList.get(0);
        GlideUtil.loadAdvert(getContext(), advertPhotoDto.getUrl(), holder.item_advert_one_image);
        holder.item_advert_one_title.setText(advertDto.getTitle() == null ? "" : advertDto.getTitle());
//        switch (itemViewType) {
//            case 1:
//                AdvertPhotoDto advertPhotoDto = advertPhotoDtoList.get(0);
//                GlideUtil.loadAdvert(getContext(), advertPhotoDto.getUrl(), holder.item_advert_one_image);
//                holder.item_advert_one_title.setText(advertDto.getTitle() == null ? "" : advertDto.getTitle());
//                break;
//            case 2:
//                break;
//            case 3:
//                break;
//        }
    }

    @Override
    public int doGetItemCount() {
        return advertDtoList.size();
    }

    @Override
    public int getItemViewType(int position) {
        return 1;
    }
    //    @Override
//    public int getItemViewType(int position) {
//        AdvertDto advertDto = advertDtoList.get(position);
//        if (advertDto == null) return 1;
//        List<AdvertPhotoDto> advertPhotoDtoList = advertDto.getAdvertPhotoDtoList();
//        if (advertPhotoDtoList == null) return 1;
//        if (advertPhotoDtoList.size() == 1) {
//            AdvertPhotoDto advertPhotoDto = advertPhotoDtoList.get(0);
//            if (advertPhotoDto == null) return 1;
//            Integer is_movie = advertPhotoDto.getIs_movie() == null ? 0 : advertPhotoDto.getIs_movie();
//            if (is_movie == 0) {
//                return 1;
//            } else if (is_movie == 1) {
//                return 3;
//            }
//        } else if (advertPhotoDtoList.size() == 2) {
//            return 2;
//        }
//        return 1;
//    }

    static class VFeatureViewHolder extends BaseViewHolder {

        //        @BindView(R.id.item_advert_one_image)
        ImageView item_advert_one_image;
        //        @BindView(R.id.flow_logo)
        ImageView flow_logo;
        //        @BindView(R.id.item_advert_one_title)
        TextView item_advert_one_title;

        public VFeatureViewHolder(View itemView) {
            super(itemView);
            item_advert_one_image = itemView.findViewById(R.id.item_advert_one_image);
            flow_logo = itemView.findViewById(R.id.flow_logo);
            item_advert_one_title = itemView.findViewById(R.id.item_advert_one_title);
        }
    }`

**Comment by HeYongRui** [comment]
跑过了，我添加的子adapter如下
` class VFeatureAdapter extends BaseDelegateAdapter<VFeatureAdapter.VFeatureViewHolder> {

    private List<AdvertDto> advertDtoList;
    private Context mContext;

    public VFeatureAdapter(List<AdvertDto> advertDtoList) {
        this.advertDtoList = advertDtoList;
    }

    public VFeatureAdapter(Context mContext, LayoutHelper mLayoutHelper, List<AdvertDto> advertDtoList) {
        super(mContext, mLayoutHelper);
        this.advertDtoList = advertDtoList;
    }

    public VFeatureAdapter(Context mContext, LayoutHelper mLayoutHelper, VirtualLayoutManager.LayoutParams mLayoutParams, List<AdvertDto> advertDtoList) {
        super(mContext, mLayoutHelper, mLayoutParams);
        this.advertDtoList = advertDtoList;
        this.mContext = mContext;
    }

    @Override
    public VFeatureViewHolder doOnCreateViewHolder(ViewGroup parent, int viewType) {
        VFeatureViewHolder vFeatureViewHolder = null;
       switch (viewType) {
            case 1:
                vFeatureViewHolder = new VFeatureViewHolder(LayoutInflater.from(this.getContext()).inflate(R.layout.fragement_main_feature_item_one, parent,
                        false));
                break;
           case 2:
                vFeatureViewHolder = new VFeatureViewHolder(LayoutInflater.from(this.getContext()).inflate(R.layout.fragement_main_feature_item_two, parent,
                        false));
                break;
            case 3:
                vFeatureViewHolder = new VFeatureViewHolder(LayoutInflater.from(this.getContext()).inflate(R.layout.fragement_main_feature_item_three, parent,
                        false));
                break;
        }
        vFeatureViewHolder = new VFeatureViewHolder(LayoutInflater.from(mContext).inflate(R.layout.fragement_main_feature_item_one, null));
        return vFeatureViewHolder;
    }

    @Override
    public void doOnBindViewHolder(VFeatureViewHolder holder, int position) {
        AdvertDto advertDto = advertDtoList.get(position);
        if (advertDto == null) return;
        List<AdvertPhotoDto> advertPhotoDtoList = advertDto.getAdvertPhotoDtoList();
        if (advertPhotoDtoList == null || advertPhotoDtoList.size() < 0) return;
        int itemViewType = holder.getItemViewType();
        AdvertPhotoDto advertPhotoDto = advertPhotoDtoList.get(0);
        GlideUtil.loadAdvert(getContext(), advertPhotoDto.getUrl(), holder.item_advert_one_image);
        holder.item_advert_one_title.setText(advertDto.getTitle() == null ? "" : advertDto.getTitle());
        switch (itemViewType) {
            case 1:
                AdvertPhotoDto advertPhotoDto = advertPhotoDtoList.get(0);
                GlideUtil.loadAdvert(getContext(), advertPhotoDto.getUrl(), holder.item_advert_one_image);
                holder.item_advert_one_title.setText(advertDto.getTitle() == null ? "" : advertDto.getTitle());
                break;
            case 2:
                break;
            case 3:
                break;
        }
    }

    @Override
    public int doGetItemCount() {
        return advertDtoList.size();
    }

    @Override
    public int getItemViewType(int position) {
        return 1;
    }
        @Override
    public int getItemViewType(int position) {
        AdvertDto advertDto = advertDtoList.get(position);
       if (advertDto == null) return 1;
        List<AdvertPhotoDto> advertPhotoDtoList = advertDto.getAdvertPhotoDtoList();
        if (advertPhotoDtoList == null) return 1;
        if (advertPhotoDtoList.size() == 1) {
            AdvertPhotoDto advertPhotoDto = advertPhotoDtoList.get(0);
            if (advertPhotoDto == null) return 1;
            Integer is_movie = advertPhotoDto.getIs_movie() == null ? 0 : advertPhotoDto.getIs_movie();
            if (is_movie == 0) {
                return 1;
            } else if (is_movie == 1) {
                return 3;
            }
        } else if (advertPhotoDtoList.size() == 2) {
            return 2;
        }
        return 1;
    }

    static class VFeatureViewHolder extends BaseViewHolder {
        ImageView item_advert_one_image;
  
        ImageView flow_logo;
       
        TextView item_advert_one_title;

        public VFeatureViewHolder(View itemView) {
            super(itemView);
            item_advert_one_image = itemView.findViewById(R.id.item_advert_one_image);
            flow_logo = itemView.findViewById(R.id.flow_logo);
            item_advert_one_title = itemView.findViewById(R.id.item_advert_one_title);
        }
    }`

**Comment by HeYongRui** [comment]
我好想找到原因了，是BaseDelegateAdapter的VirtualLayoutManager.LayoutParams问题。另外，这个库很棒，感谢开源分享，方便了很多工作，希望继续加油！(｡◕ˇ∀ˇ◕)！

**Comment by longerian** [comment]
谢谢，最终上线了的话，在 #255 里统计一下吧
