### ISSUE TITLE
设置布局参数闪退！

### ISSUE THREAD

**Issue by HeYongRui** [alibaba/vlayout#265]
`@Override
        public void onBindViewHolder(MainViewHolder holder, int position) {
            holder.itemView.setLayoutParams(
                    new LayoutParams(mLayoutParams));
        }`
就是在 holder.itemView.setLayoutParams(
                    new LayoutParams(mLayoutParams));的时候会出错，然后闪退，但是demo里又没问题

**Comment by longerian** [comment]
日志贴出来

**Comment by longerian** [comment]
可能是你的layoutParam类型不正确吧
