### ISSUE TITLE
点击最后item时自动滚动

### ISSUE THREAD

**Issue by jielundewode** [alibaba/vlayout#268]
列表比较长，滑动到最底部，点击最下面的任意一个item跳转到一个新的Activity，返回时会自动滚动！

**Comment by jielundewode** [comment]
![p45oh-qayic](https://user-images.githubusercontent.com/10189846/33977256-ff56083a-e0d4-11e7-97f0-8c287208968d.gif)

**Comment by longerian** [comment]
离开和返回是不是有什么触发布局的操作？目前确实在某些场景下因为重新布局的时候起始锚点计算有问题，导致会抖一下。

**Comment by jielundewode** [comment]
没有，只是启动了一个新的Activity

**Comment by jielundewode** [comment]
@longerian

**Comment by jielundewode** [comment]
` open fun initPartCourse(bodys: ArrayList<AllCourse.BodyPart>) {
        var Adapter_GridLayout = presenter.genColumnLayout2(bodys, object : MyItemClickListener {
            override fun onItemClick(view: View?, position: Int) {

                BodyPartActivity_.intent(this@CourseFragment).extra("id", bodys.get(position).id)
                        .startForResult(99)


            }
        })

        adapters.add(Adapter_GridLayout)
    }

    @OnActivityResult(99)
    open fun onResult() {

        Handler().postDelayed({
            ALog.e("dy=$dy")
            recyclerView.scrollBy(0, dy)


        }, 650)


    }`
如上，由于一直会向上滚动，我不得不加了一个向下滚动逻辑，所以看起来会跳一下，如果不加会一直向上滚动，最后身体部位完全不可见

**Comment by jielundewode** [comment]
@longerian 问题找到了，是设置了LayoutHelper的padding和margin的问题，能修复吗？

**Comment by longerian** [comment]
应该是能修复的，要一点时间，我修好了同步你，你也可以一起看看

**Comment by jielundewode** [comment]
应该是vlayout和滑动返回库冲突了，现在更换滑动返回库没事了，原先用的这个库：https://github.com/Jude95/SwipeBackHelper，去掉之后没事了
@longerian

**Comment by longerian** [comment]
ok，我修复了一个这样的问题，1.2.7 ，不知道是不是也能解决你的场景，有空试试看。

**Comment by longerian** [comment]
另外如果产品已经上线，到 #255 登记下咋样

**Comment by jielundewode** [comment]
@longerian 问题依旧，只是感觉上移的幅度变小了

**Comment by yahooyee** [comment]
@longerian 我也碰到了类似了的问题
