### ISSUE TITLE
动态更换LayoutHelper

### ISSUE THREAD

**Issue by lazy-ape** [alibaba/vlayout#270]
怎么动态更换LayoutHelper?需求是列表和网格的切换，怎么能够动态的将LinearLayoutHelper改为GridLayoutHelper?

**Comment by longerian** [comment]
这个应该是数据驱动来更换，比如说你应该通过数据来动态的创建layoutHelper，这样数据变了，内容自然就变了。
我们也是在Tangram框架里封装了这样一层逻辑来切换布局类型的。具体的代码在 https://github.com/alibaba/Tangram-Android/blob/master/tangram/src/main/java/com/tmall/wireless/tangram/core/adapter/GroupBasicAdapter.java

**Comment by lazy-ape** [comment]
我现在是继承DelegateAdapter.Adapter实现的，onCreateLayoutHelper里面直接返回的LayoutHelper，这样怎么根据数据动态创建呢？是否有刷新的方法adapter会重新调用onCreateLayoutHelper方法？

**Comment by lazy-ape** [comment]
已经解决了，谢谢！我在onCreateLayoutHelper中判断一下返回相应的LayoutHelper，然后重新调用了DelegateAdapter的setAdapters()，

**Comment by longerian** [comment]
嗯嗯 办法总是有的

**Comment by HuangJAndroid** [comment]
> 已经解决了，谢谢！我在onCreateLayoutHelper中判断一下返回相应的LayoutHelper，然后重新调用了DelegateAdapter的setAdapters()，

大神，你是怎么解决的，在那几个方法里面修改

**Comment by lazy-ape** [comment]
> > 已经解决了，谢谢！我在onCreateLayoutHelper中判断一下返回相应的LayoutHelper，然后重新调用了DelegateAdapter的setAdapters()，
> 
> 大神，你是怎么解决的，在那几个方法里面修改

这个说起来不太好说。大概的思路是这样：

1. 我自定义一个` ProductListDelegateAdapter  extends DelegateAdapter.Adapter `,里面有个切换的方法，同时重写`onCreateLayoutHelper`方法，根据不同设置返回不同的`LayoutHelper`.

##### 示例代码如下：
``` java
 private int mShowType = ConstantUtils.COMMON_ITEM_TYPE_PRODUCT_LIST;
 public void switchShowType(int showType){
       this.mShowType = showType;
 }

  @Override
  public int getItemViewType(int position) {
       return mShowType;
  }

  @Override
  public LayoutHelper onCreateLayoutHelper() {
       if(mShowType == ConstantUtils.COMMON_ITEM_TYPE_PRODUCT_LIST) {
            return new LinearLayoutHelper();
       }else{
            GridLayoutHelper gridLayoutHelper = new GridLayoutHelper(2);
            int padding = DensityUtil.dip2px(mContext,5f);
            gridLayoutHelper.setAutoExpand(false);
            gridLayoutHelper.setBgColor(mContext.getResources().getColor(R.color.grid_divider_gray));
            gridLayoutHelper.setPadding(padding,padding,padding,padding);
            gridLayoutHelper.setHGap(padding);
            gridLayoutHelper.setVGap(padding);
            return gridLayoutHelper;
        }
  }
```

2.在activity里面 我直接使用的是`DelegateAdapter`，大致是这样。
``` java
 mRecyclerView = (LoadMoreRecyclerView) findViewById(R.id.recyclerview_products);
 mVirtualLayoutManager = new VirtualLayoutManager(this);
 mDelegateAdapter = new DelegateAdapter(mVirtualLayoutManager,true);
        mRecyclerView.getRecycledViewPool().setMaxRecycledViews(ConstantUtils.COMMON_ITEM_TYPE_PRODUCT_LIST,10);
mRecyclerView.setLayoutManager(mVirtualLayoutManager);
 mRecyclerView.setAdapter(mDelegateAdapter);
```
在需要切换的时候，就重新设置了`DelegateAdapter`里面的adapter。

``` java
mProductAdapter.switchShowType(ConstantUtils.COMMON_ITEM_TYPE_PRODUCT_GRID);
mDelegateAdapter.clear();  //清空
mProductAdapter.setData(mProducts);
mDelegateAdapter.addAdapter(mProductAdapter);  //重新设置
 mDelegateAdapter.notifyDataSetChanged();
```

大致逻辑是这样子，我不知道有没有表达清楚。因为很久之前做的了，只是摘取了部分的代码片段，你看能不能帮你解决问题。

**Comment by HuangJAndroid** [comment]
谢谢

**Comment by HuangJAndroid** [comment]
> > 已经解决了，谢谢！我在onCreateLayoutHelper中判断一下返回相应的LayoutHelper，然后重新调用了DelegateAdapter的setAdapters()，
> 
> 大神，你是怎么解决的，在那几个方法里面修改

你有木有出现翻多页切换 会出现item顺序改变了

**Comment by HuangJAndroid** [comment]
> 已经解决了，谢谢！我在onCreateLayoutHelper中判断一下返回相应的LayoutHelper，然后重新调用了DelegateAdapter的setAdapters()，

你有木有出现翻多页切换 会出现item顺序改变了

**Comment by HuangJAndroid** [comment]
> 已经解决了，谢谢！我在onCreateLayoutHelper中判断一下返回相应的LayoutHelper，然后重新调用了DelegateAdapter的setAdapters()，

你有木有出现往下翻，然后切换，布局渲染不同，0竟然跑到右边了
