### ISSUE TITLE
你好，请问在瀑布流的布局下会自动移动一小段位置

### ISSUE THREAD

**Issue by hyr0318** [alibaba/vlayout#273]
在瀑布流下，加载更多，刷新界面，会出现移动一小段距离的情况，请问这个要怎么解决？

布局图片高度是服务器传的图片高度，再设置给布局的图片高度的
   
        StaggeredGridLayoutHelper staggerHelper = new StaggeredGridLayoutHelper(2, 30);
    
        staggerHelper.setPadding(30, 15, 30, 15);
        
        staggerHelper.setBgColor(getResources().getColor(R.color.white));
        
        return staggerHelper;

**Comment by longerian** [comment]
我排查一下吧  T_T

**Comment by hyr0318** [comment]
@longerian  好的，那弄好了 @一下我哟，辛苦了哈

**Comment by longerian** [comment]
@hyr0318 我修复了一个这样的问题，1.2.7 ，你试试看，不行再跟我反馈。

**Comment by longerian** [comment]
1.2.8 你再测一测 @hyr0318

**Comment by zxm1243** [comment]
@LinXiaoTao 请问这个问题解决了吗

**Comment by LinXiaoTao** [comment]
@zxm1243 并没有。。瀑布流用原生的了。

**Comment by zxm1243** [comment]
@hyr0318 请问这个问题解决了吗
