### ISSUE TITLE
item是UltraViewPager,滑动时布局混乱，出现卡顿现象

### ISSUE THREAD

**Issue by xueyaolive** [alibaba/vlayout#274]
@longerian 

- 
![m1](https://user-images.githubusercontent.com/15100615/34282393-fe26faa6-e6ff-11e7-8226-48223a26d4c9.png)
![m2](https://user-images.githubusercontent.com/15100615/34282394-fe69e712-e6ff-11e7-8069-106592b1a5f1.png)
![m3](https://user-images.githubusercontent.com/15100615/34282395-fe9bb792-e6ff-11e7-91a2-79fc72cc128a.png)

**Comment by longerian** [comment]
卡顿看一下有没有exception出来。

你说的布局混乱是不是两个UltraViewPager复用导致错了。

**Comment by xueyaolive** [comment]
只有一个UltraViewPager，卡顿确实出现ClassCastException，删除UltraViewPager无异常
---也许是我不会嵌套导致的，可以帮忙指正一下？
//嵌套UltraViewPager的代码
- 
public class VFPageAdapter extends DelegateAdapter.Adapter<RecyclerView.ViewHolder> {

    private RecyclerView.RecycledViewPool viewPool;

    public VFPageAdapter(RecyclerView.RecycledViewPool recycledViewPool) {
        viewPool = recycledViewPool;
    }

    @Override
    public LayoutHelper onCreateLayoutHelper() {
        LinearLayoutHelper layoutHelper = new LinearLayoutHelper();
        layoutHelper.setMargin(16, 8, 16, 8);
        return layoutHelper;
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        if (viewType == 1) {
            View view = LayoutInflater.from(parent.getContext())
                    .inflate(R.layout.item_vpage, parent, false);
            return new ViewHolder(view);
        }
        View view = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.item_vchildpage, parent, false);
        return new ViewPageHolder(view);
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        if (holder instanceof VFPageAdapter.ViewHolder) {
            ((VFPageAdapter.ViewHolder) holder).ultraViewPager.setAdapter(new VPageAdapter(this, viewPool));
        }
    }

    @Override
    public void onViewRecycled(RecyclerView.ViewHolder holder) {
        if (holder instanceof ViewHolder) {
            (((ViewHolder) holder).ultraViewPager).setAdapter(null);
        }
    }

    @Override
    public int getItemViewType(int position) {
        return 1;
    }

    @Override
    public int getItemCount() {
        return 1;
    }

    static class ViewHolder extends RecyclerView.ViewHolder {

        UltraViewPager ultraViewPager;

        public ViewHolder(View itemView) {
            super(itemView);
            ultraViewPager = itemView.findViewById(R.id.viewPage);
            ultraViewPager.setScrollMode(UltraViewPager.ScrollMode.HORIZONTAL);
            //内置indicator初始化
            ultraViewPager.initIndicator();
            //设置indicator样式
            ultraViewPager.getIndicator()
                    .setOrientation(UltraViewPager.Orientation.HORIZONTAL)
                    .setFocusColor(Color.GREEN)
                    .setNormalColor(Color.WHITE)
                    .setRadius((int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 2,
                            itemView.getContext().getResources().getDisplayMetrics()));
            //设置indicator对齐方式
            ultraViewPager.getIndicator().setGravity(Gravity.CENTER_HORIZONTAL | Gravity.BOTTOM);
            //构造indicator,绑定到UltraViewPager
            ultraViewPager.getIndicator().build();

            //设定页面循环播放
            ultraViewPager.setInfiniteLoop(true);
            //设定页面自动切换  间隔2秒
            ultraViewPager.setAutoScroll(2000);
        }
    }
    
    static class ViewPageHolder extends RecyclerView.ViewHolder{
        public ViewPageHolder(View itemView) {
            super(itemView);
        }
    }

}

//UltraViewPager adapter
- 
public class VPageAdapter extends RecyclablePagerAdapter<RecyclerView.ViewHolder> {

    public VPageAdapter(VFPageAdapter adapter, RecyclerView.RecycledViewPool pool) {
        super(adapter, pool);
    }

    @Override
    public int getCount() {
        return 3;
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {
        switch (position) {
            case 0:
                viewHolder.itemView.setBackgroundColor(Color.parseColor("#2196F3"));
                break;
            case 1:
                viewHolder.itemView.setBackgroundColor(Color.parseColor("#673AB7"));
                break;
            case 2:
                viewHolder.itemView.setBackgroundColor(Color.parseColor("#009688"));
                break;
            default:
                viewHolder.itemView.setBackgroundColor(Color.parseColor("#2196F3"));
                break;
        }
    }

    @Override
    public int getItemViewType(int position) {
        return 0;
    }

- -

**Comment by longerian** [comment]
那应该是复用过程中出错，不同类型item用了同一个type，你看看这儿的说明：https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md#%E7%BB%84%E4%BB%B6%E5%A4%8D%E7%94%A8%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by xueyaolive** [comment]
-hasConsistItemType = false，且所有Adapter中getItemViewType(int position)未重写该方法，由于利用的是同一个RecycledViewPool(默认存储5个相同类型的组件)，而在RecyclablePagerAdapter 中return 0，多个不同Adapter可能随机存在一个type = 0(碰撞，被视为相同组件)导致池的异常复用回收，造成的后果就是抛出ClassCastException，是这样理解？

-解决方案是不是每一个Adapter都得强制手动设置itemViewType返回一个类似数据库的主键(唯一)？不用再做其它处理是这样？

-那是不是想让vlayout支持横向滑动，把recyclerView当作一个item来处理，而这个item的复用池是单独的对吗？

-非常感谢作者在繁忙中抽空指点，问题可能比较多，自己也未必表达清楚，只能厚着皮红着脸问道："大佬，请指点"

**Comment by longerian** [comment]
第一点，对的
第二点，是的，如果两个adapter之间的item可以复用，可以返回相同的
第三点，recyclerView当做item，但是recyclerVIew本身的设计是可以共享一个回收复用池的，只要你的item类型一样，当然简单处理你也可以选择不共享。

**Comment by xueyaolive** [comment]
获益匪浅，再次谢谢！
