### ISSUE TITLE
layoutHelper设置setLayoutViewBindListener背景图片，滑动的时候背景会拉伸一下

### ISSUE THREAD

**Issue by 37Jayden** [alibaba/vlayout#275]
private static class BindListener implements BaseLayoutHelper.LayoutViewBindListener {
        private String imgUrl;

        public BindListener(String imgUrl) {
            this.imgUrl = imgUrl;
        }

        @Override
        public void onBind(View layoutView, BaseLayoutHelper baseLayoutHelper) {
            //loading image
           

        }
    }
给layoutHelper设置背景时，layoutView.layoutView.getWidth()高度会变，怀疑是导致图片变形的原因，layoutView我返回的是
 mLayoutManager.setLayoutViewFactory(new LayoutViewFactory() {
            @Override
            public View generateLayoutView(@NonNull Context context) {
                  ImageView imageView = new ImageView(context);
                  imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
                  return imageView;
            }
});

**Comment by zsndev** [comment]
我也遇到了同样的问题，在列表滑动时，区域背景图片的宽高会改变，于是导致背景imageview centerCrop切图出现问题

**Comment by longerian** [comment]
调用 VirtualLayoutManager的 `setRecycleOffset()` 方法试试，它会延迟一段距离回收滑出屏幕的item。这样背景区域能保持，就不会变现。

**Comment by zsndev** [comment]
@longerian 试了试setRecycleOffset()方法，但并没有起作用。后来仔细观察了下，发现当layoutHelper的元素不能同时在一屏时下拉必定会触发背景变形的问题，所以猜测layoutHelper在有未显示元素时，不清楚自己的区域到底有多大，在可见元素变化时会动态计算区域大小，并调节背景view的大小，于是就导致了背景view中图片会根据view的大小去调整自己的显示。最后我通过把背景imageview的scaleType设置为matrix，这样就不会跟随imageview的宽高进行变化，同时根据不同手机的dpi提前调整好背景图片的尺寸后，再放入imageview中就解决了问题。

**Comment by longerian** [comment]
@zsndev 是的，所以`setRecycleOffset()`可以给一个半屏的高度，让屏幕外的内容也有机会创建处理，这样layoutHelper就能尽可能知道它的真实区域大小，当然可能也不够彻底，你的办法应该更靠谱。

**Comment by yunfanasd** [comment]
> @longerian 试了试setRecycleOffset()方法，但并没有起作用。后来仔细观察了下，发现当layoutHelper的元素不能同时在一屏时下拉必定会触发背景变形的问题，所以猜测layoutHelper在有未显示元素时，不清楚自己的区域到底有多大，在可见元素变化时会动态计算区域大小，并调节背景view的大小，于是就导致了背景view中图片会根据view的大小去调整自己的显示。最后我通过把背景imageview的scaleType设置为matrix，这样就不会跟随imageview的宽高进行变化，同时根据不同手机的dpi提前调整好背景图片的尺寸后，再放入imageview中就解决了问题。
背景的imageview 怎么获取呀

**Comment by zsndev** [comment]
@yunfanasd 不是要给给背景设置BindListener嘛，在它的回调参数里有背景的imageView
