### ISSUE TITLE
setRecycleOffset滑动背景不显示的问题

### ISSUE THREAD

**Issue by zsndev** [alibaba/vlayout#276]
我有个LinerLayoutHelper的区域有一屏多高，之前有背景变形的问题，通过#275，将背景设置为matrix解决了变形的问题。但当这个区域滑出屏幕80%左右后，背景会突然消失。后来通过您给出的建议设置setRecycleOffset为屏幕的1.5倍解决了从下往上滑出屏幕的问题。但此时当这个LinerLayoutHelper整个区域都滑出屏幕后，再滑入屏幕，背景图始终不给显示，就算整个区域都已经在屏幕内了也不给显示，直到整个区域顶端也都在屏幕了，你再下滑才会触发刷新，背景才会给显示。
由于再次滑入屏幕时，整个背景都是空白，体验很不好，我想了很多办法都不行，请求赐教

**Comment by longerian** [comment]
明白，让我想想

**Comment by zsndev** [comment]
@longerian 谢谢您的关注，昨晚我尝试把给LinerLayoutHelper设置的padding，用一个空白透明的view代替，希望能触发刷新。最后的结果是：老问题仍然有，然后滑动时LinerLayoutHelper区域大小改变导致的背景重新定位的问题变得更加明显了。接下来我会努力再多想想，希望能早日找到解决方案。

**Comment by longerian** [comment]
要触发刷新，可能需要一次 requestLayout，你能跟踪进去看一下 `afterLayout` 方法里的状态变化吗，每次布局完会在这里进行背景的大小变化处理，看看一下具体是哪个点判断错了，或者状态错了。

**Comment by zsndev** [comment]
@longerian 我在afterLayout里打了断点，在debug的时候发现这个方法会被无限次的调用，即使我不再去滑动屏幕。不知道是不是您fap里描述的“设置背景图后触发循环布局”；
我的相关代码具体如下：
`
mLayoutManager.setLayoutViewFactory(context -> {
            ImageView imageView = new ImageView(context);
            imageView.setScaleType(ImageView.ScaleType.MATRIX);
            return imageView;
        });
mLayoutManager.setRecycleOffset((int) (DensityUtil.screenHeight()*1.5));

------------
BaseLayoutHelper.LayoutViewBindListener bindListener =new BindListener(section.sectionBackImg);
                                    BaseLayoutHelper.LayoutViewUnBindListener unBindListener = new UnbindListener(section.sectionBackImg);
                                    BaseLayoutHelper.DefaultLayoutViewHelper defaultLayoutViewHelper = new BaseLayoutHelper.DefaultLayoutViewHelper(bindListener, unBindListener);
                                    layoutHelper.setLayoutViewBindListener(defaultLayoutViewHelper);
-------------
    private static class BindListener implements BaseLayoutHelper.LayoutViewBindListener {
        private String imgUrl;

        public BindListener(String imgUrl) {
            this.imgUrl = imgUrl;
        }

        @Override
        public void onBind(View layoutView, BaseLayoutHelper baseLayoutHelper) {
            String hash = HashUtil.murmurHash(imgUrl);
            ImageView imageView = (ImageView) layoutView;
            Bitmap dst = BitmapCacheManager.getInstace().getBitmap(hash);
            if(dst != null){
                imageView.setImageBitmap(dst);
            }else {
                new ImageLoader(imageView.getContext(),new MatrixViewTarget(imageView, hash),imgUrl).requestType(GlideRequestType.BITMAP).holderType(HolderType.NO_HOLDER).show();
            }
        }
    }

    private static class UnbindListener implements BaseLayoutHelper.LayoutViewUnBindListener {
        private String imgUrl;

        public UnbindListener(String imgUrl) {
            this. imgUrl = imgUrl;
        }

        @Override
        public void onUnbind(View layoutView, BaseLayoutHelper baseLayoutHelper) {
            //cancel loading image
        }
    }
`

**Comment by longerian** [comment]
是的

**Comment by zsndev** [comment]
@longerian 您能指出我是哪里的错误导致了“触发循环布局”么，我觉得已经照着文档的注意事项写了

**Comment by longerian** [comment]
我的意思是在 BindListener 里判断下这个imageview是否加载过图片，是的话，就不用再触发加载图片了，不管是从cache里获取bitmap直接加载还是通过imageLoader加载远程图片加载。

**Comment by zsndev** [comment]
@longerian 之前我的代码里，用的是咱layoutHelper里的BaseLayoutHelper.DefaultLayoutViewHelper，上面的代码里有如下两句：
**BaseLayoutHelper.DefaultLayoutViewHelper** defaultLayoutViewHelper = new **BaseLayoutHelper.DefaultLayoutViewHelper**(bindListener, unBindListener);
**layoutHelper.setLayoutViewBindListener**(defaultLayoutViewHelper);
<br />
要是只用这个不行的话，我又在代码里加了：
```
        public void onBind(View layoutView, BaseLayoutHelper baseLayoutHelper) {
            if (bgMap.get(imgUrl) == null || !bgMap.get(imgUrl)) {
               。。。。。。。
            }
        }
      public void onUnbind(View layoutView, BaseLayoutHelper baseLayoutHelper) {
            bgMap.put(imgUrl, false);
        }
```
但现在afterLayout仍然会被不停的调用，在这种小事上一直叨扰，实在抱歉，但现在确实有点懵了

**Comment by longerian** [comment]
嗯  这个问题确实比较重要
现在cpu使用率会很高吗?如果是的话说明没有切断循环布局的链路。
直接分别调用下面两个方法就行了，不用 DefaultLayoutViewHelper 了。
```
    /**
     * Better to use {@link #setLayoutViewHelper(DefaultLayoutViewHelper)}
     * @param bindListener
     */
    public void setLayoutViewBindListener(LayoutViewBindListener bindListener) {
        mLayoutViewBindListener = bindListener;
    }

    /**
     * Better to use {@link #setLayoutViewHelper(DefaultLayoutViewHelper)}
     * @param layoutViewUnBindListener
     */
    public void setLayoutViewUnBindListener(
            LayoutViewUnBindListener layoutViewUnBindListener) {
        mLayoutViewUnBindListener = layoutViewUnBindListener;
    }
```

另外每次滑动后都会有afterlayout被调用，即使它不在屏幕范围内。

**Comment by zsndev** [comment]
@longerian 多次测试后总结出问题了：
1. cpu之前一直在7% - 30%之间波动是因为有张图片是gif，把gif去掉在页面静止时cpu 0%；
2.我的页面里有两个自动切换的轮播图（使用viewPager实现，viewPager及里面的imageView大小是固定的），发现viewPager自动切换时，会触发afterLayout，两个viewPager定时切换的时间不同，所以就导致了afterLayout一直被调用，所以咱DefaultLayoutViewHelper是没问题的；

**Comment by longerian** [comment]
嗯  viewpager会触发布局的，这个还好。

**Comment by zsndev** [comment]
@longerian 在4楼您让看的日志，我观察了一下，afterLayout中scrolled的值是Integer.MAX_VALUE的时候，应该是区域背景开始布局的时候。现在的情况是，在滑到页面底端后，再把页面滑入屏幕，之前有问题的背景区域，scrolled的值一直没有出现MAX_VALUE，是不是意味着背景没有再次布局

**Comment by longerian** [comment]
Integer.MAX_VALUE  是异常情况，是不应该设置背景。LayoutMaVirtualLayoutManager 有个 runAdjustLayout 方法，可以让你手动校准背景位置，你试一下，这样你可以根据需求做更频繁的操作。

**Comment by zsndev** [comment]
@longerian 元旦回了趟老家，现在才给您反馈，十分抱歉。按照您之前的建议，调试了一下，虽然还没有完美处理，但已经在用户可以接受的范围内了，谢谢您一直以来的指导。我把整个处理流程总结下，要是有遇到同样问题的朋友可以参考下，应该能节约些精力。
最初遇到的问题：在某个LayoutHelper高度比较高（比如占了一屏多），同时上下padding也非常大的时候，会出现2个问题：
1.LayoutHelper动态计算自己的高度时，背景图简单设置为centerCrop，导致的裁剪错位问题；
2.设置setRecycleOffset后，在滑动时背景图未能及时刷新的问题；
解决方案：
1.对于第一个问题，可以通过将imageView的scaleType设置为matrix，并自己预先调整好图片大小来解决，具体见#275；
2.对于第二个问题，首先设置VirtualLayoutManager的setRecycleOffset，我这里设置为1.5倍屏幕高效果并不好，所以改成了2倍的屏幕高，此时可以解决上滑时问题。下滑时的问题，可以通过VirtualLayoutManager的runAdjustLayout解决，目前我的处理方式是，给recyclerView设置了OnScrollListener在监听到时下滑时，当滑动超过了一定的距离，就调用runAdjustLayout强制刷新。

目前的解决方式还不够优雅，要是有更好的解决方案，欢迎大家@我。
最后谢谢vlayout的开源，帮我们快速的解决了当前的需求，祝你们越来越棒～～

**Comment by longerian** [comment]
好，到时候上线了在  #255 知会一下，我们也感受下。

**Comment by zsndev** [comment]
@longerian 好哒，到时候我直接在 #255回复就好了吧
