### ISSUE TITLE
StickyLayoutHelper如何判断是否已到顶

### ISSUE THREAD

**Issue by xueyaolive** [alibaba/vlayout#277]

**Comment by longerian** [comment]
试一下这个方法 `public boolean isStickyNow() `

**Comment by longerian** [comment]
还有个办法是判断当前屏幕内第一个显示的item的position 是不是大于 StickyLayoutHelper 里负责的那个item位置

**Comment by xueyaolive** [comment]
- isStickyNow()只能够检测到滑动上去时已经到顶。
- offsetTotal来自 onBindViewHolderWithOffset(ViewHolder holder, int position, int offsetTotal) 
-但如果virtualLayoutManager.scrollToPositionWithOffset(offsetTotal, 0)手动设置上去的就不行了
-方法二：是virtualLayoutManager.findFirstVisibleItemPosition()大于offsetTotal时就说明已经到头部了

**Comment by longerian** [comment]
嗯 本身就是按照方法二的时机来判断是否要到顶的。
