### ISSUE TITLE
onBindViewHolder position问题。

### ISSUE THREAD

**Issue by onionYJK** [alibaba/vlayout#279]
在缓慢滑动的时候会出现position错乱。使用了GridLayoutHelper跟LinearLayoutHelper，GridLayout这块的position会出现0过了就是2，或者连续出现两个2。这样数据显示就错误了。望解决。

**Comment by longerian** [comment]
这个需要更详细的信息，你要排查下adapter返回的位置对不对，是不是出异常了，等等。

**Comment by onionYJK** [comment]
恩，就是adapter返回的position不对。onBindViewHolder#里面的参数position返回不对。

**Comment by longerian** [comment]
可能需要把相关代码贴出来看看。之前没有这样的反馈
onionYJK <notifications@github.com>于2018年1月9日 周二13:49写道：
