### ISSUE TITLE
从1.2.6版本升级到1.2.8版本后无法正常显示

### ISSUE THREAD

**Issue by lazy-ape** [alibaba/vlayout#283]
1.2.6版本的瀑布流在加载更多后总是跳动，升级到1.2.8后所有都无法正常显示了，是使用方法发生变化了吗？

**Comment by longerian** [comment]
TT  我修复的本来就是notifyDataSetChanged引起的问题 可能场景还不太一样

**Comment by lazy-ape** [comment]
但是我从1.2.6升级到1.2.8之后显示不正常了是不是由于notifyDataSetChanged引起的？使用方式大概如下：
```
    private Context mContext;
    private List<ShopcartProductActivityRule> mRules;
    public AddOnProductActAdapter(Context context){
        this.mContext = context;
    }

    public void setData(List<ShopcartProductActivityRule> rules){
        this.mRules = rules;
    }

    @Override
    public int getItemViewType(int position) {
        return AddOnProductActivity.TYPE_ACT;
    }

    @Override
    public LayoutHelper onCreateLayoutHelper() {
        return new SingleLayoutHelper();
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return new ViewHolder(LayoutInflater.from(mContext).inflate(R.layout.layout_addon_product_act,parent,false));
    }

    @Override
    public void onBindViewHolder(ViewHolder holder, int position) {
        if(mRules != null){
            holder.mContainer.removeAllViews();
            for(ShopcartProductActivityRule rule : mRules){
                holder.mContainer.addView(createActText(rule));
            }
        }
    }
```
因为每个页面都会请求几个不同的接口，要保证显示顺序，所以在更新数据的时候都是使用的下面的方式：
```
 mDelegateAdapter.clear();
 mDelegateAdapter.addAdapter(mAddOnProductActAdapter);
 mDelegateAdapter.addAdapter(mProductListDelegateAdapter);
```
在1.2.6这样使用显示时正常的 ，升级到1.2.8后就不行了。
1.2.6显示如下：
![device-2018-01-13-112117](https://user-images.githubusercontent.com/20139666/34902355-d4566eda-f854-11e7-86c9-4df8ff37b3f9.png)
换成1.2.8后显示如下：
![device-2018-01-13-112539](https://user-images.githubusercontent.com/20139666/34902357-e1291dec-f854-11e7-9597-0847bd5e9484.png)
![device-2018-01-13-112638](https://user-images.githubusercontent.com/20139666/34902359-e3baf530-f854-11e7-9f28-127da72fe3a8.png)
也就是换成1.2.8后显示的都是默认布局了  没有再进行数据更新了

**Comment by longerian** [comment]
我主要是改了  OnePlusNLayoutHelper和 StaggeredGridLayoutHelper 相关的两块，你这个看上去是图片不加载了。让我想想

**Comment by longerian** [comment]
和 #295 类似，你确认下，发布了 1.2.11-SNAPSHOT，需要配置仓库
maven { url "http://oss.jfrog.org/oss-snapshot-local/" }
你试一下。
