### ISSUE TITLE
Vlayout本身数据变化刷新问题

### ISSUE THREAD

**Issue by Aries369** [alibaba/vlayout#291]
当我不知道要显示多少种item的时候，先把adapters设置给DelegateAdapter，然后把DelegateAdapter再设置给recyclerView，等数据都请求回来解析好，然后再初始化每个item对应的adapter并把这个adapter添加给adapters，最后调用DelegateAdapter的notifyDataSetChanged方法，结果是页面刷不出来，麻烦大神解答一下这是什么问题，怎么解决呢

**Comment by longerian** [comment]
你看看 DelegateAdapter 的getItemCount 返回个数对不对。

**Comment by Aries369** [comment]
多谢了  我看一下Tangram-Android
