### ISSUE TITLE
第一个页面滑动完之后回来界面他会把当前fragment置顶上去最顶部

### ISSUE THREAD

**Issue by yuwoquan** [alibaba/vlayout#292]
(我录制了视频放在这里：[http://bmob-cdn-15478.b0.upaiyun.com/2018/01/30/7ffdb7fe403e5c4b8062c1e48287510d.mp4)]
我回来的时候手指没有滑动，他自动回滚到最前面

**Comment by lixi0912** [comment]
看下你 切换 Fragment 的时候，是否有处理什么逻辑，没提供代码或伪代码或 pr ，那些大佬很难帮到你

**Comment by longerian** [comment]
检查下是不是重新刷了数据，或者是有什么触发重新布局的操作之类的。

**Comment by yuwoquan** [comment]
调用了onHiddenChanged。来隐藏fragment而已。没有其他的操作

**Comment by longerian** [comment]
你确认下 隐藏的操作是不是有触发清理界面重新布局的可能
