### ISSUE TITLE
升级后出现onBindViewHolder未分发的问题

### ISSUE THREAD

**Issue by xuehuayous** [alibaba/vlayout#295]
升级到1.2.7及以后的版本出现了数据都设置的问题，场景是这样的：
为了扩展RecyclerView加载更多，对DelegateAdapter.Adapter进行了包装，

    public class LoadMoreWrapper extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
        ... ...
        private RecyclerView.Adapter mRealAdapter;
        ... ...
        public LoadMoreWrapper(Context context, RecyclerView.Adapter adapter) {
            this.mContext = context;
           this.mRealAdapter = adapter;
        }
        ... ...
        @Override
        public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
            ... ...
            if (!isFooterType(holder.getItemViewType())) {
                mRealAdapter.onBindViewHolder(holder, position);
            }
        }
        ... ...
    }

发现调用DelegateAdapter的`onBindViewHolder(holder, position)`后就没有向各个Adapter分发onBindViewHolder(holder, position)，经过查看源码发现在1.2.7及以后的版本这个方法变为空的了：

    @SuppressWarnings("unchecked")
    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {

    }

经研究是解决另一位使用者的子Adapter重写`onBindViewHolder(RecyclerView.ViewHolder holder, int position, List<Object> payloads)`不执行问题时引入的。

向作者提个建议，这种问题的解决以及迭代应该是要认真code review的，毕竟很多人在线上使用，而且不了解具体实现的人还不好排查问题。

**Comment by longerian** [comment]
感谢提醒，之前合并了一个pr，改过这方面的逻辑，当时验证没把控好。明天会修复发布一个。

**Comment by longerian** [comment]
发布了 1.2.11-SNAPSHOT，需要配置仓库 maven { url "http://oss.jfrog.org/oss-snapshot-local/" }

同时麻烦review下代码。

**Comment by xuehuayous** [comment]
这样会造成子Adapter的`onBindViewHolder(RecyclerView.ViewHolder holder, int position)`调用两次的问题。

一是，DelegateAdapter的`onBindViewHolder(RecyclerView.ViewHolder holder, int position, List<Object> payloads)`中调用了`super.onBindViewHolder(holder, position, payloads)`，会去调用DelegateAdapter的`onBindViewHolder(RecyclerView.ViewHolder holder, int position)`这时候执行了一次子Adapter的`onBindViewHolder(RecyclerView.ViewHolder holder, int position)`分发。
二是，DelegateAdapter的`onBindViewHolder(RecyclerView.ViewHolder holder, int position, List<Object> payloads)`方法中通过`pair.second.onBindViewHolder(holder, position - pair.first.mStartPosition, payloads)`分发了一次，在每个子Adapter的`onBindViewHolder(holder, position - pair.first.mStartPosition, payloads)`也会调用一次`onBindViewHolder(RecyclerView.ViewHolder holder, int position)`。

这样就造成了子Adapter的`onBindViewHolder(RecyclerView.ViewHolder holder, int position)`调用了两次。

**Comment by longerian** [comment]
ok，我研究下。

**Comment by longerian** [comment]
@xuehuayous 去掉重复调用了，一起review下。

**Comment by xuehuayous** [comment]
很好

**Comment by raulbest** [comment]
1.2.8版本，调用delegateAdapter.notifyDataSetChanged();数据没有刷新，这个怎么解决呢？
