### ISSUE TITLE
LayoutHelper设置背景的问题

### ISSUE THREAD

**Issue by tracymo** [alibaba/vlayout#297]
设置背景用了setLayoutViewBindListener ，这一用才发现afterLayout ， bindLayoutView这两个方法一直在循环走啊，有什么办法可以在静止的时候不让走吗？

**Comment by tracymo** [comment]
你说的解决方案不是很明白  因为bindLayoutView里面调了 layoutView.setBackgroundColor(mBgColor);  
那岂不是只要设置了背景图，哪怕用map标记了,但是还是设置不上啊

**Comment by longerian** [comment]
设置背景色是不会循环的，如果设置背景图，会触发循环布局，所以需要 `setLayoutViewBindListener` 提供一个 listener ，在 listener 里自己判断下图片是不是加载过，加载过就不用再次设置图片了，这样就切断了循环链路。

**Comment by kobeyuandun** [comment]
> 设置背景色是不会循环的，如果设置背景图，会触发循环布局，所以需要 `setLayoutViewBindListener` 提供一个 listener ，在 listener 里自己判断下图片是不是加载过，加载过就不用再次设置图片了，这样就切断了循环链路。

判断了图片是不是加载过，还是会调用 bindLayoutView 方法，导致设置背景不生效！这种方式不行哈，有其他解决方案吗？
