### ISSUE TITLE
能否把adapter分离出来?

### ISSUE THREAD

**Issue by BinarySatan** [alibaba/vlayout#30]
是否能把adapter分离出来, 不用继承你的adapter ?

**Comment by longerian** [comment]
用这个`VirtualLayoutAdapter`?

**Comment by BinarySatan** [comment]
@longerian 这个也不用, 因为项目里面用的别的adapter库,  无法继承VirtualLayoutAdapter

**Comment by longerian** [comment]
当然也是可以，`VirtualLayoutAdapter `做的事情其实很薄，
只要你自己负责往`VirtualLayoutManager`里注入`LayoutHelper`，自己管理好相关逻辑就可以了。
