### ISSUE TITLE
你好，请问在使用OnePlusNLayoutHelper，可否实现这样的效果？

### ISSUE THREAD

**Issue by hyr0318** [alibaba/vlayout#301]
左边的控件是屏幕的2/3的宽度，右边两个垂直显示，宽度是剩余的1/3。 现在demo里面OnePlusNLayoutHelper对应的3个是平分的效果。怎么实现我这样的效果额？

**Comment by longerian** [comment]
可以的  调用 ```setColWeights(new float[](0.667, 0.333))``` ，就可以分配比例了。 @hyr0318
