### ISSUE TITLE
快速滑动图片错位

### ISSUE THREAD

**Issue by fishyuyu** [alibaba/vlayout#303]
Glide.with(mContext).load(itemData.get(position).getImageUrl())
                .skipMemoryCache(true)
                .diskCacheStrategy( DiskCacheStrategy.ALL )
                .into((ImageView) holder.itemView.findViewById(R.id.imgs));

去掉
// .skipMemoryCache(true)
// .diskCacheStrategy( DiskCacheStrategy.ALL ) 
每次网络获取就不会错位，
求助！

**Comment by longerian** [comment]
最好有个demo，我抽空跑一下看看

**Comment by fishyuyu** [comment]
上传了，帮忙看下

**Comment by fishyuyu** [comment]
加入占位符  设置tag  

  if((itemData.get(position).getImageUrl()).equals(((ImageView) holder.itemView.findViewById(R.id.imgs)).getTag(R.id.imgs).toString())) {
            Glide.with(mContext).load(itemData.get(position).getImageUrl())
                .skipMemoryCache(true)
                    .placeholder(R.drawable.no_banner)
                    .error(R.drawable.no_banner)
                .diskCacheStrategy( DiskCacheStrategy.ALL )
                    .into((ImageView) holder.itemView.findViewById(R.id.imgs));
        }

//设置Tag
((ImageView) holder.itemView.findViewById(R.id.imgs)).setTag(R.id.imgs,itemData.get(position).getImageUrl());

//滑动取消请求
 recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
                if (newState == RecyclerView.SCROLL_STATE_DRAGGING || newState == RecyclerView.SCROLL_STATE_SETTLING) {
                    sIsScrolling = true;
                    Glide.with(mContext).pauseRequests();
                } else if (newState == RecyclerView.SCROLL_STATE_IDLE) {
                    if (sIsScrolling == true) {
                        Glide.with(mContext).resumeRequests();

                    }
                    sIsScrolling = false;
                }
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
            }
        });
自己的问题，不好意思，解决了，谢谢！
