### ISSUE TITLE
StickyLayoutHelper  StaggeredGridLayoutHelper 同时使用  StickyLayoutHelper 吸顶 会被覆盖到底下

### ISSUE THREAD

**Issue by 904079904** [alibaba/vlayout#311]
StickyLayoutHelper  StaggeredGridLayoutHelper 瀑布流 同时使用  StickyLayoutHelper 吸顶 会被覆盖到底下
能告诉我一下 解决办法码

**Comment by longerian** [comment]
你看看是不是这个问题 https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md#stickylayouthelper%E9%87%8C%E7%9A%84-item-%E8%A2%AB%E5%85%B6%E4%BB%96-item-%E8%A6%86%E7%9B%96

**Comment by 904079904** [comment]
谢谢你的解答
我还是没弄好
 1、CardView。解决方法是给它设置一个更大的 z 参数（>= 5.0 系统）
我在xml 中cardMaxElevation 设置了 200dp 最大值  还是被覆盖了
，或者检查一下有没有调整 drawingOrder 的地方。 我没有设置 drawingOrder

**Comment by 904079904** [comment]
cardElevation  这个属性要设置为0就可以了  cardElevation 属性会使CardView 在上层  但是设置之后就没阴影了

**Comment by longerian** [comment]
你可以给 StickyLayoutHelper 里的设置一个更大的z轴参数啊
