### ISSUE TITLE
如何禁用上下滚动？

### ISSUE THREAD

**Issue by jinghongjun** [alibaba/vlayout#312]
求解答？

**Comment by longerian** [comment]
什么意思

**Comment by jinghongjun** [comment]
我期待使用vlayout的RecyclerView禁用上下滚动

       谢谢！

**Comment by longerian** [comment]
那你全部展开，会牺牲性能的。调用 `VirtualLayoutManager` 的 ` public void setNestedScrolling(boolean nestedScrolling, int maxMeasureSize)` 方法。
