### ISSUE TITLE
局部数据刷新问题

### ISSUE THREAD

**Issue by lisadan** [alibaba/vlayout#313]
一个recyclerview,有很多adapters,但是我其中一个接口返回数据,我只需要插入n条数据到某个类型的adaper不需要界面其他item重绘view,比如 我有一个item是正在播放的视频,,但是这时候我要添加其他类型item到列表,请教一下 如何做到

**Comment by longerian** [comment]
要获取到那些item的位置，用对应的局部刷新方法调用。最好是我封装一下。 拖了很久了

**Comment by lisadan** [comment]
不能使用对应的subAdapter(helper)去进行刷新数据吗?

**Comment by longerian** [comment]
是的，就是要更新subadapter里的内容，还要同步更新对应的layouthelper信息，是比较麻烦的。
