### ISSUE TITLE
如何获取subadaper中数据在总数据集合的位置

### ISSUE THREAD

**Issue by lisadan** [alibaba/vlayout#317]
1.首先我想通过DelegateAdapter获取某个postion的数据? 有好方法推荐吗?
2. 如何在subadaper中 获取某个数据在总数据列表的位置? 难道要各种相加吗?

**Comment by longerian** [comment]
1. 请参考这个 https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md#%E8%8E%B7%E5%8F%96-delegateadapter-%E9%87%8C%E6%95%B0%E6%8D%AE%E7%9A%84%E7%9B%B8%E5%AF%B9%E4%BD%8D%E7%BD%AE

2.  下面 offsetTotal 就是总的位置
```
protected void onBindViewHolderWithOffset(VH holder, int position, int offsetTotal) {

        }
```
