### ISSUE TITLE
上下滑动卡顿问题

### ISSUE THREAD

**Issue by controlFate** [alibaba/vlayout#324]
经过多次测试，发现添加的adapter超过5个就会滑动时卡顿，四个以内滑动流畅，大神这个怎么解决你

**Comment by longerian** [comment]
卡顿可能是你组件item太复杂了，或者复用有问题，你看看有没有相关日志信息

**Comment by controlFate** [comment]
经过多次测试，发现是item布局太复杂了，某个item布局，嵌套了tablayout+viewpage的功能，请问大神，这个怎么解决卡顿的问题，

**Comment by longerian** [comment]
这只能精简优化了。   减少耗时操作。

**Comment by controlFate** [comment]
终于解决了，对于布局复杂的，通过滑动状态来判断是否加载itemView的初始化操作，我设置停止滑动才让itemView的控件做初始化和加载数据，加载图片，设置viewpage的adapter的等等一些耗时操作。才解决了滑动卡顿的问题，问题是解决了，但感觉不是完美解决方案，大神有什么建议吗，精简优化已经该优化的都优化了，主要业务要求布局确实复杂许多。

**Comment by longerian** [comment]
其实也没有什么特别的方案，主要看你的业务场景了，比如是否可以反过来，在viewpage里的每一页里用vlayout，还有就是view的层级可以简化，扁平化，用自定义的控件。还有可以加入异步流程，先占位，异步加载图片数据等。
