### ISSUE TITLE
关于卡顿问题

### ISSUE THREAD

**Issue by WillLiaowh** [alibaba/vlayout#329]
当 hasConsistItemType=true 的时候，不同的 DelegateAdapter.Adapter 之间返回相同的 itemType 的时候，他们之间是可以复用的。
按这里的说法，例如我有两个Adapter,一个是GridAdapter，对应Item布局为gird_item,一个是LinerAdapter,对应布局是linear_item，两个adapter都不复写getItemViewType,即返回默认itemType为0。
设置hasConsistItemType=true，设置复用池viewPool.setMaxRecycledViews(0, 20)，应该是会复用的,但是实际会卡顿？

**Comment by longerian** [comment]
en   这一块会比较麻烦，建议全部都写成不一样的type，就没有这些繁琐的问题了。
