### ISSUE TITLE
关于数据刷新的问题

### ISSUE THREAD

**Issue by raulbest** [alibaba/vlayout#334]
我往RecycleView中添加了几个不同样式的Adapter（继承于DelegateAdapter.Adapter）,现在请求到数据之后，需要全部刷新，我直接调用的delegateAdapter.notifyDataSetChanged(),数据没有刷新出来，然后我用了最笨的方法，将List<DelegateAdapter.Adapter> adapters中的adapter遍历出来，逐个调notifyDataSetChanged刷新数据，这样数据就出来了。请问delegateAdapter.notifyDataSetChanged()这个调用是否正确？或者有没有更好的办法来刷新数据，我用的版本是1.2.13，谢谢！

**Comment by longerian** [comment]
目前是这样的。

**Comment by raulbest** [comment]
这个后续有优化的打算么？总感觉这种for循环刷新数据有点怪怪的

**Comment by longerian** [comment]
确实很怪，我抽空看看，主要是我们不是直接使用这个delegateAdapter的，我们自己写了一个库叫 tangram-android  ，间接操作它。
