### ISSUE TITLE
吸顶view被瀑布流遮挡

### ISSUE THREAD

**Issue by lazy-ape** [alibaba/vlayout#337]
如题，吸顶的View，被下部的瀑布流遮挡住了，没有被其他的项遮挡，滑动到其他地方都是正常的，找了半天没查出什么原因。
![1523937196122](https://user-images.githubusercontent.com/20139666/38847860-5ef85122-4236-11e8-939c-4ac9d8d988aa.jpg)
![1523937226324](https://user-images.githubusercontent.com/20139666/38847861-5f36d6fe-4236-11e8-926d-e103be80b34f.jpg)

**Comment by longerian** [comment]
https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md#stickylayouthelper%E9%87%8C%E7%9A%84-item-%E8%A2%AB%E5%85%B6%E4%BB%96-item-%E8%A6%86%E7%9B%96 你看看FAQ
