### ISSUE TITLE
如何支持HORIZONTAL_SCROLL_LAYOUT

### ISSUE THREAD

**Issue by blackbluezx** [alibaba/vlayout#34]
Demo中是HORIZONTAL_SCROLL_LAYOUT并未实现，是需要自己基于BaseLayoutHelper实现一套吗，还是目前已经支持，只需要设置某个参数即可？

**Comment by longerian** [comment]
没有相关实现

**Comment by BinarySatan** [comment]
后期准备加入 HORIZONTAL_SCROLL_LAYOUT 吗

**Comment by longerian** [comment]
建议一起来搞

**Comment by fengdexunmi** [comment]
@longerian 楼主，你好，这里支持横向可滚动的布局，可否直接用横向的RecycleView，不知道你们打算如何实现横向可滚动的布局，我使用vlayout的实现横向滚动布局就是直接添加横向RecycleView，就像你添加ViewPager一样。

**Comment by longerian** [comment]
是的，我们项目里就是用 viewpager或者横向的 recyclerView 来实现横向滚动的。

**Comment by longerian** [comment]
没什么大问题，还可以共享一个复用池。
