### ISSUE TITLE
建议VirtualLayoutAdapter改为接口

### ISSUE THREAD

**Issue by zouzhenglu** [alibaba/vlayout#341]
RT，把VirtualLayoutAdapter还原为系统的adapter，库中的调用改为interface，这样使用的时候，就不会因为使用了这个库而不得不去修改 原有的BaseAdapter

**Comment by MikeAfc** [comment]
建议考虑使用成本，BaseAdapter改一下父类比只给interface让你自己实现内部逻辑还是轻松多了
