### ISSUE TITLE
vlayout与部分下拉刷新控件冲突

### ISSUE THREAD

**Issue by github-zhanghang** [alibaba/vlayout#343]
部分下拉刷新控件，例如XRecyclerView，vlayout会把下拉刷新的头部当成一个item来处理。
例如使用GridLayoutHelper时，下拉刷新区域会变成Grid的第一个item，Grid的最后一个Item会被挤到下一个Adapter中
![screenshot_2018-04-28-16-56-09-108_com zhanghang](https://user-images.githubusercontent.com/19282135/39394769-803a044a-4b08-11e8-8306-14ea5af37409.png)

**Comment by MikeAfc** [comment]
建议使用不侵入Adapter的下拉方案，如 https://github.com/scwang90/SmartRefreshLayout
