### ISSUE TITLE
DelegateAdapter.simpleAdapter代码错误

### ISSUE THREAD

**Issue by gzxg1234** [alibaba/vlayout#347]
调用DelegateAdapter.simpleAdapter生成adapter，下面onCreateLayoutHelper处有问题
<pre>
<code>
static class SimpleViewAdapter extends Adapter<RecyclerView.ViewHolder> {

        private View mView;

        private LayoutHelper mLayoutHelper;

        public SimpleViewAdapter(@NonNull View view, @NonNull LayoutHelper layoutHelper) {
            this.mView = view;
            this.mLayoutHelper = layoutHelper;
        }

        public SimpleViewAdapter(@NonNull View view) {
            this(view, new SingleLayoutHelper());
        }

        @Override
        public LayoutHelper onCreateLayoutHelper() {
            //应该返回mLayoutHelper
            return new SingleLayoutHelper();
        }

        @Override
        public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            return new SimpleViewHolder(mView);
        }

        @Override
        public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {

        }

        @Override
        public int getItemCount() {
            return 1;
        }
    }
</code>
</pre>

**Comment by MikeAfc** [comment]
已修复
