### ISSUE TITLE
Logo/icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [alibaba/vlayout#355]
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by MikeAfc** [comment]
Thank you. We're pretty happy with the project logo! If you have any ideas or improvement suggestions, definitely let us know!
