### ISSUE TITLE
notifyItemChanged不刷新

### ISSUE THREAD

**Issue by lazy-ape** [alibaba/vlayout#362]
继承的DelegateAdapter.Adapter，使用的StaggeredGridLayoutHelper，调用了notifyItemChanged刷新单项数据，但是没有效果，onBindViewHolder也没有被调用，版本是1.2.6

**Comment by lazy-ape** [comment]
刚更新了一下版本2.1.15，还是无法刷新数据

**Comment by MikeAfc** [comment]
参考 #334
