### ISSUE TITLE
加载图片后卡顿严重

### ISSUE THREAD

**Issue by shijia109** [alibaba/vlayout#374]
与glide一起使用的时候卡顿特别严重，尤其华为p20上，卡的跟千元机似的，使用RecyclerView的adapter时加载大图滑动也不会卡，使用多个自定义adapter继承自DelegateAdapter.Adapter()就出奇的卡，不加载图片会感觉不到卡，感觉Vlayout还有比较严重的性能问题没有解决，demo里也根本没有图片加载所以感觉不到卡，实际场景中不可能不加载图片，不知道贵团队了不了解这个问题，既然是阿里出品，为什么淘宝那么复杂的页面都不卡，我们这简单的一行两三个图片的布局就卡的不行了？不要说布局优化问题，就一个图片两行文字，有啥可优化的，不存在布局复杂问题

**Comment by MikeAfc** [comment]
请参照faq解决，https://github.com/alibaba/vlayout/blob/master/docs/VLayoutFAQ.md#%E7%BB%84%E4%BB%B6%E5%A4%8D%E7%94%A8%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by shijia109** [comment]
写的这些压根没有好吗，我吧所有adapter合并成一个，把所有类型viewpool搞成100也一样，第一次滑动会很卡，滑到底再划就不卡了，这算复用问题？麻烦你们正视自己的问题，不要把开发者当白痴

**Comment by shijia109** [comment]
拜托你们搞个华为p20做测试，比小米2s都卡，你们对华为兼容有问题

**Comment by shijia109** [comment]
爱解决不解决，不敢正视自己问题的人，老子反馈还嫌浪费心情呢

**Comment by MikeAfc** [comment]
附上你在其他项目提的issue，供后来人参考，语言风格奇特，https://github.com/scwang90/SmartRefreshLayout/issues/605

**Comment by shijia109** [comment]
最近一共提了两个issue，没一个解决我的问题然后直接close掉，第一个给了截图依然回复说不能复现选择不解决，你们这个也是，完全按照demo写的，确保集成没问题，华为p20特别卡，但是你们 一点不重视我提的问题，让我看最基本的文档，这是尊重人的表现吗？

**Comment by shijia109** [comment]
敢问一句，你敢保证你在华为p20上做了图片加载测试吗？重视用户反馈的bug是开发人员最基本的修养，你们都做到了吗

**Comment by huclengyue** [comment]
别人开源项目，并没有义务帮你解决BUG，也没有强迫你用这个框架，都知道是开发者为何不自己解决。你这态度，难道你是给作者付费解决问题的？或者你给作者邮递个P20我估计他可以解决P20的问题。

---
在提醒一下 这是开源项目。

**Comment by shijia109** [comment]
既然开源，为啥不重视别人提的意见，提意见也是为了越来越好，受益的是所有使用它的人，拒绝接受意见，还要issue干什么？你可以选择无视。我当啥也没说

**Comment by shijia109** [comment]
开源者没义务解决bug，我自然没义务提供测试机，另外，我们早就不用vlayout了，我们团队自己研发了一套性能更好的库，valyout好坏已经跟我们无关了。不同团队对性能要求不一样，你们觉得不卡，也许我们就是不通过测试

**Comment by appledong** [comment]
和Glid的兼容性确实不好，目前我们用的这套框架上下滑动确实是卡顿抖动，目前我们屏蔽了滑动加载图片滑动结束在加载，好了很多，但是这样就牺牲用户体验了
