### ISSUE TITLE
LayoutHelper在初始化时的设置，和数据变化时的再次设置。

### ISSUE THREAD

**Issue by Joinfeng** [alibaba/vlayout#386]
初始化的时候，如果用了LinearLayoutHelper，然后在数据更新之后，要想设置其他的helper，则只有前者会起作用，后者的设置不生效。结论，前后需要统一的helper。

**Comment by tmexcept** [comment]
不知道你怎么设置的其他的helper？你可以尝试清空adapters之后重新添加重设置helper之后的adapter
