### ISSUE TITLE
GridLayoutHelper问题

### ISSUE THREAD

**Issue by chenzixue** [alibaba/vlayout#40]
连续添加两个类型为GridLayoutHelper的Adapter，当下方的Adapter使用GridLayoutHelper的setSpanSizeLookup()方法动态设置item所占的列数时，下方Adapter的布局会混乱。

**Comment by longerian** [comment]
ok 提供一下详细代码看看

**Comment by chenzixue** [comment]
https://github.com/chenzixue/VlayoutTest/tree/master
在这里

**Comment by longerian** [comment]
这个是你使用有问题，public int getSpanSize(int position)的position是DelegateAdapter里的位置，而在实现里你用这个position去GridAdapter里取数据，导致数组越界。
