### ISSUE TITLE
StickyLayoutHelper置顶时控件宽度不会重新绘制

### ISSUE THREAD

**Issue by SunxiaoyaoHHL** [alibaba/vlayout#404]
吸顶时更改Textview中的文字，宽度不会改变
<RelativeLayout
    android:background="@color/white"
    xmlns:android="http://schemas.android.com/apk/res/android" 
    android:layout_width="match_parent"
    android:layout_height="50dp">

            <TextView
                android:layout_centerInParent="true"
                android:id="@+id/txt_top"
                android:text="置顶"
                android:gravity="center"
                android:textColor="@color/white"
                android:background="@color/black"
                android:layout_width="wrap_content"
                android:layout_height="match_parent" />

</RelativeLayout>

**Comment by Mike-bel** [comment]
@SunxiaoyaoHHL 
我也遇到过这个问题，吸顶状态下更改 view 的 layoutParams 属性，虽然值确实变了，但是 UI 不会刷新，解决办法就是使用 sub adapter 的 notify 刷新机制来处理。

算是变相解决这类问题吧。
