### ISSUE TITLE
 GridLayoutHelper的setSpanSizeLookup()与AutoExpand属性的冲突

### ISSUE THREAD

**Issue by totond** [alibaba/vlayout#42]
GridLayoutHelper gridLayoutHelper = new GridLayoutHelper(4);
        gridLayoutHelper.setAutoExpand(true);
        gridLayoutHelper.setSpanSizeLookup(new GridLayoutHelper.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                if (position > 13) {
                    return 2;
                }else {
                    return 1;
                }
            }
        });

这样会导致最后一个Item的大小扩展之后再乘2，
![图](http://i.imgur.com/6BvDvGR.png)

**Comment by longerian** [comment]
ok。这个好解决，处理一下

**Comment by longerian** [comment]
在两者冲突的情况下，只支持setSpanSizeLookup()
