### ISSUE TITLE
用vlayout设置的多布局，页面底部的横向recyclerview的adapter因为页面太长会被清空？

### ISSUE THREAD

**Issue by tmxd09887** [alibaba/vlayout#427]
adapters.add(adapterSimilar);
delegateAdapter.setAdapters(adapters);

adapterSimilar是页面底部的recycerlview的adapter，如果页面不长，是正常的。如果页面很长，滚动到底部，再点击item，发现adapter被清空了。是不是因为adapter数据错乱了?

用的是com.alibaba.android:vlayout:1.2.8

**Comment by lixi0912** [comment]
提供的信息与当前问题并没有太大的帮助，建议提供更完善的信息或描述(最好有个 repo)，目测使用不当
