### ISSUE TITLE
STICKY_LAYOUT在例子中遇到的问题

### ISSUE THREAD

**Issue by fengdexunmi** [alibaba/vlayout#43]
打开vlayout的example中的VLayoutActivity，发现position为30的布局是一个吸附在底部的STICKY_LAYOUT,滑动整个视图至这个position为30的布局在屏幕中央位置附近，此时点击Jump Position的输入框，弹出系统键盘，输入比较前的位置下标（比如1），点击jump视图滑动到指定的位置，这个时候按返回键系统键盘隐藏，但是position为30的STICKY布局没有回到底部位置，仍然停留在屏幕中央的位置。截图如下：
### position为30的布局滑动至屏幕中央
![screenshot_2017-04-13-15-44-27](https://cloud.githubusercontent.com/assets/2813239/24995168/59277fe6-2060-11e7-9547-69b046ad8aa8.png)

### 跳转至比较前的位置，按下返回键，position为30的布局没有变化
![screenshot_2017-04-13-15-44-36](https://cloud.githubusercontent.com/assets/2813239/24995253/c8e2cda4-2060-11e7-8c75-2d1792320463.png)

![screenshot_2017-04-13-15-44-40](https://cloud.githubusercontent.com/assets/2813239/24995223/a08f8392-2060-11e7-85b2-e663eaad7020.png)

**Comment by longerian** [comment]
这个需要外部页面去监听键盘状态，然后刷新页面，这个逻辑不宜在sdk内部做。
我在VLayoutActivity里提供了类似的demo。
