### ISSUE TITLE
GridLayoutHelper中spanCount和size问题

### ISSUE THREAD

**Issue by Gofar** [alibaba/vlayout#437]
GridLayoutHelper设置spanCount为2，当item数量为3（或其他不为2的倍数的数值），最后一个item会占据一整行，如何处理这个问题？
![TIM截图20190402141925](https://user-images.githubusercontent.com/8542718/55380330-76c7de00-5552-11e9-8a66-3f2e8778e8d9.png)

**Comment by lixi0912** [comment]
使用 `GridLayoutHelper.setAutoExpand(boolean isAutoExpand)` 方法

**Comment by Gofar** [comment]
好的，多谢
