### ISSUE TITLE
meaning of hasConsistItemType ?

### ISSUE THREAD

**Issue by softrice** [alibaba/vlayout#47]
问题一：hasConsistItemType的意义是否是指adapters内的itemType是否是属于一个集合,即不同的子adapter的itemType都能复用.
问题二:如果我上述理解正确,当hasConsistItemType为false的时候,RecycledViewPool限制的是什么?

**Comment by longerian** [comment]
为了保持对外接口的统一和简洁，itemType是由每一个`DelegateAdapter.Adapter`的`public int getItemViewType(int position)`方法来决定。

当hasConsistItemType=true的时候，不论是不是属于同一个子adapter，相同类型的item都能复用。表示它们共享一个类型。
当hasConsistItemType=false的时候，不同子adapter之间的类型不共享，因此内部会在`DelegateAdapter.Adapter`的`public int getItemViewType(int position)`方法返回类型之后做进一步处理，RecyclerView看到的是不同的type。

所以你的问题一理解是对的，问题二和这个参数无关，RecycledViewPool的限制不限制仍然与默认的一样，一个类型的item默认最大复用池大小是5。可以单独修改它。

**Comment by longerian** [comment]
当 hasConsistItemType = false的时候，实现颇为巧妙，特意发布了一篇文章：[Pairing Function —— vlayout 中使用数学的小场景](http://pingguohe.net/2017/05/03/the-beauty-of-math-in-vlayout.html)， 你可以参考一下。

**Comment by softrice** [comment]
恩 感谢~

**Comment by excitedhaha** [comment]
> @softrice 当 hasConsistItemType = false的时候，实现颇为巧妙，特意发布了一篇文章：[Pairing Function —— vlayout 中使用数学的小场景](http://pingguohe.net/2017/05/03/the-beauty-of-math-in-vlayout.html)， 你可以参考一下。

妙啊
