### ISSUE TITLE
作者是否有概念抄袭以及其他一些东西抄袭的嫌疑。

### ISSUE THREAD

**Issue by youngsoft** [alibaba/vlayout#5]
初看这个是android的一个布局体系结构。然后名称还是叫Tangram。但是文中的一些介绍和其中的一些理念和本人的iOS界面布局库的swift版本：[TangramKit](https://github.com/youngsoft/TangramKit)库是一样的。先不说实现的抄袭，在理念上和命名上是否作者有抄袭的嫌疑。。

**Comment by WangChangQin** [comment]
我拿出了小板凳。

**Comment by a247124718** [comment]
吃瓜

**Comment by mrchenmo** [comment]
里皮

**Comment by JacksonTian** [comment]
特意去内网看了gitlab上的commit记录，（vlayout）的第一条commit最早于2015年10月24日（1024）提交。TangramKit的最早提交记录是2016年10月27日。光从这个就可以判定并没有抄袭的嫌疑。

做类似的事情，名字必然有一定概率相似相似。。

吃瓜群众可以退散了。

**Comment by chenmol** [comment]
@gaosboy Tangram-AppContainer（用来承载业务逻辑的后台容器，未来半年内会开）这个是否有具体时间表？

**Comment by longerian** [comment]
@chenmol 预计明年3月份左右，还在准备中。

**Comment by chenmol** [comment]
@longerian 一直非常期待AppContainer，开源有进展了么？

**Comment by MikeAfc** [comment]
@chenmol 目前进展比较慢，估计要5月份了

**Comment by MikeAfc** [comment]
@chenmol 目前进展比较慢，估计要5月份了
