### ISSUE TITLE
GridLayoutHelper数量不能整除时，默认显示存在BUG

### ISSUE THREAD

**Issue by caiyoufei** [alibaba/vlayout#50]
[
![1](https://cloud.githubusercontent.com/assets/11989916/25660214/d22be5de-303d-11e7-9f0b-44858de1b6d9.png)
![2](https://cloud.githubusercontent.com/assets/11989916/25660215/d26d4236-303d-11e7-8389-2d2aac530fcd.png)

](url)

**Comment by longerian** [comment]
你想要怎么显示，这是异常情况下的两种策略，要么撑开，要么留空白区域

**Comment by caiyoufei** [comment]
滑动过程中重用时会在这两个状态切换，不是应该固定一种嘛，或者可以配置

**Comment by caiyoufei** [comment]
还要另外一个BUG，就是如图二所示，如果不采用setHGap设置间距而不采用setWeights方法的时候，不能整除时会导致上下两行的间距不一致

**Comment by 5peak2me** [comment]
@caiyoufei 印象中可以使用layoutHelper.setAutoExpand(false);来规避你所指示的第一张图的情况。你可以看下

**Comment by longerian** [comment]
第一张图是默认情况，即layoutHelper.setAutoExpand(true);
第二张图是layoutHelper.setAutoExpand(false);

如果你在滑动过程中，同一个区域出现变化，检查一下你是否动态改了这个属性。

**Comment by longerian** [comment]
@caiyoufei setHGap设置的是水平间距，是左右之间的间距，不是上下之间

**Comment by caiyoufei** [comment]
@5peak2me 我不是说的上下间距，我说的左右间距，如果第二行不足4个，采用setHGap设置，会出现间距不一样的情况

**Comment by caiyoufei** [comment]
@longerian 第一张图是进入列表默认显示的图片，第二张图是滑动列表后回到原来的地方出现的情况，没有设置过setAutoExpand属性，只是滑动了一下列表而已

**Comment by longerian** [comment]
@caiyoufei  第二个问题我知道了，确实有问题。
