### ISSUE TITLE
设置不同的 adapter，adapter 不会正常更新。

### ISSUE THREAD

**Issue by notHide** [alibaba/vlayout#53]
简而言之，现在有 3 个 adapter，分别叫 A1 A2 B1。    
A1 和 A2 是同一个类型，但是各自都是通过 new 创建出来的，B1 是另外一个类型。    
（三个 Adapter 没有互相引用，也没有 static 变量）
步骤如下：    
1. 通过 .setAdapters() 先设置 A1，在 onBindViewHolder() 里面设置了点击事件。    
2. 给 A1 添加 2 条数据，刷新界面。    
3. 再通过 .setAdapters() 设置 B1。    
4. 再通过 .setAdapters() 设置 A2，在 onBindViewHolder() 里面设置了点击事件。    
5. 把 A1 的数据清空，然后给 A2 添加 2 条不同的数据（A1 和 A2 的集合和数据是各自 new 出来的）。    
4. 调用 A2 的方法刷新界面。    （Log 显示添加数据操作是在 A2 里，界面也是显示的 A2 的内容）    
5. 点击数据，此时点击无反应！（Log 显示，点击是触发在 A1 里面的）    
    
设置的是 A2，数据也是 A2 的，但是点击是在 A1 里面！就是这个情况……

**Comment by longerian** [comment]
因为view是复用的 ，你会不会在点击响应里引用了A1的资源。要传代码看看 或者你自己 先debug一下

**Comment by notHide** [comment]
@longerian 找到原因了，果然是复用的问题，因为 A1 的点击事件是匿名的，匿名类会隐式引用外部类，所以造成 A1 内存泄露了。目前已经解决，感谢！
