### ISSUE TITLE
关于布局全屏的问题

### ISSUE THREAD

**Issue by ailuoyi** [alibaba/vlayout#54]
不好意思，打扰一下：
我通过：
delegateAdapter.addAdapter(new LoadingAdapter());
添加一个LoadingAdapter。LoadingAdapter的布局xml宽高都是match_parent。但是显示出来效果如下：
![image](https://cloud.githubusercontent.com/assets/20197174/25788963/a356a0be-33df-11e7-90d0-fcc1940dc5ce.png)
如上图，红色区域并未铺满屏幕。
初次接触vLayout，如有打扰，多多包涵

**Comment by longerian** [comment]
检查一下你的adapter里有没有限制item的高度
