### ISSUE TITLE
Stick

### ISSUE THREAD

**Issue by jiangwei18** [alibaba/vlayout#55]
StickLayout下面紧跟StaggeredLayout时，StaggeredLayout里面的item会折叠卡顿的效果

**Comment by jiangwei18** [comment]
https://github.com/jiangwei1517/VlayoutDemo

MainActivity    line:120

    /*
        天猫历史
        有问题StaggeredGridLayoutHelper上面套上一个StickyLayout时会UI卡顿
     */
    private void tianMaoHistory(List<DelegateAdapter.Adapter> adapters) {

//        mStickyLayoutHelperHistory.setMarginBottom(20);
//        adapters.add(new CommonSticky(this, mStickyLayoutHelperHistory) {
//            @Override
//            public void onBindViewHolder(CommonStickyViewHolder holder, int position) {
//                holder.tv.setText("历史纪录");
//            }
//        });

        //设置瀑布流布局
        StaggeredGridLayoutHelper staggeredGridLayoutHelper = new StaggeredGridLayoutHelper(2, 10);
        staggeredGridLayoutHelper.setMarginBottom(30);
        adapters.add(new StaggeredAdapter(this, staggeredGridLayoutHelper, mTianMao.history.size()) {
            @Override
            public void onBindViewHolder(StaggeredViewHolder holder, int position) {
                holder.llMain.getLayoutParams().height = mTianMao.history.get(position).height;
                holder.llMain.getLayoutParams().width = 400;
                Glide.with(MainActivity.this).load(mTianMao.history.get(position).imgUrl).dontAnimate().into(holder.iv);
            }
        });
    }

**Comment by longerian** [comment]
1.0.9 里解决了。 在 #122 里记录。
