### ISSUE TITLE
FloatLayout

### ISSUE THREAD

**Issue by jiangwei18** [alibaba/vlayout#56]
//设置浮动布局
        FloatLayoutHelper floatLayoutHelper = new FloatLayoutHelper();
        //设置初始位置
        floatLayoutHelper.setDefaultLocation(20,250);

        adapters.add(new FloatAdapter(this, floatLayoutHelper) {
            @Override
            public void onBindViewHolder(FloatViewHolder holder, int position) {

            }
        });
这个floatLayout必须滚到adapters的位置上，才能滚动。

项目：https://github.com/jiangwei1517/VlayoutDemo
MainActivity中  103行将tianMaoShopping放最后会划不动购物车
        tianMaoShopping(adapters);

        tianMaoSearchView(adapters);

        tianMaoBinnerView(adapters);

        tianMaoHotView(adapters);

        tianMaoTodayHots(adapters);

        tianMaoHistory(adapters);

**Comment by longerian** [comment]
我抽空看一下

**Comment by longerian** [comment]
如你所述调整了一下代码位置，并没有出现你说的问题，从原理上来讲滑动跟顺序也没有关系。

```
        tianMaoSearchView(adapters);

        tianMaoBinnerView(adapters);

        tianMaoHotView(adapters);

        tianMaoTodayHots(adapters);

        tianMaoHistory(adapters);

        tianMaoShopping(adapters);
```
