### ISSUE TITLE
使用GridLayoutHelper 出现日志死循环输出

### ISSUE THREAD

**Issue by jameqian** [alibaba/vlayout#57]
// 动态设置列数
        int tempSize = list.size();
        int CRITICAL_COLUMNS_FOUR = 4;
        int CRITICAL_COLUMNS_FIVE = 5;
        int spanCount = CRITICAL_COLUMNS_FOUR;
        if (tempSize > 8 || tempSize == 5) {
            spanCount = CRITICAL_COLUMNS_FIVE;
        } else if (tempSize > 5 && tempSize <= 8) {
            spanCount = CRITICAL_COLUMNS_FOUR;
        }
        GridLayoutHelper helperFunc = new GridLayoutHelper(spanCount);
        helperFunc.setBgColor(getResources().getColor(R.color.white));
        helperFunc.setPadding(0, 0, 0, getResources().getDimensionPixelSize(R.dimen
                .public_space_28px));
        if (btnsBackGroundData != null && !btnsBackGroundData.isEmpty()) {
            helperFunc.setLayoutViewBindListener(new BaseLayoutHelper.LayoutViewBindListener() {
                @Override
                public void onBind(final View layoutView, BaseLayoutHelper baseLayoutHelper) {
                    //背景图片
                    mImageLoader.loadImage(SuningUrl.IMAGE_SUNING_CN_CMS + btnsBackGroundData.get
                                    (0).getPicUrl(),
                            new ImageLoader.OnLoadCompleteListener() {
                                @Override
                                public void onLoadComplete(Bitmap bitmap, View view, String url,
                                                           ImageLoadedParams loadedParams) {
                                    layoutView.setBackgroundDrawable(new BitmapDrawable(mContext
                                            .getResources(), bitmap));
                                }
                            });
                }
            });
        }
        adapters.add(new FuncBtnAdapter(mContext, helperFunc, mImageLoader, list));

public class FuncBtnAdapter extends DelegateAdapter.Adapter<FuncBtnViewHolder> {
    private static final String TAG = "FuncBtnAdapter";
    private Context mContext;
    private LayoutHelper mLayoutHelper;
    private VirtualLayoutManager.LayoutParams mLayoutParams;
    private List<HomeModelContent> mList;
    private ImageLoader mImageLoader;

    public FuncBtnAdapter(Context context, LayoutHelper layoutHelper, ImageLoader imageLoader, List<HomeModelContent> list) {
        this(context, layoutHelper, imageLoader, list, new VirtualLayoutManager.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT));
    }

    public FuncBtnAdapter(Context context, LayoutHelper layoutHelper, ImageLoader imageLoader, List<HomeModelContent> list,
                          @NonNull VirtualLayoutManager.LayoutParams layoutParams) {
        this.mContext = context;
        this.mLayoutHelper = layoutHelper;
        this.mList = list;
        this.mImageLoader = imageLoader;
        this.mLayoutParams = layoutParams;
    }

    @Override
    public int getItemCount() {
        if (mList == null) {
            return 0;
        }
        return mList.size();
    }

    @Override
    public int getItemViewType(int position) {
        return HomeConstants.VIEW_TYPE_FUNCTION_BTN;
    }

    @Override
    public LayoutHelper onCreateLayoutHelper() {
        return mLayoutHelper;
    }

    @Override
    public FuncBtnViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        SuningLog.d(TAG, "onCreateViewHolder----------------------------------------");
        return new FuncBtnViewHolder(LayoutInflater.from(mContext).inflate(R.layout.activity_home_functions_item, parent, false));
    }

    @Override
    public void onBindViewHolder(FuncBtnViewHolder holder, int position) {
        SuningLog.d(TAG, "onBindViewHolder----------------");
        if (mList == null || mList.isEmpty() || mList.size() <= position) {
            return;
        }
        if (mLayoutParams != null) {
            holder.itemView.setLayoutParams(new VirtualLayoutManager.LayoutParams(mLayoutParams));
        }

    }

    @Override
    protected void onBindViewHolderWithOffset(FuncBtnViewHolder holder, int position, int offsetTotal) {
        final HomeModelContent content = mList.get(position);
        if (content != null) {
            mImageLoader.loadImage(SuningUrl.IMAGE_SUNING_CN_CMS + content.getPicUrl(), holder.imageView);
            holder.tvName.setText(content.getElementName());
            holder.itemView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (!TextUtils.isEmpty(content.getLinkUrl())) {
                        PageRouterParase.getInstance().gotoDestPage(mContext,
                                content.getLinkUrl());
                        SuningLog.d(TAG, "Function: " + content.getTrickPoint());
                        StatisticsUtil.onCmsClick(content.getTrickPoint());
                    }
                }
            });
        }
    }
}
控制台出现：

05-09 21:03:01.691 22410-22410/com.suning.mobile.msd W/View: requestLayout() improperly called by com.suning.mobile.msd.common.custom.view.vlayout.l{fd4e418 V.ED..... ......ID 0,1100-1080,1348} during layout: running second layout pass
05-09 21:03:01.695 22410-22410/com.suning.mobile.msd W/View: requestLayout() improperly called by com.suning.mobile.msd.common.custom.view.vlayout.l{fd4e418 V.ED..... ........ 0,1100-1080,1348} during second layout pass: posting in next frame
05-09 21:03:01.708 22410-22410/com.suning.mobile.msd W/View: requestLayout() improperly called by com.suning.mobile.msd.common.custom.view.vlayout.l{fd4e418 V.ED..... ......ID 0,1100-1080,1348} during layout: running second layout pass
05-09 21:03:01.712 22410-22410/com.suning.mobile.msd W/View: requestLayout() improperly called by com.suning.mobile.msd.common.custom.view.vlayout.l{fd4e418 V.ED..... ........ 0,1100-1080,1348} during second layout pass: posting in next frame
05-09 21:03:01.725 22410-22410/com.suning.mobile.msd W/View: requestLayout() improperly called by com.suning.mobile.msd.common.custom.view.vlayout.l{fd4e418 V.ED..... ......ID 0,1100-1080,1348} during layout: running second layout pass
05-09 21:03:01.728 22410-22410/com.suning.mobile.msd W/View: requestLayout() improperly called by com.suning.mobile.msd.common.custom.view.vlayout.l{fd4e418 V.ED..... ........ 0,1100-1080,1348} during second layout pass: posting in next frame
05-09 21:03:01.742 22410-22410/com.suning.mobile.msd W/View: requestLayout() improperly called by com.suning.mobile.msd.common.custom.view.vlayout.l{fd4e418 V.ED..... ......ID 0,1100-1080,1348} during layout: running second layout pass
05-09 21:03:01.745 22410-22410/com.suning.mobile.msd W/View: requestLayout() improperly called by com.suning.mobile.msd.common.custom.view.vlayout.l{fd4e418 V.ED..... ........ 0,1100-1080,1348} during second layout pass: posting in next frame

**Comment by longerian** [comment]
LayoutViewBindListener 是在布局过程中调用的，这个回调里加载完图片会触发布局过程，这样就循环了。你需要在绑定图片前判断一下是否加载完毕，加载完毕就不用重复加载图片了。这样就可以避免。

**Comment by longerian** [comment]
这个逻辑在1.0.6 sdk内部做了简单的封装，设置`DefaultLayoutViewHelper` 然后在图片加载成功的时候调用`onBindViewSuccess(View layoutView, String id)`方法即可。

**Comment by mattaojie** [comment]
请问onBindViewSuccess这个方法要在哪里调用，我不知道图片什么时候加载成功，请指教

**Comment by mattaojie** [comment]
你好，我在LayoutViewBindListener中使用9patch图片作为背景，但是不知道图片加载成功的回调怎么设置，所以就在onBind方法里设置了约束条件进行判断，如果超过一定的值就不再绑定，但是在达到约束条件后9patch图背景就没有了，请问有什么解决办法吗？

**Comment by mattaojie** [comment]
@longerian  你好，我在LayoutViewBindListener中使用9patch图片作为背景，但是不知道图片加载成功的回调怎么设置，所以就在onBind方法里设置了约束条件进行判断，如果超过一定的值就不再绑定，但是在达到约束条件后9patch图背景就没有了，请问有什么解决办法吗？
