### ISSUE TITLE
滑动闪退

### ISSUE THREAD

**Issue by kimi007117** [alibaba/vlayout#6]
上下滑动会闪退，support的RecyclerView版本为：25.1.1

**Comment by longerian** [comment]
我大概知道，我查一下

**Comment by longerian** [comment]
与 #1 重复，recyclerview 底层有 bug，官方未修复，我再跟进查一下。

详情参考[这里](https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&groupby=&sort=&id=230295)
