### ISSUE TITLE
release版本一混淆就出问题

### ISSUE THREAD

**Issue by clgg** [alibaba/vlayout#60]
已经加了-keepattributes InnerClasses
-keep class com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx {
    *;
｝
还是一打开页面就乱
 java.lang.NullPointerException
05-10 20:52:04.087 25410-25410/? W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$ChildHelperWrapper.show(ExposeLinearLayoutManagerEx.java:1921)
05-10 20:52:04.087 25410-25410/? W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.showView(ExposeLinearLayoutManagerEx.java:1440)
05-10 20:52:04.087 25410-25410/? W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.showView(VirtualLayoutManager.java:1102)
05-10 20:52:04.097 25410-25410/? W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.addChildView(VirtualLayoutManager.java:1067)
05-10 20:52:04.097 25410-25410/? W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.addChildView(VirtualLayoutManager.java:1061)
05-10 20:52:04.097 25410-25410/? W/System.err:     at com.alibaba.android.vlayout.layout.BaseLayoutHelper.nextView(BaseLayoutHelper.java:120)
05-10 20:52:04.097 25410-25410/? W/System.err:     at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:85)
05-10 20:52:04.097 25410-25410/? W/System.err:     at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:264)

这个怎么加混淆啊谁能指点一下

**Comment by clgg** [comment]
发现问题了
加上这些就可以了
-keep class android.support.v7.widget.RecyclerView$LayoutParams { *; }
-keep class android.support.v7.widget.RecyclerView$ViewHolder { *; }
-keep class android.support.v7.widget.ChildHelper { *; }
-keep class android.support.v7.widget.RecyclerView$LayoutManager { *; }

**Comment by longerian** [comment]
ok 更新下文档
