### ISSUE TITLE
staggeredLayout的item布局文件最外层是cardview，会忽略staggeredLayout上面的sticky的效果

### ISSUE THREAD

**Issue by jiangwei18** [alibaba/vlayout#61]
项目地址：https://github.com/jiangwei1517/VlayoutDemo
将最外层的LinearLayout改成CardView就异常了

staggered_item.xml:
<LinearLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/card"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    >

    <android.support.constraint.ConstraintLayout
        android:id="@+id/ll_main"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <ImageView
            android:id="@+id/iv"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:scaleType="fitXY"
            android:src="@mipmap/ic_launcher"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

    </android.support.constraint.ConstraintLayout>
</LinearLayout>

**Comment by longerian** [comment]
cardview有z轴小姑，需要将sticky的item设置一个更高的z参数。
