### ISSUE TITLE
跟SwipeRefreshLayout一起使用会有问题吗？

### ISSUE THREAD

**Issue by windwise** [alibaba/vlayout#62]
首次加载页面一直不停报下面这个空指针异常，去到另外一个界面再返回就没问题了，但是如果调用SwipeRefreshLayout的刷新又会继续报这个错误。求指点。
错误信息如下：
05-12 17:12:29.204 11277-11277/ W/System.err: java.lang.NullPointerException
05-12 17:12:29.206 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$b.b(ExposeLinearLayoutManagerEx.java:1921)
05-12 17:12:29.206 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.showView(ExposeLinearLayoutManagerEx.java:1440)
05-12 17:12:29.207 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.showView(VirtualLayoutManager.java:1102)
05-12 17:12:29.207 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.a(VirtualLayoutManager.java:1067)
05-12 17:12:29.207 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.a(VirtualLayoutManager.java:1061)
05-12 17:12:29.207 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.a.b.a(BaseLayoutHelper.java:120)
05-12 17:12:29.207 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.a.a.a(AbstractFullFillLayoutHelper.java:67)
05-12 17:12:29.207 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.a.k.b(OnePlusNLayoutHelper.java:177)
05-12 17:12:29.207 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.a.b.a(BaseLayoutHelper.java:264)
05-12 17:12:29.207 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:574)
05-12 17:12:29.208 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1140)
05-12 17:12:29.208 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:358)
05-12 17:12:29.208 11277-11277/ W/System.err:     at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:398)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.support.v7.widget.RecyclerView.N(RecyclerView.java:3583)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.support.v7.widget.RecyclerView.p(RecyclerView.java:3312)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.view.View.layout(View.java:15136)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4862)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.view.View.layout(View.java:15136)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4862)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.view.View.layout(View.java:15136)
05-12 17:12:29.208 11277-11277/ W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4862)
05-12 17:12:29.209 11277-11277/ W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
05-12 17:12:29.209 11277-11277/ W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
05-12 17:12:29.209 11277-11277/ W/System.err:     at android.view.View.layout(View.java:15136)
05-12 17:12:29.209 11277-11277/ W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4862)
05-12 17:12:29.209 11277-11277/ W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
05-12 17:12:29.209 11277-11277/ W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
05-12 17:12:29.209 11277-11277/ W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
05-12 17:12:29.209 11277-11277/ W/System.err:     at android.view.View.layout(View.java:15136)
05-12 17:12:29.209 11277-11277/ W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4862)
05-12 17:12:29.209 11277-11277/ W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
05-12 17:12:29.210 11277-11277/ W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
05-12 17:12:29.210 11277-11277/ W/System.err:     at android.view.View.layout(View.java:15136)
05-12 17:12:29.210 11277-11277/ W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4862)
05-12 17:12:29.210 11277-11277/ W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
05-12 17:12:29.210 11277-11277/ W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
05-12 17:12:29.210 11277-11277/ W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.view.View.layout(View.java:15136)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4862)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.view.View.layout(View.java:15136)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4862)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.view.View.layout(View.java:15136)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4862)
05-12 17:12:29.211 11277-11277/ W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.view.View.layout(View.java:15136)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4862)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2367)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2073)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1239)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6283)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:591)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:560)
05-12 17:12:29.212 11277-11277/ W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
05-12 17:12:29.213 11277-11277/ W/System.err:     at android.os.Handler.handleCallback(Handler.java:808)
05-12 17:12:29.213 11277-11277/ W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
05-12 17:12:29.213 11277-11277/ W/System.err:     at android.os.Looper.loop(Looper.java:193)
05-12 17:12:29.213 11277-11277/ W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5328)
05-12 17:12:29.213 11277-11277/ W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
05-12 17:12:29.213 11277-11277/ W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
05-12 17:12:29.213 11277-11277/ W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
05-12 17:12:29.213 11277-11277/ W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654)
05-12 17:12:29.213 11277-11277/ W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
05-12 17:12:29.214 11277-11277/ W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by longerian** [comment]
```
void show(View view) {
            try {
                ensureChildHelper();
                int index = **mRecyclerView**.indexOfChild(view); //空指针报的是这一行， 检查一下为什么这个mRecyclerView被置空了、
                args[0] = Integer.valueOf(index);
                mClearMethod.invoke(mInnerBucket, args);
                if (mInnerHiddenView != null)
                    mInnerHiddenView.remove(view);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
```

**Comment by longerian** [comment]
试了一下没有碰到你说的问题，请提供详细信息 。

**Comment by windwise** [comment]
@longerian 发现混淆后就有这个问题，没混淆没出现这个错误。
#VLayout的混淆代码
-keepattributes InnerClasses
-keep class com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx { *; }
-keep class android.support.v7.widget.RecyclerView$LayoutParams { *; }
-keep class android.support.v7.widget.RecyclerView$ViewHolder { *; }
-keep class android.support.v7.widget.ChildHelper { *; }
-keep class android.support.v7.widget.RecyclerView$LayoutManager { *; }
-keep class com.express.adapter.IndexBottomActiveAdapter{public static final <fields>;}
-keep enum com.express.adapter.SubAdapter$IndexAdapterItemType{*;}

**Comment by windwise** [comment]
@longerian 混淆文件中增加后解决
-keep class android.support.v7.widget.ChildHelper$Bucket{
    *;
}
