### ISSUE TITLE
给adapter 设置一个背景图片 ，来回滑动图片总跳，这个怎么处理啊

### ISSUE THREAD

**Issue by clgg** [alibaba/vlayout#63]
public LayoutHelper onCreateLayoutHelper() {   
     LinearLayoutHelper linearLayoutHelper = new LinearLayoutHelper();

        linearLayoutHelper.setLayoutViewBindListener(new BaseLayoutHelper.LayoutViewBindListener() {
            @Override
            public void onBind(View layoutView, BaseLayoutHelper baseLayoutHelper) {
                layoutView.setBackgroundResource(R.drawable.shadow_device_home_bg);
                Log.e("linearLayoutHelper","onBind"+ layoutView.getHeight());
            }
        });
在recyclerview中，动态改变item大小后，背景就开始抖动
当item滑出屏幕，这个设置背景会给当前的item自己再次设置一个背景，不知道是我这样设置背景有问题还是这个现在不能设置背景图片呢？有没有遇到过得给指点下啊

**Comment by longerian** [comment]
与 #57 类似的问题，目前先采用这样的方式避免：

> LayoutViewBindListener 是在布局过程中调用的，这个回调里加载完图片会触发布局过程，这样就循环了。你需要在绑定图片前判断一下是否加载完毕，加载完毕就不用重复加载图片了。这样就可以避免。

等我发布个新版本把这个逻辑内置到sdk里，外部提供图片加载的信息即可。

**Comment by longerian** [comment]
这个逻辑在1.0.6 sdk内部做了简单的封装，设置`DefaultLayoutViewHelper` 然后在图片加载成功的时候调用`onBindViewSuccess(View layoutView, String id)`方法即可。

**Comment by baiyuas** [comment]
看到这个方法了但是没看看哪里使用？我应该怎么使用呢？不是很 明白，可以在详细说明下么？

**Comment by longerian** [comment]
这个我一开始可能理解错了，应该是说 #275 里的问题。
