### ISSUE TITLE
使用GridLayoutHelper时，item中的图片比例会影响布局展示(严重！！！)

### ISSUE THREAD

**Issue by luddite1989** [alibaba/vlayout#71]
使用GridLayoutHelper出现了严重的错误排版，原因可能是后台传来的图片比例影响了item的展示。详情见下图：
**1.正常的展示为：**
![image](https://cloud.githubusercontent.com/assets/11624146/26184990/9de01af6-3bba-11e7-86f7-2c72782a8229.png)

**2.错乱的展示为：**
![image](https://cloud.githubusercontent.com/assets/11624146/26185016/d17d0d06-3bba-11e7-880b-349f3bde2da2.png)

![image](https://cloud.githubusercontent.com/assets/11624146/26185039/f252a73e-3bba-11e7-8faf-18156ca8013f.png)

**3.涉及代码：**
![image](https://cloud.githubusercontent.com/assets/11624146/26185068/21478f32-3bbb-11e7-9177-a33304e9d76b.png)

**Comment by longerian** [comment]
跟图片应该没关系，检查一下你的数据有没有动态更改的没有通知adapter的情况导致，这样可能导致内部索引错乱。
