### ISSUE TITLE
項目編譯失敗

### ISSUE THREAD

**Issue by pythoncat1024** [alibaba/vlayout#77]
clone 下來，導入到 Android studio 中，之前成功編譯過。這回clone 下來導入還是失敗。
`Error:Could not download layoutlib-api.jar (com.android.tools.layoutlib:layoutlib-api:25.2.2): No cached version available for offline mode`
大概是自定义了gradle配置，不是很懂。而且，感觉没有必要自定义gradle配置。自己写起来也麻烦吧...

**Comment by longerian** [comment]
你检查一下 Android studio的配置，这个 com.android.tools.layoutlib:layoutlib-api:25.2.2 不是vlayout所依赖的，另外你不要选中offline  mode

<img width="1169" alt="2017-05-23 11 20 31" src="https://cloud.githubusercontent.com/assets/1511489/26361729/7967abdc-400e-11e7-9aaa-39b656fdfea2.png">
