### ISSUE TITLE
某些Adapter不停地执行getItemViewType和getItemCount方法

### ISSUE THREAD

**Issue by windwise** [alibaba/vlayout#79]
代码如下，先说说我遇到的情况：
       数据填充完成后，商户列表(见代码注释)对应的DelegateAdapter.Adapter对象会随着轮播图的每次切换的时候不停地执行getItemViewType和getItemCount方法。轮播图所在的adapter也会不停地执行getItemViewType和getItemCount方法。轮播图的实现也是使用第三方的库，我不知道方不方便在这里贴上那个库的github地址，先贴上吧，[https://github.com/youth5201314/banner](url)。

    private void initVlayout(RecyclerView recyclerView) {

        final VirtualLayoutManager virtualLayoutManager = new VirtualLayoutManager(this, VirtualLayoutManager.VERTICAL);
        recyclerView.setLayoutManager(virtualLayoutManager);

        DelegateAdapter delegateAdapter = new DelegateAdapter(virtualLayoutManager, false);
        recyclerView.setAdapter(delegateAdapter);
        //滑动监听事件
        recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
                int visibleItemCount = virtualLayoutManager.getChildCount();
                int totalItemCount = virtualLayoutManager.getItemCount();
                if ((visibleItemCount > 0 && newState == RecyclerView.SCROLL_STATE_IDLE && (lastVisibleItemPosition) >= totalItemCount - 1)) {
                   
                    if (null != lifeShopListAdapter && !isLoadingMore) {
                        loadMoreData();
                    }
                }
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                lastVisibleItemPosition = virtualLayoutManager.findLastVisibleItemPosition();
            }
        });

        List<DelegateAdapter.Adapter> adapterList = new LinkedList<>();

        //创建顶部导航栏的layoutHelper
        SingleLayoutHelper gridViewPagerHelper = new SingleLayoutHelper();
        gridViewPagerAdapter = new GridViewPagerAdapter(this, gridViewPagerHelper, 1, Constant.GRIDVIEW_LIFESERVICE);
        adapterList.add(gridViewPagerAdapter);

        //创建商家活动的导航layoutHelper
        SingleLayoutHelper activeViewPagerHelper = new SingleLayoutHelper();
        activeViewPagerHelper.setMarginTop(8);
        activeGridViewAdapter = new ActiveGridViewAdapter(this, activeViewPagerHelper, 1);
        adapterList.add(activeGridViewAdapter);

        //创建轮播图layoutHelper
        SingleLayoutHelper bannerLayoutHelper = new SingleLayoutHelper();
        bannerLayoutHelper.setMarginTop(10);
        bannerAdapter = new LifeSerViceBannerAdapter(mContext, bannerLayoutHelper, 1);
        adapterList.add(bannerAdapter);

        //创建推荐商户列表layoutHelper
        LinearLayoutHelper shopListLayoutHelper = new LinearLayoutHelper();
        shopListLayoutHelper.setMarginTop(10);
        lifeShopListAdapter = new LifeShopListAdapter(mContext, shopListLayoutHelper, 1);
        lifeShopListAdapter.setRetryListener(new LifeShopListAdapter.RetryListener() {
            @Override
            public void onRetry() {
                loadMoreData();
            }
        });
        adapterList.add(lifeShopListAdapter);

        delegateAdapter.setAdapters(adapterList);

    }

**Comment by longerian** [comment]
根据经验 应该是你的业务代码里有某个地方一直在触发这个调用，笨一点的办法就是你通过排除法 逐步删减一些代码，看看是什么东西引起的。比如首先你先把这个轮播的组件检查一下。
