### ISSUE TITLE
关于 StickyLayoutHelper 

### ISSUE THREAD

**Issue by iielse** [alibaba/vlayout#8]
![1](https://cloud.githubusercontent.com/assets/7521943/23640436/a8fd2228-0328-11e7-9c41-5539dceae733.gif)
这个算bug吗? 下拉的时候，9有抖动，没有考虑到8里面设置的margin padding ?

**Comment by longerian** [comment]
正常态8的 margin 和 padding 已经考虑在内了，抖动是因为这个瞬间8的 margin 和 padding 没计算进去，算一个小bug。

**Comment by qinguyi** [comment]
可以提供个刷新数据的示例吗？数据改变需要重要delegateAdapter.setAdapters(adapters)吗
