### ISSUE TITLE
有多个adapter时，点击时如何获取某个adapter中的数据集的下标

### ISSUE THREAD

**Issue by AlwaysBeMySelf** [alibaba/vlayout#80]
每个Adapter中都有单独的一个list存放数据
    private static class HolderGoods extends RecyclerView.ViewHolder implements View.OnClickListener {
        ImageView ivImg;
        TextView tvName;
        ImageView ivShare;
        TextView tvShareCount;
        PriceTextView pricetvItem;
        private ItemClickListener mListener;

        HolderGoods(View itemView, ItemClickListener itemClickListener) {
            super(itemView);
            ivImg = (ImageView) itemView.findViewById(R.id.item_img);
            tvName = (TextView) itemView.findViewById(R.id.item_name);
            ivShare = (ImageView) itemView.findViewById(R.id.iv_share_item);
            tvShareCount = (TextView) itemView.findViewById(R.id.tv_share_count);
            pricetvItem = (PriceTextView) itemView.findViewById(R.id.pricetv_item);
            mListener = itemClickListener;
            itemView.setOnClickListener(this);
        }

        @Override
        public void onClick(View v) {
            if (mListener != null) {
                mListener.onItemClick(v, getAdapterPosition());// getAdapterPosition()获取到的是相对于整个RecycleView的位置，而不是相对于该adapter的位置，这里应该如何处理？？？？？？？？？？
            }
        }
    }

    public interface ItemClickListener {
        void onItemClick(View view, int postion);
    }

**Comment by longerian** [comment]
可以这么获取，先通过position找到对于的adapter位置信息，
```
int adapterPosition = getAdapterPosition();
Pair<AdapterDataObserver, Adapter> p = delegateAdapter.findAdapterByPosition(position);
int subAdapterPosition = adapterPosition - p.first.mStartPosition
```

**Comment by pinkApple** [comment]
@longerian  AdapterDataObserver由于是protected , 以及mStartPosition没有public,造成了kotlin在调java的时候出现无法访问mStartPosition的情况.

**Comment by alienzh** [comment]
请问你是怎么获取位置的，我也遇到这个问题了，访问不了

**Comment by longerian** [comment]
@pinkApple @alienzh  我加接口开放出来。

**Comment by AlwaysBeMySelf** [comment]
I solved this way.
`   @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        if (holder instanceof GoodsAdapter.HolderGoods) {
            HolderGoods holderGoods = (HolderGoods) holder;
            Goods goods = mDatas.get(position);
            holderGoods.tvName.setText(goods.getName());
            ImageLoaderHelper.displayGoodsItemImage(goods.getImgUrl(), holderGoods.ivImg);
            holderGoods.tvShareCount.setText(String.valueOf(goods.getShareCount()));
            holderGoods.pricetvItem.setRmbAndIntegration(goods.getPrice(), goods.getMixPrice(), goods.getIntegration(), goods.getSellType()).updateUI();
            holderGoods.itemView.setTag(position);
        }
    }` 



`  private static class HolderGoods extends RecyclerView.ViewHolder implements View.OnClickListener {
        View itemView;
        ImageView ivImg;
        TextView tvName;
        ImageView ivShare;
        TextView tvShareCount;
        PriceTextView pricetvItem;
        private OnItemClickListener mListener;

        HolderGoods(View itemView, OnItemClickListener itemClickListener) {
            super(itemView);
            this.itemView = itemView;
            ivImg = (ImageView) itemView.findViewById(R.id.item_img);
            tvName = (TextView) itemView.findViewById(R.id.item_name);
            ivShare = (ImageView) itemView.findViewById(R.id.iv_share);
            tvShareCount = (TextView) itemView.findViewById(R.id.tv_share);
            pricetvItem = (PriceTextView) itemView.findViewById(R.id.pricetv_item);
            mListener = itemClickListener;
            itemView.setOnClickListener(this);
        }

        @Override
        public void onClick(View v) {
            if (mListener != null) {
                mListener.onItemClick(v, (int) itemView.getTag());
            }
        }
    }`

By this way ,I can solve my problem easily.

**Comment by longerian** [comment]
增加了 `findOffsetPosition()` 方法，
或者用
```
    public static abstract class Adapter<VH extends RecyclerView.ViewHolder> extends RecyclerView.Adapter<VH> {
        public abstract LayoutHelper onCreateLayoutHelper();

        protected void onBindViewHolderWithOffset(VH holder, int position, int offsetTotal) {

        }
    }
```
中的 `onBindViewHolderWithOffset()` 方法代替传统的 `onBindViewHolder()` 方法，其中的 `position` 参数也是相对位置。

**Comment by softrice** [comment]
我拿到最新的release版本，AdapterDataObserver还是protect权限
