### ISSUE TITLE
FixLayoutHelper、ScrollFixLayoutHelper无法设置View铺满宽度，GridLayoutHelper显示异常

### ISSUE THREAD

**Issue by xueyaolive** [alibaba/vlayout#82]
code 1:
layoutParams = new VirtualLayoutManager.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, 300);
holder.itemView.setLayoutParams(new VirtualLayoutManager.LayoutParams(layoutParams));
无效
code 2:
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/tv_head"
    android:layout_width="match_parent"
    android:layout_height="70dp"
    android:gravity="center"
    android:text="固定头部"/>
无效

**Comment by xueyaolive** [comment]
还有GridLayoutHelper 有时出现布局是错误，经过滑动又正常了
布局样式：
item1  item2
item3           （正常情况）

错误 ：item3 有时跨2列了，占满了最后一列

**Comment by longerian** [comment]
第二个问题确实有bug，还需要解。第一个待排查

**Comment by longerian** [comment]
第一个问题，要调用一下`layoutHelper.setSketchMeasure(true);`，  默认情况下，这个内部是wrap_content的。
