### ISSUE TITLE
仿微信朋友圈布局用这个框架能不二级嵌套么?

### ISSUE THREAD

**Issue by a4081675** [alibaba/vlayout#83]
朋友圈信息和评论,普通方法应该是信息里面嵌套一个评论的RecyclerView
如果用这框架能实现不嵌套的么?   我只想到了循环添加adapter 那样感觉比嵌套都麻烦.
求大大支个招

**Comment by longerian** [comment]
不用循环嵌套，简单点弄，通过自定义view实现一条消息的内容与评论，给评论区做自己的回收复用。
