### ISSUE TITLE
嵌套spinner 当界面滑出后重新滑进来，spinner选项被初始化

### ISSUE THREAD

**Issue by houjianbo188** [alibaba/vlayout#85]

**Comment by longerian** [comment]
那你检查一下有没有被重新创建这个spinner

**Comment by dodola** [comment]
这种情况只能保存一下状态，等重新创建的时候再贴回去

**Comment by longerian** [comment]
不应该有重新创建，除非你页面一瓶里有大量的包含spinner的组件，超出了复用池的大小（默认是5），那么重新滑进来，会创建的新的。

**Comment by houjianbo188** [comment]
因为赶时间，我直接换成单选了，单选没有出现问题，具体原因没有弄明白，后面时间空了来处理这个问题
