### ISSUE TITLE
如何动态的隐藏显示一个layout?

### ISSUE THREAD

**Issue by Justin777s** [alibaba/vlayout#86]
如何动态的隐藏显示一个layout?

**Comment by longerian** [comment]
调用adapter的remove方法把它移除掉，如果只是要隐藏，那就把view的visibility设置为gone

**Comment by yinyinnie** [comment]
removeAdapter之后，看源码，貌似还是需要notifyDataSetChanged吧？

**Comment by softrice** [comment]
removeAdapter后需要notifyDataSetChanged么
