### ISSUE TITLE
快速上下滑动会出现某些随机cell莫名悬浮效果，不可取消，多个手机上可频繁复现

### ISSUE THREAD

**Issue by yanyusong** [alibaba/vlayout#87]

**Comment by yanyusong** [comment]
![image](https://cloud.githubusercontent.com/assets/5779087/26751207/bddd93f2-4866-11e7-9ac3-88ac398986cd.png)

**Comment by longerian** [comment]
没有遇到过这种场景，你的页面里有没有使用过吸底相关的layoutHelper？

**Comment by yanyusong** [comment]
经过多次测试看看源码，我感觉应该是Tangram中GroupBasicAdapter的问题，很抱歉在这里问有关Tangram的问题，因为我不确定到底是哪里的问题。开启开发者模式以后如图：
![image](http://ofc92njab.bkt.clouddn.com/C4A4409F-2350-4263-AC0D-1A85042687B0.png?imageView2/5/w/400/h/250/q/75|imageslim)
![image](http://ofc92njab.bkt.clouddn.com/F98E3B1E-95A8-4713-A4FD-8BAABC926D54.png?imageView2/5/w/400/h/250/q/75|imageslim)
可以看到标出来的两处没有控件的边框，说明不是条目复用的问题，我在Tangram中GroupBasicAdapter里的setdata方法里看到了如下代码：
```
    public void setData(@Nullable List<L> cards, boolean silence) {
        createSnapshot();

        mCards.clear();
        mData.clear();


        if (cards != null && cards.size() != 0) {
            mCards.ensureCapacity(cards.size());
            setLayoutHelpers(transformCards(cards, mData, mCards));
        } else {
            setLayoutHelpers(Collections.<LayoutHelper>emptyList());
        }

        diffWithSnapshot();

        if (!silence)
            notifyDataSetChanged();
    }
```
我感觉问题代码在于createSnapshot();和 diffWithSnapshot();，然后在快速刷新数据的时候，出现了屏幕上的残影无法清除，但是现在还不知道问题该如何解决，项目这几天就要上线，急求解决，我QQ：1924355291，希望和您一块讨论下，万分感谢
@longerian

**Comment by yanyusong** [comment]
解决方法：# 将图片加载框架从Glide更换为Picasso

我将代码抽离出来，一块一块的注释、对比、调试、验证，终于发现了问题所在 0.0，要哭了😭，问题在于图片加载框架的问题。
```
        TangramBuilder.init(ct, new IInnerImageSetter() {
            @Override
            public <IMAGE extends ImageView> void doLoadImageUrl(@NonNull IMAGE view, @Nullable String url) {      
                Picasso.with(ct).load( url).into(view);
            }
        }, ImageView.class);
```
我一直用的Glide，所以出现了问题😭，改成Picasso以后，问题就解决了，我会在Tangram项目中提个Issues，希望能重视测试一下哈

**Comment by longerian** [comment]
@yanyusong 辛苦了  话说Glide具体做了什么引起这个问题，有没有研究过。

**Comment by KarelGT** [comment]
使用Glide遇到同样的问题…

**Comment by liufsd** [comment]
但是Picasso不支持gif展示。这就麻烦了的。
