### ISSUE TITLE
怎么添加上拉加载

### ISSUE THREAD

**Issue by longshihan1** [alibaba/vlayout#88]
在Recyclerview不太容易获取到itemcount，layoutmanager可能用的不止一个，无法判断是否到底最低处

**Comment by dodola** [comment]
layoutmanager一个rv应该只会对应一个吧，应该可以用
` delegateAdapter.getItemCount() - 1 == layoutManager.findLastVisibleItemPosition()
` 来判断 @longshihan1

**Comment by JeasonWong** [comment]
可以增加个loadMore组件，attach的时候触发下

**Comment by longerian** [comment]
上拉加载都需要自己封装，vlayout主要做布局，不做这些额外逻辑，除了 @dodola 提供的方法，也可以用 #110 里演示的方法。
