### ISSUE TITLE
关于FLoatLayoutHelpter

### ISSUE THREAD

**Issue by ruodezizaiyi** [alibaba/vlayout#91]
1.在使用FloatLayoutHelper最后的动画AnimatorX时,(以右下角为例)发现translationX与Default设置的int x比较,发现相差10px, 也就是view会有10px宽度部分被隐藏

2.当返回指定位置时,需要重写BaseLayoutHelper,FixAreaLayoutHelper和FloatLayoutHelper,可不可以暴露一个方法,或者将mAspectRatio public

**Comment by longerian** [comment]
1. FloatLayoutHelper，动画做完之后会吸到屏幕边缘，而不是初始位置，至于你说的view会有10px被隐藏，我倒没有发现有这个问题

2. mAdpectRatio本来就有set方法，应该可以的吧
