### ISSUE TITLE
关于RangeGridLayoutHelper

### ISSUE THREAD

**Issue by ruodezizaiyi** [alibaba/vlayout#93]
会重复called detach on an already detached child,报IllegalArgumentException

**Comment by ruodezizaiyi** [comment]
版本 25

**Comment by ruodezizaiyi** [comment]
找到原因了.....不能使用VirtualLayoutManager.LayoutParam

**Comment by longerian** [comment]
可以把详细信息贴一下，不太明白『不能使用VirtualLayoutManager.LayoutParam』是什么意思。
