### ISSUE TITLE
new两个linerlayoutHelper  是必须有相同的ViewHodler吗？

### ISSUE THREAD

**Issue by 18311023368** [alibaba/vlayout#98]
我new了两个adapter添加进去  ，然后如果ViewHodler不一致会导致卡顿的问题，但是如果一样的话 就没事  请问 怎么解决

**Comment by longerian** [comment]
应该是你的itemviewtype类型使用有问题，导致viewholder复用的时候类型转换出错，你检查一下

**Comment by longerian** [comment]
具体可以参考 #126 ， 没有其他问题就关闭啦
